Feat/#106 게시글 등록, 수정 시 이미지 10개 검증 로직을 추가
woowacourse-teams/2023-edonymyeon pull request #107
Opened 2023-07-24 06:29 UTC by hectick

## 🔥 연관 이슈

- close: #106 

## 📝 작업 요약

- 게시글 등록, 수정 시 이미지 10개 검증 로직을 추가
- 테스트할때 이미지가 생성되어 저장되는 테스트 클래스들에 `@AfterEach`로 해당 디렉토리의 이미지 파일들을 삭제하는 테스트 추가

## 🔎 작업 상세 설명

게시글 등록, 수정 시 이미지 10개 검증 로직을 추가
- 이미지 개수 검증의 위치를 최대한 도메인으로 집어넣고 싶었으나, 이미지 파일이 생성되어 디렉토리에 저장되기 전에 이미지 개수 검증을 하기 위해 적당히 서비스와 타협하였습니다. 😭 그래서 현재 서비스에서 Post 클래스의 isValidImageNumber 메서드를 호출해서 이미지 개수를 검증하고 있습니다만, 좋은 의견 있으시면 코멘투 주세요 ~! 적극 반영해보겠습니다~
- 관련 테스트 코드를 추가했습니다. (PostServiceTest)

테스트할때 이미지가 생성되어 저장되는 테스트 클래스들에 `@AfterEach`로 해당 디렉토리의 이미지 파일들을 삭제하는 테스트 추가
- Post 관련 테스트들 중, 이미지를 생성하는 테스트 클래스들에게 테스트가 끝난 후 이미지 파일 지우는 코드를 추가했습니다.

2023-07-24 07:21 UTC, BackFoxx requested changes
몇가지 리팩토링이 필요한 부분이 있어 Request Changes 하겠습니다.
기능은 잘 동작해요 수고하셨어요~!!

2023-07-24 07:21 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceFindingAllPostsTest.java
> +    }
오 파일 삭제 잘 동작하네요~~ 수고하셨습니다 👍🏻

2023-07-24 07:21 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/ui/PostControllerTest.java
> +    }
AfterEach 코드가 클래스마다 중복구현 되어있는데
이미지 삭제 코드를 별도의 public static 코드로 분리하거나 상속을 사용하면 유지보수성이 향상될 것 같아요

2023-07-24 07:21 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    }
혹시 이 AfterEach 코드를 IntegrationTest로 옮겨도 잘 동작하나요? 궁금해지네요 😮

2023-07-24 07:21 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
> +    public boolean isValidImageNumber(final Integer imageNumber) {
이미지 개수를 검증하는 코드인데 이름이 isValidImageNumber라서 의미를 파악하는 데에 어려움이 있었어요 😵

GPT에서 더 적절한 네이밍을 몇 개 추천해주었으니 개선 부탁드려요!
* isValidImageCount
* isValidNumberOfImages
* isImageCountValid

2023-07-24 07:21 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
> +    public static final int MAX_IMAGE_NUMBER = 10;
팀 컨벤션 따라 다르겠지만 요것도 number보다 count가 가시성 있지 않을까 생각해요!

2023-07-24 07:21 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
> +    POST_IMAGE_NUMBER_INVALID(2667, "게시글 하나에 이미지는 최대 10개까지 등록 가능합니다."),
```java
POST_IMAGE_NUMBER_INVALID(2667, String.format("게시글 하나에 이미지는 최대 %d개까지 등록 가능합니다.", Post.MAX_IMAGE_NUMBER))
```
요렇게 하면 상수 값이 변경되었을 때 조금 더 유연한 메시지를 보낼 수 있는데
요건 이 메시지 뿐만 아니라 모든 메시지에 해당하는 내용이니
나중에 누군가 이슈 생성해서 리팩토링 해줘야 할 듯~~

2023-07-24 07:21 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +        }
post.updateImages(postImageInfos)에서 이미지 개수 검증을 이미 하고 있는데
여기서 또 하고 있네요~!

2023-07-24 08:24 UTC, jyeost approved these changes
수고하셨슴미다 ~~~

2023-07-24 08:24 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceFindingAllPostsTest.java
> +    }
222222 수고하셨어영 ><

2023-07-24 10:21 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    }
오~ 잘 동작하네용~~

2023-07-24 10:22 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
> +    public static final int MAX_IMAGE_NUMBER = 10;
죠은 생각입니당

2023-07-24 12:11 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/ui/PostControllerTest.java
> +    }
상속으로 분리하기엔 PostIntegrationTest가 이미 IntegrationTest를 상속받고 있어서,
중복 코드를 인터페이스로 분리해봤어요!

2023-07-24 12:12 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
> +    POST_IMAGE_NUMBER_INVALID(2667, "게시글 하나에 이미지는 최대 10개까지 등록 가능합니다."),
이부분은 나중에 이슈로 하는 것으로 ~

2023-07-24 13:21 UTC, This2sho reviewed
이리저리내씨 고생하셨습니다.
고생의 의미로 새우🍤 하나 드릴게유 👍

코드 보고 생각난거 몇개 댓글 남겼습니다~

2023-07-24 13:21 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
>          final List<PostImageInfo> postImageInfos = uploadImages(postRequest).stream()
그리고 지금 `List<ImageInfo>` 이 부분 로직이 많은데 일급컬랙션도 한 번 고려해볼 수 있지 않을까유?!

2023-07-24 13:21 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceFindingAllPostsTest.java
> +    }
고생하셨습니다유!

2023-07-24 13:21 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceFindingAllPostsTest.java
> +        assert files != null;
`assert`는 뭐하는 용도인가유?

2023-07-24 14:19 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
>          final List<PostImageInfo> postImageInfos = uploadImages(postRequest).stream()
> 그리고 지금 List<ImageInfo> 이 부분 로직이 많은데 일급컬랙션도 한 번 고려해볼 수 있지 않을까유?!

현재 있는 로직들이 주로 ImageInfo <-> PostImageInfo 간의 변환로직들인데, 부모 클래스에서 자식클래스를 알고있다는 것이 이상하다고 생각하여 선뜻 변환로직을 숨기지 못했슴니다 ㅠㅠ
대신 지금 코드를 다시보다보니 자식클래스 -> 부모클래스로의 불필요한 변환로직들이 존재하길래 제거하엿습니당

2023-07-24 14:34 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
>          final List<PostImageInfo> postImageInfos = uploadImages(postRequest).stream()
PostImageInfos 한번 만들어봤어용 이런 느낌이 맞으신가용

2023-07-24 15:25 UTC, hectick commented
https://github.com/woowacourse-teams/2023-edonymyeon/pull/107#discussion_r1272236931
위 리뷰를 반영하면서 PostImageInfos 일급 컬렉션을 도입해 보았어요!
https://wbluke.tistory.com/23
위 블로그를 보니 **_일급컬렉션에 @Embeddable 어노테이션을 달아준다면, 엔티티에서도 일급 컬렉션을 가질 수 있길래_** Post가 List<PostImageInfo> 대신 PostImageInfos라는 일급 컬렉션을 가지도록 바꾸어보았어요!
이것이 괜찮은 변화일지 의견 부탁드립니당.. @This2sho @BackFoxx @jyeost

2023-07-25 11:05 UTC, This2sho approved these changes
고생하셨습니다..
다 잘 바 꼈 네 요..
(하 지 만, PostService가 로직이 많아 보 이 는 건 저 만 그 런 건 가 요 혹 시 ?! 나중에, 대대적인 수정이 필요할지도....)

2023-07-25 11:20 UTC, BackFoxx approved these changes
고생많으셨어요~~~~머지하겠습니다 오늘은 푹 쉬세요

2023-07-25 11:20 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/ImageFileCleaner.java
> +}
왜 추상클래스가 아니라 인터페이스인가 했는데 다중상속 문제 때문에 이렇게 했나보네요~~~
요걸 추상클래스로 선언하고 IntegrationTest가 얘를 상속하게 설계한다면 다중상속 문제가 해결되지 않았을까 싶지만 요정도도 충분히 좋은 것 같아요!!

2023-07-25 11:20 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java
> +}
오 일급컬렉션~~~~~~~~~~~~~~~~~~~~~~따봉맨

2023-07-25 11:20 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/ImageFileCleaner.java
> +        final File targetFolder = new File("src/test/resources/static/img/test_store/");
URI 하드코딩 ㅡ.ㅡ 이번만 봐드립니다

2023-07-26 01:50 UTC, merged