Fix/#105 페이징 트러블슈팅
woowacourse-teams/2023-edonymyeon pull request #117
Opened 2023-07-25 11:02 UTC by BackFoxx

## 🔥 연관 이슈

- close: #105 

## 📝 작업 요약

postService.findAllPosts() 메소드 실행시
게시글 조회 SELECT 1개 + 회원 조회 SELECT 1개 + 게시글 이미지 조회 SELECT N(조회한 게시글 수)개로
총 1+1+N개의 SELECT쿼리가 전송되는 성능 버그를 개선했습니다.

## 🔎 작업 상세 설명

@BatchSize를 지정함으로써
각각의 SELECT문으로 발송되는 N개의 쿼리를
하나의 in절로 묶어 발송함으로써
N+1+1개를 (N/batchSize)+1+1개로 줄이는 데에 성공했습니다.

상세한 개선 과정은
[이돈이면 기술블로그](https://velog.io/@idonymyeon/N1-Pageable-%ED%8A%B8%EB%9F%AC%EB%B8%94%EC%8A%88%ED%8C%85-%EC%97%AC%ED%96%89%EA%B8%B0-vobk675g)에 상세히 기술했습니다.

2023-07-26 04:18 UTC, jyeost reviewed
여우 블로그 글 잘 봤습니다 ~~ 
너무 수고했어용 🦊❤️‍🔥

2023-07-26 04:18 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +        final Slice<Post> foundPosts = postRepository.findAllBy(pageRequest);
저 궁금한게 있는데 컬렉션을 Slice를 사용한 이유가 있나요?

2023-07-26 04:18 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    void 한_번에_3개씩_조회하는_조건으로_전체게시글_조회(@Autowired PostService postService) {
`@batchSize`를 사용하고 있는데 해당 테스트가 의미가 있나용??
(사이즈를 클라이언트로부터 유동적으로 받아와야 하는 이유가 있을까요...)
또 파라미터에 사이즈로 0이나 음수값이 들어오면 어떻게 되나요?

2023-07-26 04:18 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
>      public List<GeneralPostInfoResponse> findAllPost(final GeneralFindingCondition generalFindingCondition) {
findAllPost라는 이름이 현재 메서드를 설명하기 부족한 것 같아요

2023-07-26 04:18 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    void 기본조건으로_전체게시글_조회(@Autowired PostService postService) {
postService가 꽤 많은 곳에서 쓰이고 있는데 전역으로 빼면 안되나요?

2023-07-26 06:09 UTC, This2sho requested changes
고생하셨습니다. 🦊 선생님
수정한거 보고 테스트하다가 `Member`도 N+1 문제가 발생하는걸 발견했습니다..
한번 더 고생을 해주시면..😅

2023-07-26 06:09 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +        한_사용자가_게시글을_서른개_작성한다(postService);
여러 사용자가 작성한 것도 테스트하면 좋지 않을까유?!

2023-07-26 08:07 UTC, BackFoxx reviewed
코드리뷰 반영했어요~~~

2023-07-26 08:07 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +        한_사용자가_게시글을_서른개_작성한다(postService);
한 사람이 여러 게시글을 작성하던 기존 더미데이터를 수정했어요!

2023-07-26 08:18 UTC, hectick reviewed
성능개선 조아요

2023-07-26 08:18 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    }
```suggestion
    private Member 사용자를_하나_만든다() {
        return memberTestSupport.builder()
                .build();
    }
```
이렇게 쓰면 범용성이 넓어질것 같아용

2023-07-26 08:18 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
이번에 수정된 부분이 아니라 리뷰를 어떻게 남겨야할지 몰라서 여기 남겨봅니다!
여기 290번째 줄에
`.auth().preemptive().basic("email", "password")`
->`.auth().preemptive().basic(member.getEmail(), member.getPassword())`

2023-07-26 08:37 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
블로그 글 1개 더 써주세요 ~ㅎㅎ

2023-07-26 09:01 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    void 한_번에_3개씩_조회하는_조건으로_전체게시글_조회(@Autowired PostService postService) {
현재 sortBy나 sortDirection 도 적절한 예외처리가 안되어있는 것 같은데
쿼리 파라미터인 만큼 예외 처리가 확실히 되어있는 상태에서 확장성을 고려했으면 좋겠습니다

2023-07-26 09:04 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    void 한_번에_3개씩_조회하는_조건으로_전체게시글_조회(@Autowired PostService postService) {
현재 sortBy나 sortDirection 도 적절한 예외처리가 안되어있는 것 같은데
쿼리 파라미터인 만큼 예외 처리가 확실히 되어있는 상태에서 확장성을 고려했으면 좋겠습니다
또 페이징을 사용하는 곳이 많은데, 컨벤션을 맞추던가 다같이 쓰는 클레스가 있었으면 좋겠어요 :)

2023-07-26 09:05 UTC, jyeost approved these changes

2023-07-27 01:50 UTC, This2sho approved these changes
반영된거 확인했습니다.
고생하셨어요 👍

2023-07-27 07:50 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    }
IntegrationTest를 위해 응답 객체를 반환하는 Support 클래스를 만들었어요!!!! 야호

2023-07-27 07:50 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    void 한_번에_3개씩_조회하는_조건으로_전체게시글_조회(@Autowired PostService postService) {
어디서든 페이징을 쉽게 사용할 수 있도록 
@PostPaging 어노테이션과 함께 Condition 객체를 컨트롤러의 인자로 받아 쉽게 사용할 수 있게 개선했습니다!

2023-07-27 07:51 UTC, hectick approved these changes

2023-07-27 07:52 UTC, merged