Fix/#145 게시글 수정 api 변경
woowacourse-teams/2023-edonymyeon pull request #148
Opened 2023-07-27 06:25 UTC by hectick

## 🔥 연관 이슈

- close: #145 

## 📝 작업 요약

안드로이드와의 연동 과정에서, 게시글 수정할 때, 서버가 보내준 이미지의 url을 안드로이드에서 multipartFile로 바꾸어 보낼수 없는 이슈가 있었습니다.

해당 문제를 해결하기 위해, 아래와 같이 api를 수정하고 코드도 수정하였습니다.

```
PUT /posts/{postId} HTTP/1.1

{
	"게시글 제목(title)": "이거 사도되나요?",
	"게시글 내용(content)": "살까 말까 고민중인데, 추천좀 해주세요.",
	"상품 가격(price)": 13000,
	"이미지들(originalImages)": ["http://naver.com/image/1.jpg","http://naver.com/image/2.jpg"] // 삭제되지 않고 잔류한 이미지들의 url들
	"이미지들(newImages)": //새로운 이미지들을 multipart로
}
```

## 🔎 작업 상세 설명

삭제되지 않고 잔류되는 이미지들(originalImages)는 이미지 파일을 새로 생성하지 않고 기존 이미지 파일을 유지합니다.
삭제되는 이미지들(originalImages에 포함되어 있지 않은 이미지들)은 디렉토리와 데이터베이스에서 삭제합니다.
새로 추가된 이미지들(newImages)은 디렉토리와 데이터베이스에 새로 생성됩니다.

## 🌟 리뷰 요구 사항

> `http://naver.com/image/1.jpg` -> `1.jpg`로 바꾸는 로직을 어디다가 넣어줄까 고민하다가 현재 가장 관련있는 Domain 클래스에 있는데 괜찮을까요?

2023-07-27 15:32 UTC, BackFoxx approved these changes
작업량이 엄청 많네요 이리내~~~~ 수고 많으셨어요
자잘한 네이밍 외에는 특별히 주의할 점이 안 보여요
그나마 신경쓰이는 점이라면 이번 Fix로 인해 PostService가 엄청 커졌다는 거?
별도의 클래스로 분리할 수 있는 게 있을 지 같이 고민해보아요!!

2023-07-27 15:32 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
> +    IMAGE_DOMAIN_INVALID(50001, "이미지의 url 경로가 잘못되었습니다."),
50,001

2023-07-27 15:32 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/image/domain/Domain.java
> +        }
흠 replace 메소드를 호출할 때 domain 문자열이 들어가있지 않더라도 문제가 생기지는 않는데 
이 예외처리가 꼭 필요할까요?

2023-07-27 15:32 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java
> +        //todo: postImageInfos의 post를 null로 세팅해줘야 할까?
저는 그케 해야 한다고 생각해요!

2023-07-27 15:32 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +            final PostModificationRequest request
네이밍 좋은데욥?

2023-07-27 15:32 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +                .extract();
최근 머지된 PR에 PostIntegrationSupport가 추가되었으니 활용해보세요 :)

2023-07-27 17:32 UTC, This2sho requested changes
고생하셨슴돠 이리내🍤
리뷰달았으니 한번 봐주시면 감사하겠습니다링

2023-07-28 00:56 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/image/domain/Domain.java
> +        }
http://foxxbabo.com/image.jpg
가 들어올수도 있잖아요~!

2023-07-28 00:57 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
> +    IMAGE_DOMAIN_INVALID(50001, "이미지의 url 경로가 잘못되었습니다."),
^^.... 수정하겠슴돠

2023-07-28 01:02 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java
> +        checkImageAdditionCount(1);
서비스에서 바로 호출하는 경우도 있는데, 그때는 1이 아닐수도 있어서 저렇게 하였습니다!!
validate로 통일할게용

2023-07-28 01:05 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java
> +        //todo: postImageInfos의 post를 null로 세팅해줘야 할까?
오케이 죠습니다

2023-07-28 01:05 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +            final PostModificationRequest request
굿굿

2023-07-28 01:06 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +                .extract();
좋아유!

2023-07-28 01:06 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
> +    IMAGE_DOMAIN_INVALID(50001, "이미지의 url 경로가 잘못되었습니다."),
🙀

2023-07-28 01:06 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/image/domain/Domain.java
> +    }
감사링

2023-07-28 01:09 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceTest.java
> +                .buildImagesForCreatePost();
짱이죠

2023-07-28 01:09 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +        final Member 게시글_쓴_사람 = memberTestSupport.builder()
ㄷㄷㄷ

2023-07-28 01:09 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +                .statusCode(HttpStatus.OK.value());
support를 써보겟슴니다

2023-07-28 01:09 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
> +    public List<PostImageInfo> getUnmatchedPostImageInfos(final List<String> storeNames) {
굳이네요

2023-07-28 01:10 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java
> +                .collect(Collectors.toList());
굳이네요

2023-07-28 01:10 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
> +        postImageInfos.checkImageAdditionCount(imageAdditionCount);
화긴.

2023-07-28 01:23 UTC, jyeost commented
> 그나마 신경쓰이는 점이라면 이번 Fix로 인해 PostService가 엄청 커졌다는 거?
> 별도의 클래스로 분리할 수 있는 게 있을 지 같이 고민해보아요!!

저도 이 부분이 신경쓰여서 서비스에서 조회 부분들을 따로 분리하고 싶어요

2023-07-28 02:03 UTC, jyeost requested changes
복잡한 로직인데 넘 열심히 잘해주셨근요!!!!
역시 이리내 👍 👍 
api 테스트 코드 점 추가해주시면 바아로 머지 날리겟습니당근

+) 아 그리고 사진 관련 테스트에 log() all() 지워주십셔

2023-07-28 02:28 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceTest.java
죠습니다

2023-07-28 08:47 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +    @Test
반영하엿습니당

2023-07-28 08:50 UTC, hectick commented
PostIntegrationTest 코드 작성하다가 변수명들은 한글로 통일시켰습니다^^....

2023-07-28 09:05 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/image/domain/Domain.java
> +        }
흠~ 🤨 if문 안의 코드로 해당 맥락을 파악하기 힘들어서 제가 코드를 잘못 읽었네요!
imageUrl이 우리 도메인의 url을 가지고 있는지 검증하려는 의도라면

* isSameDomain(imageUrl)
* isInProjectDomain(url) 등의 이름을 가진 메소드로 한 번 더 래핑해주시면 가독성이 오를 것 같습니다

2023-07-28 09:07 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/image/domain/Domain.java
> +        }
validateDomainOfUrl(imageUrl)로 분리했ㅅ브니당~!

2023-07-28 09:12 UTC, jyeost approved these changes

2023-07-28 09:24 UTC, This2sho approved these changes
고생했어요 이리매👍

2023-07-28 10:02 UTC, merged