Feat/#139 검색 게시글 전체조회, 페이징 처리
woowacourse-teams/2023-edonymyeon pull request #150
Opened 2023-07-27 08:51 UTC by jyeost

## 🔥 연관 이슈

- close: #139 

## 📝 작업 요약
 제목에 검색어가 포함되면 조회되도록 한다
 내용에 검색어가 포함되면 조회되도록 한다
 request 파라미터로 받아온 조건으로 페이징 처리하도록 한다.

## 🔎 작업 상세 설명
처음엔 정적 쿼리로 구현하였다가 JpaSpecificationExecutor를 사용하여 좀 더 확장 가능성 있도록 구현하였습니다.
이를 사용하는 과정에서 기존 코드를 재활용하기 위하여 페이징 처리도 같이 해주었습니다...

현재는 파라미터로 넘어온 모든 키워드를 기준으로 제목이나 내용에 정확하게 포함이 되어있다면 조회해오도록 되어있는데
"청소기 다이슨" 처럼 여러 키워드로 검색하는 경우를 생각하여 띄워쓰기를 기준으로 검색어를 
"청소기" "다이슨" 과 같이 나누어 해당 키워드들이 전부 포함되어 있다면 "청소기 사려는데 다이슨 괜찮은가요?" 와 같은 글도 조회해올까... 하는 고민중에 있습니다.

성능적인 부분도 같이 고려해주었으면 감사하겠읍니다 ㅎ.ㅎ

2023-07-27 08:54 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/global/controlleradvice/GlobalExceptionHandler.java
> +
이 부분 요청에 필수 파라미터가 들어오지 않으면 자동으로 핸들러에서 잡아주는 형태라서 이렇게 구현했습니다...
에러 컨벤션에 맞춰 기본 코드와 메세지를 포함했으나, 해당 Exception에 더 상세한 설명이 있어서 일단 함께 첨부하도록 하였습니다

2023-07-27 08:55 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +        final Specification<Post> searchResults = PostSpecification.searchBy(searchWord);
이 부분에서 return 값이 Specification<Post> 타입으로 고정이여서 return의 stream문을 재활용 하기 위해서 
밑의 findAll에서 첫번째 파라미터로 사용하게 하기위해 페이징 처리도 함께 해주었습니다

2023-07-28 02:53 UTC, This2sho requested changes
처음엔 정적 쿼리로 구현하였다가 JpaSpecificationExecutor를 사용하여 좀 더 확장 가능성 있도록 구현하였습니다.
이를 사용하는 과정에서 기존 코드를 재활용하기 위하여 페이징 처리도 같이 해주었습니다...

현재는 파라미터로 넘어온 모든 키워드를 기준으로 제목이나 내용에 정확하게 포함이 되어있다면 조회해오도록 되어있는데
"청소기 다이슨" 처럼 여러 키워드로 검색하는 경우를 생각하여 띄워쓰기를 기준으로 검색어를
"청소기" "다이슨" 과 같이 나누어 해당 키워드들이 전부 포함되어 있다면 "청소기 사려는데 다이슨 괜찮은가요?" 와 같은 글도 조회해올까... 하는 고민중에 있습니다.

성능적인 부분도 같이 고려해주었으면 감사하겠읍니다 ㅎ.ㅎ

`Specification` 처음 봤는데 repository에 일일이 메소드 정의 안해도 되고 좋네염
띄워쓰기를 기준으로 검색어를 나누면 확실히 검색이 정확할거 같네유 성능적인 부분은DB에서 조회할 때 단어 하나 마다 2배씩 느려지지 않을까유?

2023-07-28 02:53 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/post/ui/ReadPostController.java
> +                .body(new GeneralPostsResponse(posts));
`Controller`에서 `GeneralPostsResponse`를 생성한 이유가 있나융? 🥺

2023-07-28 02:53 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/global/controlleradvice/GlobalExceptionHandler.java
> +
에러 메시지가 거의 동일한거 같아서 저는 기존 예외 메시지는 빼도 될거 같아유 🙃

"필수 쿼리 파라미터가 비었습니다.Required request parameter 'query' for method parameter type String is not present"

2023-07-28 02:53 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +        final Specification<Post> searchResults = PostSpecification.searchBy(searchWord);
무슨 소린지 모르겠어욤

2023-07-28 06:59 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/ui/ReadPostController.java
> +                .body(new GeneralPostsResponse(posts));
기존 전체 게시글 조회의 여우 코드 따라갓습니다

2023-07-28 07:03 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/global/controlleradvice/GlobalExceptionHandler.java
> +
기존 예외 메시지가 영어로 된 메세지 말하는 걸까여??
'query' 부분에 어떤 파라미터가 비었는지 알려줘서 파라미터가 여러개인 경우 유용할거라고 생각햇어요

2023-07-28 07:10 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/integration/PostSearchIntegrationTest.java
> +        writePost(member, "사과 먹고 싶어요", "사먹어도 되나요? 자취생인데...", 14_000L);
언제 나몰래 만들엇쥐

2023-07-28 07:24 UTC, hectick reviewed
고생하셧슴니당 멋지네유

> 현재는 파라미터로 넘어온 모든 키워드를 기준으로 제목이나 내용에 정확하게 포함이 되어있다면 조회해오도록 되어있는데
> "청소기 다이슨" 처럼 여러 키워드로 검색하는 경우를 생각하여 띄워쓰기를 기준으로 검색어를
> "청소기" "다이슨" 과 같이 나누어 해당 키워드들이 전부 포함되어 있다면 "청소기 사려는데 다이슨 괜찮은가요?" 와 같은 글도 조회해올까... 하는 고민중에 있습니다.

서비스 사용자로썬 필요한 기능이라고 생각함돠

2023-07-28 07:24 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/repository/PostSpecification.java
> +    }
오호 이것이 JpaSpecificationExecutor를 쓸때 필요한 것인가 보군용
👍👍👍👍

2023-07-28 07:24 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +        final Specification<Post> searchResults = PostSpecification.searchBy(searchWord);
Specification 타입은 바로 stream을 쓸 수 없어서,
findAll로 다시 조회를 해오는데, 페이징 처리가 필수 파라미터라 페이징 처리도 함께했다는 걸까요?
<img width="627" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/62106852/1352a429-fac9-41e6-b73b-49da0a952d36">

2023-07-28 07:24 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostSearchIntegrationTest.java
> +                .statusCode(HttpStatus.BAD_REQUEST.value());
log().all() 삭제 부탁드립니당

2023-07-28 07:24 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostSearchIntegrationTest.java
> +                .statusCode(HttpStatus.BAD_REQUEST.value());
그리고 응답을 추출해서 예외가 발생했을 때 예외 코드나 메세지도 같이 검증하면 좋을 것 같아요

2023-07-28 08:43 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceSearchPostsTest.java
> +    private final PostRepository postRepository;
3줄 한꺼번에 써주실 순 없는 부분???? 💢

2023-07-28 08:44 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceSearchPostsTest.java
> +                    softly.assertThat(검색결과.get(0).id()).isEqualTo(postId2);
현재 포스트에 equals가 필요한 로직이 없는데 
테스트를 위해 추가해도 되나용?

2023-07-28 08:45 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/integration/PostSearchIntegrationTest.java
> +        memberRepository.save(member);
감사합니다람쥐 :-)

2023-07-28 08:57 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/integration/PostSearchIntegrationTest.java
> +                .statusCode(HttpStatus.BAD_REQUEST.value());
추가하였습니당 ㅎㅅㅎ

2023-07-28 09:03 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +        final Specification<Post> searchResults = PostSpecification.searchBy(searchWord);
Specification<Post> 이라는 자료 타입이 컬렉션 타입이 아니라서 기존 전체 페이지 조회처럼

``` java
return searchResults
                .stream()
                .map(post -> GeneralPostInfoResponse.of(post, domain.getDomain()))
                .toList();
```
이런 스트림 문으로 response를 만드는 것이 불가능 했습니당근
그래서 이리내가 첨부해준 사진의 메서드를 써서 컬렉션 타입으로 만들수밖에 없었습니다람쥐

2023-07-28 09:27 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/post/ui/ReadPostController.java
> +                .body(new GeneralPostsResponse(posts));
프로젝트에서 dto 생성을 Service 계층에서 하고 있는데
`GeneralPostsResponse`도 `PostService`에서 해주는거 어떨까유?!

2023-07-29 10:12 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +                .toList();
여우랑 비슷한 로직이라 안일어날줄 알았는데 다른 메서드를 쓰고 있었습니다...
fetch join 사용하여 해결 하였습니다 !!! 찾아줘서 감사함돠 ~~!!!!

2023-07-29 10:13 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/ui/ReadPostController.java
> +                .body(new GeneralPostsResponse(posts));
우리 컨벤션에서 그렇게 정하긴 햇조.. 
수정하겠씁니다 ~!

2023-07-29 11:18 UTC, hectick approved these changes
검색 공부하시느라 고생하셧읍니다 🐸 🐸 🐸 🐸 🐸

2023-07-29 11:18 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/post/integration/PostSearchIntegrationTest.java
> +        assertThat(jsonPath.getInt("errorCode")).isEqualTo(ExceptionInformation.REQUEST_PARAMETER_NOT_EXIST.getCode());
400 bad request인지 확인하는 것은 어디로 가버렸죵

2023-07-29 11:18 UTC, BackFoxx approved these changes
N+1 멋지게 해결해 주셨네요~~~ 쿼리 이쁘게 날아가는 거 확인했습니다
어프루브 할게요 수고하셨어요~~!!!

2023-07-29 11:18 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +                .toList();
나이스~~~~~!!!!!!

2023-07-29 11:18 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceSearchPostsTest.java
> +        var 검색결과 = postService.searchPosts("이리내", emptyFindingCondition).posts();
var 편안~~~🥹

2023-07-29 12:23 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/integration/PostSearchIntegrationTest.java
> +        assertThat(jsonPath.getInt("errorCode")).isEqualTo(ExceptionInformation.REQUEST_PARAMETER_NOT_EXIST.getCode());
헉... 수정수정 하갯음ㅁ다

2023-07-31 04:58 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceSearchPostsTest.java
> +    private final PostRepository postRepository;
힘내세요~

2023-07-31 05:03 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceSearchPostsTest.java
> +                    softly.assertThat(검색결과.get(0).id()).isEqualTo(postId2);
`equals` 정도는 정의해도 괜찮을거 같은데욤?!

2023-07-31 05:09 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +        final Specification<Post> searchResults = PostSpecification.searchBy(searchWord);
`Specification`이라는 자료 타입이 검색을 위한 조건 같은 거군요

2023-07-31 05:10 UTC, This2sho approved these changes
변경사항 확인했습니다링~
고생했어유 🐍

2023-07-31 06:28 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceSearchPostsTest.java
> +                    softly.assertThat(검색결과.get(0).id()).isEqualTo(postId2);
이거 확인해 보니까 service에서 검색 결과로 return하는 거는 response 객체라서 
Post에 equals재정의 해도 못쓰더라고여???? 그래서 그냥 놔뒀습니다 ㅎㅎ

2023-07-31 06:30 UTC, merged