Fix/#110 게시글 수정 페이지 오류
woowacourse-teams/2023-edonymyeon pull request #157
Opened 2023-07-28 11:51 UTC by Choisehyeon

## 🔥 연관 이슈

- close: #110 

## 📝 작업 요약

게시글 수정 페이지에서 기존 이미지를 넘길 때 생기는 오류 수정

## 🔎 작업 상세 설명

기존 이미지를 서버와 협의 후 url로 받아오는 이미지는 수정페이지에서 올리는 이미지와 같이 전달되는 것이 아니라 나누어서 전달되도록 수정하였습니다. 

## 🌟 리뷰 요구 사항

> PostEditorViewmodel의 변수 부분은 issue를 따로 파서 추후 수정할 예정입니다. 글을 수정하는 부분을 자세히 봐주시면 좋을 것 같아요! 시간은 아마 multipart 부분을 다들 처음 접하는 것 같아서 공부하면 시간이 좀 걸릴 것 같습니다!

2023-07-30 10:27 UTC, sujin9 requested changes
어려운 오류였는데 너무 고생 많았어요오!!
옆에서 볼 때마다 오류 해결 중인 모습을 봤는데, 해결되어서 너무 기쁩니당 ㅎㅎ
당신은 지니어스,,, ⭐ 

하지만, 처음 게시글을 작성할 때,
여전히 사진 용량이 큰 경우에는 postId를 받아오지 못해 null이 되고
게시글 페이지에는 아무것도 보이지 않더라구용.
(아래는 로그캣 캡쳐 화면인데, PostEditorViewModel > savePost()에서 id 로그 찍으면 6이 뜨고,
postDetail 화면으로 이동 후에 400 에러가 떴어요!)

<img width="532" alt="스크린샷 2023-07-30 오후 7 03 24" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/8490058/51612049-9dbb-4e49-a996-a1dde2cf9874">

이 부분에 대해서는 같이 해결 방법을 논의해보면 좋을 것 같아요!! 😊

2023-07-30 10:27 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorViewModel.kt
>                  Log.d("id", (it as PostEditorResponse).id.toString())
로그가 남아있네용! 😆

2023-07-30 10:27 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorViewModel.kt
> +            else -> null
함수로 분리를 해주시니 함수의 역할을 이해하기도 더 쉽고 가독성이 좋아졌네요!! 😆

2023-07-30 10:27 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        finish()
작성/수정을 한 후 상세 페이지에서 뒤로가기 할 때 
다시 작성 페이지가 뜨지 않도록 수정된 점 너무 좋은 것 같아요!! 😄 

다만, 이제는 수정되기 전 상세 페이지로 돌아가더라구요! (수정하는 경우)
혹시 이 부분도 같이 수정해서 반영해주실 수 있을까요~?

(제 생각에는 수정 페이지로 이동할 때 `finish()`를 추가해서 하면 될 것 같은데,
혹시 더 좋은 다른 방법이 있을까요?)

2023-07-30 14:42 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        finish()
PostDetailActivity에서 수정 페이지로 넘어갈 때 finish()를 추가해서 수정했습니다. intent flag를 사용해서 수정하는 방법도 있을 것 같긴한데 그 부분에 대해서는 같이 얘기해봐도 좋을 것 같아요!!😄

2023-07-30 14:56 UTC, Choisehyeon commented
> 하지만, 처음 게시글을 작성할 때,
여전히 사진 용량이 큰 경우에는 postId를 받아오지 못해 null이 되고
게시글 페이지에는 아무것도 보이지 않더라구용.
(아래는 로그캣 캡쳐 화면인데, PostEditorViewModel > savePost()에서 id 로그 찍으면 6이 뜨고,
postDetail 화면으로 이동 후에 400 에러가 떴어요!)

아마 이부분은 로딩 전략이랑 연관된 것 같아보여요! 사진 용량이 큰 경우에 저장되는데 시간이 걸리는 것 같은데 저장이 되기 전에 postDetail 화면으로 이동하다보니까 아직 저장되지 않은 post를 불러와야해서 오류가 생긴 것 같아보여서 이 부분 로딩 전략이 아직 구현되지 않은 상태라 추후 구현이 된 다음에 얘기해봐도 좋을 것 같아요😄

2023-08-01 01:36 UTC, rhkrwngud445 approved these changes
고생했어요 로피!
상수화 관련해서 사소하게 남겼습니다!
바로 Approve 할게요!

2023-08-01 08:41 UTC, Choisehyeon commented
리뷰 부탁드려요!!

2023-08-01 13:05 UTC, sujin9 approved these changes
깔끔하네용 ㅎㅎ 고생했어요 로피 ~

2023-08-01 14:37 UTC, merged