Feat/#128 내가쓴글 페이지 뷰 구현
woowacourse-teams/2023-edonymyeon pull request #160
Opened 2023-07-29 09:29 UTC by Choisehyeon

## 🔥 연관 이슈

- close: #128 

## 📝 작업 요약

내가 쓴 글 페이지 뷰 구현하였습니다.

## 🔎 작업 상세 설명

내가 쓴 글 페이지에 들어갈 리사이클러뷰 구현 및 그 뷰에서 사용될 다이얼로그도 구현하였습니다.

## 🌟 리뷰 요구 사항

뷰만 구현했기 때문에 xml 파일 위주로 봐주시면 좋을 것 같습니다! 지금 api 연동이 되어있지 않은 상태라 애뮬레이터에서는 뷰를 볼 수가 없어서 xml 디자인탭을 통해서 디자인까지 확인해주시면 좋을 것 같아요!😃

2023-07-30 09:20 UTC, sujin9 requested changes
고생했어요, 로피! :)
깔끔하게 뷰를 잘 짜주셨네요 ~ 👍 

다만, 내가 쓴 글 페이지를 마이페이지 프래그먼트와 연결해서 확인을 한 번 해봤는데요,
다음 사진과 같이 앱바에 문구가 잘못 뜨고 있어서 한 번 확인해주시면 좋을 것 같아요!! :)
<img width="383" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/8490058/3b994fd4-bd32-4f4d-809d-7cd063a0187f">

그리고 다이얼로그도 실제로 띄웠을 때 number picker가 어떻게 보이는지 궁금한데 아쉽네용 ㅋㅋ~

2023-07-30 09:40 UTC, sujin9 requested changes

2023-07-30 09:40 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/adapter/MyPostDiffUtilCallback.kt
> +        return oldItem.id == newItem.id
이건 조금 사소할 수 있는데요..!
posteditor > adapter > ImageDiffUtilCallback 에서는
```kotlin
override fun areItemsTheSame(oldItem: String, newItem: String): Boolean {
    return oldItem == newItem
}
```
다음과 같이 구현하셨어서요!
혹시 다르게 구현하신 이유가 있으신지 궁금하고,
이 부분도 통일하면 좋지 않을까 조심스럽게 의견 남겨봅니당 😊

2023-07-30 09:40 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/dialog/ConsumptionDialog.kt
> +    private lateinit var binding: DialogInputConsumptionBinding
제가.. postdelete > delete dialog를 구현할 때 by lazy로 안하고 lateinit var로 구현하는 실수를 했었군요... 미안합니다... 앞으로는 컨벤션&통일성 잘 지키겠습니다.... (ㅠㅠ)

다음 코드도 다음과 같이 수정해주시면 좋을 것 같아요 ~
```suggestion
    private val binding: DialogInputConsumptionBinding by lazy {
        DialogInputConsumptionBinding.inflate(layoutInflater)
    }
```

2023-07-30 14:58 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/adapter/MyPostDiffUtilCallback.kt
> +        return oldItem.id == newItem.id
위 부분은 image를 따로 객체로 지정하지 않고 String으로만 표시를 해서 두개가 같음을 id로 비교할 수 없어서 위와 같이 구현했습니다! MyPost 같은 경우에는 id가 따로 있어서 id로 아이템이 같은지 비교할 수 있었습니다!!😀

2023-07-30 15:00 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/dialog/ConsumptionDialog.kt
> +    private lateinit var binding: DialogInputConsumptionBinding
아아 저도 컨벤션은 생각 못한 채 사용했네요😂  이 부분은 수정하도록 하겠습니당!!

2023-07-30 15:09 UTC, Choisehyeon commented
> 내가 쓴 글 페이지를 마이페이지 프래그먼트와 연결해서 확인을 한 번 해봤는데요,
다음 사진과 같이 앱바에 문구가 잘못 뜨고 있어서 한 번 확인해주시면 좋을 것 같아요!! :) 

이 부분은 수정하였습니다! numberpicker 부분은 구현을 빠르게 해서 어떻게 보이는 지 보여드릴께용😃 조금만 기다려주세요ㅎㅎ😉

2023-07-31 12:27 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/adapter/MyPostDiffUtilCallback.kt
> +        return oldItem.id == newItem.id
아하 string이었군요!! 제가 자세하게 살펴보질 못했었네용 에궁,,! 설명해주셔서 감사해요! :) 😆

2023-08-01 02:02 UTC, rhkrwngud445 requested changes
고생했어요 로피!
전체적으로 잘 구현해 주셨는데, 궁금한 점 위주로 리뷰를 남겼습니다.
확인 부탁해요~

2023-08-01 02:06 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/viewholder/MyPostViewHolder.kt
> +    fun bind(myPost: MyPostUiModel) {
이 부분은 아직 뷰만 구현한 상태라서 이후 기능을 넣을 때 추가할 생각이었습니다!

2023-08-01 02:07 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostActivity.kt
> +        TODO("Not yet implemented")
위 부분도 기능 구현시에 같이 처리할 예정입니다!!

2023-08-01 02:07 UTC, Choisehyeon commented on android/app/src/main/res/layout/activity_my_post.xml
> +                android:layout_gravity="center_vertical|center_horizontal"
오오 감사합니다👍

2023-08-01 03:45 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/dialog/ConsumptionDialog.kt
> +class ConsumptionDialog : DialogFragment() {
AlertDialog와 DialogFragment가 두 개가 구현할 때 큰 차이는 없지만 DialogFragment가 Fragment이기 때문에 Fragment 생명주기를 고려할 수 있어서 관리하기 편하고 또 DialogFragment 기존에 써본 경험이 있어서 DialogFragment를 선택하게 되었습니다. 또, PostDetail 부분에서 삭제 Dialog를 DialogFragment로 구현되어 있어서 같이 맞추면 좋을 것 같았습니다!

2023-08-01 08:42 UTC, Choisehyeon commented
리뷰 부탁드려요!!

2023-08-01 13:07 UTC, sujin9 approved these changes
의견 모두 잘 반영해주셨네요! 👍 
수고했어요 로피 ~~ 😄

2023-08-02 05:03 UTC, rhkrwngud445 approved these changes
피드백 반영 빠르게 잘해주셨네요!
Approve할게요 고생했습니다!

2023-08-02 05:51 UTC, merged