Feat/#114 이벤트 더블클릭 방지
woowacourse-teams/2023-edonymyeon pull request #162
Opened 2023-07-30 08:33 UTC by sujin9

## 🔥 연관 이슈

- close: #114 

## 📝 작업 요약

추천/비추천 기능을 수행하면 해당 이벤트에 대한 서버 요청의 응답이 오기 전까지 기능이 수행될 수 없도록 하여 더블클릭을 방지합니다.

## 🔎 작업 상세 설명

view model에는 서버로부터 응답을 받았는지 여부를 저장하는 LiveData (isRecommendationRequestDone) 변수가 있습니다.
체크박스를 클릭하면(추천, 비추천 기능을 실행하면) 위 변수의 값은 false가 되고,
서버 응답이 끝나면 다시 true가 됩니다.

이 값은 Activity에서 추천/비추천 checkbox의 isEnabled 값으로 observe 하고 있어, 
변수의 값이 false인 동안에는 체크박스가 비활성화됩니다.

## 🌟 리뷰 요구 사항

> 로직 구현 뿐만 아니라, 이 방법이 제대로 작동하는 지를 검증하는 데에 고민을 많이 했어요. 테스트 코드로 이를 증명하려고 했는데, 놓치고 있는 모순점이 있지 않은지, 근거가 부족한 점이 있는지를 중점으로 봐주시면 좋을 것 같아요. 코드의 이해를 위해 테스트 코드에 주석을 상세히 적었는데, 이해가 되지 않는 부분이 있으시면 말씀해주세요! 리뷰 자체에는 큰 시간이 소요될 것 같진 않지만, 시간을 두고 천천히 고민해주시면 좋을 것 같습니다 ~

2023-07-31 03:06 UTC, Choisehyeon requested changes
하티 로직 구현과 테스트까지 하느라 수고 많았어요👍👍
하티가 의도한 부분대로 구현이 잘 된 것 같아요! 
테스트 코드 주석을 보니 태스트 내용이 더 쉽게 이해된 것 같아요😃

이 추천/비추천 부분은 아니긴 하지만, 수정 페이지에서 내용을 작성하지 않은 채 저장을하면 
<img width="195" alt="스크린샷 2023-07-31 오후 12 03 39" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/50761690/8c5f1e43-c604-423c-be6d-09b34e048880">
이렇게 게시물 페이지에 null로 작성이 되더라구요! 이 부분도 나중에 수정해주시면 좋을 것 같아요! 😄

2023-07-31 03:06 UTC, Choisehyeon commented on android/app/src/test/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModelTest.kt
> +}
하티가 어떤 부분을 의도하고 테스트했는지 주석을 통해 바로 알 수 있었던 것 같아요! repositoryImpl에서 delay해주고 테스트 해봤더니 추천/비추천 서버 통신이 완료되기 전까지 추천/비추천이 비활성화가 되네요!👍 
여기서 또 어떤 오류가 발생할지는 아직 생각나는게 없는 것 같아여😂 아마 QA 테스트를 통해 여러 폰으로 검증을 해보고 나면 또 예상하지 못한 오류를 찾을 수 있을 것 같아요 ㅎㅎ

2023-08-01 02:14 UTC, rhkrwngud445 approved these changes
고생했어요 하티!
제 시야에서는 리뷰드릴게 안 보이네요! 바로 Approve할게요!

2023-08-01 02:14 UTC, rhkrwngud445 commented on android/app/src/test/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModelTest.kt
> +    )
Fake 객체👍

2023-08-01 02:15 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModel.kt
>      }
리팩토링.. 리팩토링..

2023-08-01 04:51 UTC, sujin9 commented on android/app/src/test/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModelTest.kt
> +    @OptIn(ExperimentalCoroutinesApi::class)
저도 이번에 처음 코루틴 테스트를 했는데요!
코루틴을 테스트하기 위해 runTest를 이용했고, 이 테스트에서는 스케쥴링 없이 즉시 실행되도록 하기 위해 UnconfinedTestDispatcher를 이용했어요. (Dispatcher.main은 android main looper을 사용하기 때문에 테스트로 진행할 수 없어요!)

`@OptIn(ExperimentalCoroutinesApi::class)` 
이는 코루틴 API가 아직 실험 단계이므로 앞으로 업데이트될 가능성이 있음을 표시해주는 역할입니다 :)

2023-08-01 08:36 UTC, sujin9 commented
> 이 부분이 함수 안에 내용이 길어지다보니까 가독성이 떨어진다는 생각이 들었어요!! 이 부분을 좀 더 가독성 있게 하는 방법이 없을지 같이 고민해보는게 좋을 것 같아요😄 밑에 updateDownRecommendationUi 함수 부분도 같이 고민해보면 좋을 것 같습니다!
> 리팩토링.. 리팩토링..
리팩토링했습니다! 다시 확인 부탁드려요 :)
이해를 위해 우선 주석을 적었는데, 추후 머지할 때는 이 주석들을 제거해야 할까요 ~??

> 수정 페이지에서 내용을 작성하지 않은 채 저장을하면
> 이렇게 게시물 페이지에 null로 작성이 되더라구요! 이 부분도 나중에 수정해주시면 좋을 것 같아요! 😄
이 부분은 게시물을 보낼 때 null이라는 string값으로 보내지는 문제여서 @Choisehyeon 가 수정해준다고 하네요 ! 😆

2023-08-01 08:49 UTC, rhkrwngud445 approved these changes
통일성 관련해서 간단하게 리뷰 하나 남겼습니다! 또한 Approve 할게요~

2023-08-01 09:56 UTC, Choisehyeon approved these changes
함수 부분 리팩토링을 해줘서 이해하기가 수월해진 것 같아요!!
approve 하겠습니다😄

2023-08-01 10:35 UTC, merged