Feat/#159 로그인페이지 서버 연결
woowacourse-teams/2023-edonymyeon pull request #163
Opened 2023-07-30 15:47 UTC by Choisehyeon

## 🔥 연관 이슈

- close: #159 

## 📝 작업 요약

로그인 페이지를 서버와 연동했습니다!

## 🔎 작업 상세 설명

로그인 시 이메일과 패스워드를 입력하지 않으면 스낵바를 통해 필수 입력항목입니다를 알려주도록 하였습니다.
이메일과 패스워드를 입력한 후 로그인 버튼을 눌러 서버에 연결시 성공하면, 서버에서 쿠키에 담아서 전달한 토큰을 sharedpreference를 사용해서 저장할 수 있도록 구현했습니다.
로그인 실패 시에는 실패한 오류를 서버로부터 받아와서 스낵바를 통해 오류 메시지를 보이도록 구현했습니다!

로그인 성공하고 다른 페이지로 넘어가는 부분은 아직 구현하지 않았고 우선 finish 되도록 하였습니다. 회원가입 버튼을 클릭해서 페이지 넘어가는 부분도 아직 연결하지 않았습니다!

## 🌟 리뷰 요구 사항

sharedpreference에 토큰을 저장하고 불러올 수 있도록 localDataSource를 구현했습니다. 토큰을 쿠키에서 가져와서 저장하는 부분에 대해서 리뷰 남겨주시면 좋을 것 같습니다! 또 실패한 오류를 받을 때 result.code와 result.message에서 받는 것이 아니라 result.errorBody에서 받아와서 구현하였는데 result.message를 가져오면 빈 값이 들어와서 result.errorBody에서 오류 메세지를 가져와 처리하도록 구현했습니다! 그 부분에 대해서도 리뷰 부탁드립니다😀 

또 LoginViewModel에서 서버와의 연결과 에러 메시지에 관한 부분을 livedata로 관리하도록 하였는데 그 부분도 리뷰 부탁드립니다! 
리뷰는 늦어도 화요일까지는 해주시면 좋을 것 같아요💪💪

2023-08-01 02:35 UTC, sujin9 requested changes
로그인 구현하느라 고생 많았어요, 로피 !! 😆 
몇 가지 의견과 궁금한 점도 코멘트로 남겨놨으니 확인 부탁해요 ~~ :)

2023-08-01 02:35 UTC, sujin9 commented on android/app/src/main/res/layout/activity_login.xml
> +                android:inputType="textPassword"
password를 입력하는 데 * 표시가 안보이네요..!

<img width="421" alt="스크린샷 2023-08-01 오전 11 22 46" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/8490058/e43f6961-ab07-4a52-980c-ae72515b3536">

2023-08-01 02:35 UTC, sujin9 commented on android/app/src/main/res/layout/activity_login.xml
> +                android:fontFamily="@font/dohyeon"
```suggestion

```

이미 기본 폰트 설정이 되어있어서 이 코드는 생략해주셔도 됩니다! (비밀번호도 동일해요~)

2023-08-01 02:35 UTC, sujin9 commented on android/app/src/main/res/layout/activity_login.xml
> +
빈 라인 하나 삭제해주세용 ~

2023-08-01 02:35 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/login/LoginViewModel.kt
> +    private fun setLoginEnable() {
이메일, 비밀번호 중 하나를 입력하지 않았을 때
입력한 값이 사라져버리는건 조금 불편하게 느껴졌어요!
값을 유지하면서 snackbar를 보여주는 건 어떠신가요~?
또는, 둘 중 하나가 입력되지 않으면 로그인 버튼이 비활성화 되는 것도 방법일 것 같아요!
혹시 로피와 코비는 어떻게 생각하시나요?  😊

2023-08-01 02:35 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/login/LoginActivity.kt
> +    }
사소한 부분이지만, `navigateToMain`과 `navigateToJoin` 함수가 함께 있을 때 가독성이 더 좋을 것 같아요! :)

2023-08-01 02:35 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/login/LoginActivity.kt
> +        }
observe 하는 부분도 함수로 분리할 수 있을 것 같은데요 ~? 😆

2023-08-01 02:35 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/data/datasource/auth/AuthLocalDataSource.kt
> +                AuthLocalDataSource(context)
이 부분이 어떤 코드 내용인지, 왜 `synchronized`를 사용하신 건지 혹시 알려주실 수 있나요 ~?

2023-08-01 02:35 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/data/datasource/auth/AuthLocalDataSource.kt
> +    private val sharedPreference: SharedPreferences =
보안이 적용된 SharedPreferences인 [EncryptedSharedPreferences](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences) 도 있어요!
로그인 토큰에 보안을 적용해야 할지 논의해보고, 필요하다면 적용해보아도 좋을 것 같아요 :)

2023-08-01 03:45 UTC, Choisehyeon commented on android/app/src/main/res/layout/activity_login.xml
> +                android:inputType="textPassword"
이 부분은 오류를 다시 한 번 찾아보도록 하겠습니다!!

2023-08-01 03:46 UTC, Choisehyeon commented on android/app/src/main/res/layout/activity_login.xml
> +                android:fontFamily="@font/dohyeon"
넵! 감사합니다

2023-08-01 05:02 UTC, rhkrwngud445 requested changes
고생했어요 로피!
리뷰 조금 남겨 놓았는데, 확인 부탁드릴게요!!

2023-08-01 06:39 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/login/LoginActivity.kt
> +        }
ㅋㅋㅋㅋ HomeFragment에는 함수명이 `initObserve` 던데 이 부분도 통일성을 논의해보죠 ~? 😸

2023-08-02 09:06 UTC, Choisehyeon commented
죄송합니다😂 제가 rebase merge를 하고 그래도 push를 해버려서 commit이 55개입니다ㅜㅜㅜ 피드백은 다 반영해서 올렸어요!!
로그인 부분만 봐주시면 될 것 같아요😄

2023-08-03 08:16 UTC, sujin9 approved these changes
아주 좋습니다 ㅎㅎ 어푸루부 할게욤!

2023-08-03 08:25 UTC, merged