Feat/#130 구매확정, 절약확정 기능 구현 및 확정 취소 기능 구현
woowacourse-teams/2023-edonymyeon pull request #164
Opened 2023-07-31 05:15 UTC by hectick

## 🔥 연관 이슈

- close: #130 
- close: #131 

## 📝 작업 요약

구매확정, 절약확정 기능 구현 및 확정 취소 기능을 구현하였습니다.

## 🔎 작업 상세 설명

사용자는 자신이 작성한 게시글에 대해 구매/절약을 확정할 수 있습니다.
- 글쓴이가 아니면 예외가 발생합니다.
- 존재하지 않는 게시글이라면 예외가 발생합니다.
- 이미 구매/절약 확정을 했다면 예외가 발생합니다.
- 0원 미만, 1억원 초과의 가격으로 확정하면 예외가 발생합니다. (Post 도메인에서의 가격 검증과 동일하게 진행하였습니다.)
- 확정 년도가 0년 미만이면 예외가 발생합니다. (임의로 지정하였으니 의견 부탁드립니다.)
- 확정 달이 1월~12월이 아니면 예외가 발생합니다.

사용자는 자신이 구매/절약 확정한 내역을 삭제할 수 있습니다.
- 글쓴이가 아니면 예외가 발생합니다.
- 존재하지 않는 게시글이라면 예외가 발생합니다.
- 구매/절약 확정 내역이 없다면 예외가 발생합니다.

게시글이 삭제될 때, 구매/절약 확정 내역이 존재한다면 해당 확정 내역도 같이 삭제되도록 하였습니다.
- 처음에는 PostService에서 ConsumptionRepository를 통해 삭제하는 것을 고려하였으나, Post <-> Consumption 패키지의 양방향 관계가 생길 것을 고려해서 Cascade 옵션을 한줄을 추가하는 것을 통해 삭제하도록 방향을 바꾸었습니다.
<img width="1051" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/62106852/55d44f31-7c11-43aa-a772-27094437bbc5">

## 🌟 리뷰 요구 사항

> 현재 존재하는 패키지의 의존 관계입니다. (Thumbs와 Post는 추후에 개선이 필요해 보입니다)
<img width="982" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/62106852/eca43965-3ca7-4322-94da-c94a443c1c1a">

> Images를 제외한 모든 패키지가 Member에 의존하고 있기 때문에 Member가 Consumption 패키지를 의존하지 않는 방향으로 ConsumptionService 리팩터링을 진행하였는데, 괜찮은지 확인 부탁드립니다.
현재 Member가 소비확정서비스(ConsumptionConfirmService) 인터페이스를 가지고 있고, 그 구현체가 Consumption 패키지에 있어서, 의존 방향은 Consumption ---> Member 패키지입니다. 추후에 6개월간 소비내역을 조회할 때는 ConsumptionController를 통해 요청이 들어오도록 할 것이므로, Consumption 패키지에 별도의 서비스를 만들 계획입니다.

> 또, 코드상의 중복을 줄이기 위해 MemberService에서 구매를 확정하든, 절약을 확정하든 ConsumptionConfirmService의 동일한 메서드를 호출하도록 코드를 짰습니다. 다만, 이 과정에서 dto의 변환(PurchaseConfirmRequest -> YearMonthDto, SavingConfirmRequesst -> YearMonthDto)이 한번 발생하게 되는데요, 사실상 SavingConfirmRequest와 YearMonthDto의 형태가 똑같아서 번거롭다 생각될 수도 있을 것 같습니다. 저는 과정이 조금 번거로울 수 있더라도 dto의 네이밍으로 코드를 이해하기엔 더 쉬울 것이라 생각해서 남겨두긴 했는데, 이에 대해 어떻게 생각하는지, 더 좋은 생각이 있는지 의견 부탁드립니다!!

2023-07-31 05:55 UTC, BackFoxx requested changes
성능 관련해서 개선할 점을 코멘트로 남겨두었어요!
고생 많으셨고 천천히 반영해주세요 ~~

2023-07-31 05:55 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionConfirmServiceImpl.java
> +        post.validateWriter(member);
post.validateWriter(member)가 어떻게 동작하는 지 보니까

post의 member랑 파라미터로 넘어온 member를 equals() 메소드로 비교하네요.

근데 member의 equals()는 식별자인 id만 비교하도록 구현이 돼있어요.


그렇다면 여기서 굳이 findById로 Member 객체 전체를 불러와 사용하는 것보다

post.validateWriter(memberIdDto.id()) 이렇게 식별자만 넘겨서 비교하게 하는 게

불필요한 MEMBER SELECT 비용을 절감할 수 있지 않을까요?

2023-07-31 05:55 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/consumption/domain/Consumption.java
> +    }
validate 깔끔해서 너무 좋아요~!!!

2023-07-31 05:55 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionConfirmServiceImpl.java
> +        if (consumptionRepository.findByPostId(postId).isPresent()) {
postId로 데이터가 존재하는 지 확인하는 용도라면

exists 메소드를 사용해보는 건 어떨까요!

[참고자료](https://recordsoflife.tistory.com/1213)

데이터 존재여부를 확인하기 위해 findByXxx를 사용하면 불필요한 데이터 매핑 작업이 추가되고

별도로 limit 1같은 걸 지정하지 않는 이상

데이터베이스 안의 테이블을 풀스캔하기 때문에 성능상 좋지 않다고 하더라구요

2023-07-31 06:01 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionConfirmServiceImpl.java
> +        if (consumptionRepository.findByPostId(postId).isPresent()) {
오 이런게 있었다니 너무 좋은데요 바로 반영!!

2023-07-31 06:02 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionConfirmServiceImpl.java
> +        post.validateWriter(member);
좋아유!! 여우가 쿼리 성능에 대해서 잘 아는 것 같아 든든하네요

2023-07-31 07:16 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionConfirmServiceImpl.java
> +        post.validateWriter(member);
POST 테이블에 연결된 MEMBER_ID 정보가 외래키 제약이 걸려있기 때문에
존재하지 않는 회원이라면 POST에서 애초에 들고있지 않을 거라는 점을 함께 고려해보셨음 좋겠어요!

2023-07-31 07:26 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionConfirmServiceImpl.java
> +        post.validateWriter(member);
Post에서 들어온 회원은 id가 3이고, 들어온 아이디가 5인데, 5인 회원이 존재하지 않을 수도 있잖아용!

2023-07-31 07:32 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionConfirmServiceImpl.java
> +        post.validateWriter(member);
memberId의 유효 여부는 서비스에 넘어오기 전에 컨트롤러 레이어에서 이미 검증하는걸요? 🤨

2023-07-31 07:44 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionConfirmServiceImpl.java
> +        post.validateWriter(member);
최대한 검증은 빡세게 하는게 안전하다 생각했었는데,
ArgumentResolver에서 이미 검증을 하는 중복을 고려하면 뺄수도 있겠네요! 생각해보니 동일한 검증로직이 여기저기 널려있으면 유지보수하기 불편할수도 있겠어요
여우 말대로 빼고나니 서비스의 필드에서 memberRepository가 사라져 서비스가 더 깔끔해지는 것 같습니다!

2023-07-31 07:45 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionConfirmServiceImpl.java
> +        post.validateWriter(member);
예아 감사합니다~~~~~!!! 👍🏻🤝🏻

2023-07-31 07:45 UTC, BackFoxx approved these changes
빠른 리뷰반영 감사합니다~~ 어프루브!

2023-07-31 10:23 UTC, This2sho reviewed
고생하셨습니다 이리내🍤
패키지 방향성까지 꼼꼼히 생각해서 하셨네유!
코드 확인하면서 몇가지 커맨트 남겼스무니다

`SavingConfirmRequest`와 `YearMonthDto`의 경우 분리하니 이해하기 더 편했습니다리!

추가로, 확정 년도와 확정 달의 유효성 검사로 현재 년 월을 비교해서 넘어가면 예외처리 해주는건 어떨까유?!

2023-07-31 10:23 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
> +        if (!isSameMember(other)) {
이 메소드를 재사용하기 위해 `Member`에 새로운 생성자를 추가하셨네욤..

2023-07-31 10:42 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/domain/Consumption.java
> +    private static final int MIN_MONTH = 0;
아리가또

2023-07-31 10:43 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
> +    CONSUMPTION_PRICE_ILLEGAL_SIZE(6543, "가격은 0원 이상 100억 이하여야 합니다."),
꼼꼼하시네유 호이~

2023-07-31 10:43 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/consumption/domain/ConsumptionTest.java
> +    void 년도가_0년_이하면_예외가_발생한다() {
스미마셍...

2023-07-31 10:46 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
> +    CONSUMPTION_PRICE_ILLEGAL_SIZE(6543, "가격은 0원 이상 100억 이하여야 합니다."),
앗 근데 PR 코멘트에 1억이라고 잘못쓴 거엿읍니다.
도메인 숫자 세보니 100억이 맞아유

2023-07-31 10:47 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/consumption/domain/ConsumptionTest.java
> +    @ValueSource(ints = {-1, 0, 13})
이거 테스트 코드 수정햇으니 확인해주시죠!!

2023-07-31 10:47 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/consumption/domain/ConsumptionTest.java
> +                .hasMessage(ExceptionInformation.CONSUMPTION_YEAR_ILLEGAL.getMessage());
앗. 들킴

2023-07-31 10:48 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/member/integration/steps/MemberConsumptionSteps.java
> +public class MemberConsumptionSteps {
😎

2023-07-31 11:54 UTC, This2sho approved these changes
변경된거 확인했습니다
고생하셨어유 👍

2023-08-01 01:41 UTC, jyeost commented
> * 이미 구매/절약 확정을 했다면 예외가 발생합니다.

이 부분도 동시성 문제 고민해보면 좋을 것 같아영 ㅎㅅㅎ

> ## 🌟 리뷰 요구 사항
> > 현재 존재하는 패키지의 의존 관계입니다. (Thumbs와 Post는 추후에 개선이 필요해 보입니다, 놓친 부분이 있을 수 있습니다)

의존성... 놓치고 있었내여 ㅠㅠ 
thumbs 추후에 개선 하도록 하께여 ~_~

> > 또, 코드상의 중복을 줄이기 위해 MemberService에서 구매를 확정하든, 절약을 확정하든 ConsumptionConfirmService의 동일한 메서드를 호출하도록 코드를 짰습니다. 다만, 이 과정에서 dto의 변환(PurchaseConfirmRequest -> YearMonthDto, SavingConfirmRequesst -> YearMonthDto)이 한번 발생하게 되는데요, 사실상 SavingConfirmRequest와 YearMonthDto의 형태가 똑같아서 번거롭다 생각될 수도 있을 것 같습니다. 저는 과정이 조금 번거로울 수 있더라도 dto의 네이밍으로 코드를 이해하기엔 더 쉬울 것이라 생각해서 남겨두긴 했는데, 이에 대해 어떻게 생각하는지, 더 좋은 생각이 있는지 의견 부탁드립니다!!

클래스명으로 좀 더 명확하게 알 수 있어서 저는 좋았어요 !!

2023-08-01 01:49 UTC, jyeost approved these changes
구현 잘 해주셨습니다 ㅎㅎ
리뷰가 늦어서 죄송합니다..... ㅜㅜ
건의 사항을 적어놨는데 리코멘 달아주십셔 ~

2023-08-01 01:49 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/consumption/domain/Consumption.java
> +        ConsumptionType consumptionType = ConsumptionType.classifyConsumptionType(purchasePrice);
다른 api로 요청을 받고 같은 메서드로 처리를 하는데 (confirm 메서드)
그것을 나누는 기준이 금액이 0이라는 기준인 것이 저는 부자연 스럽다고 생각해요
사용자가 구매 확정을 입력하고 금액을 0원이라고 입력했을때 뷰에서는 아무런 알림도 없이 절약확정이 되어버리는 것이 이상한것 같아요

차라리 memberService에서 confirm메서드를 사용하는 시점에서 enum을 입력 받아서 오는 것이 어떨까요

2023-08-01 01:49 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/consumption/domain/Consumption.java
> +    private static final int MIN_YEAR = 0;
min_year 2000부터 인 것이 어떤가염??????????

2023-08-01 01:49 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
> +        MemberConsumptionSteps.구매_확정_요청을_보낸다(작성자, 게시글_id, 구매_확정_요청);
꼼꼼한 테스트 조화용 ><

2023-08-01 01:49 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/member/integration/MemberConsumptionIntegrationTest.java
> +
테스트 케이스가 정말 촘촘하군여 ...!!!!
굳굳굳굳

2023-08-01 02:12 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/domain/Consumption.java
> +        ConsumptionType consumptionType = ConsumptionType.classifyConsumptionType(purchasePrice);
0원이라도 값이 들어오면 무조건 구매확정이고, 값이 없을 때 절약확정을 하고 있습니다! (절약확정하면 따로 입력으로 들어오는 값이 없으니까요!)

enum을 받아서 오는 것도 고려하긴 했는데요, dto에 사용하는 enum을 따로 분리하는 것이 좋을까요?

2023-08-01 02:13 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/domain/Consumption.java
> +    private static final int MIN_YEAR = 0;
좋아용

2023-08-01 02:16 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/consumption/domain/Consumption.java
> +        ConsumptionType consumptionType = ConsumptionType.classifyConsumptionType(purchasePrice);
> 0원이라도 값이 들어오면 무조건 구매확정이고, 값이 없을 때 절약확정을 하고 있습니다! (절약확정하면 따로 입력으로 들어오는 값이 없으니까요!)

이런 구현로직으로 테스트에서도 구현이 명확하지 않다고 느껴졌습니다 .... (저는용ㅎㅎ)
지금은 도메인에서 사용하는 enum을 서비스에서 dto에 담아주어도 괜찮을 것 같다고 생각합니다  ㅎㅅㅎ

2023-08-01 02:37 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/domain/Consumption.java
> +        ConsumptionType consumptionType = ConsumptionType.classifyConsumptionType(purchasePrice);
enum을 전해주려다가, 새로운 enum의 이름을 정하는것도 난관이고 해서,
ConsumptionConfrim서비스에서 메서드 분리를 통해 명확히 만들어보았습니다!

2023-08-01 03:49 UTC, merged