Feat/#135 그래프
woowacourse-teams/2023-edonymyeon pull request #171
Opened 2023-07-31 13:33 UTC by sujin9

## 🔥 연관 이슈

- close: #135 

## 📝 작업 요약

소비, 절약 금액이 보이는 라인 그래프를 구현하였습니다.

## 🔎 작업 상세 설명

소비, 절약 금액이 함께 보이는 라인 그래프를 구현하였습니다.
라이브러리는 MPAndroidChart 를 채택하였는데요,
우선 사용률(점유율)도 가장 높고 그만큼 레퍼런스가 가장 많다는 장점이 있었어요.
또한, 타 라이브러리에 비해 비교적 최신까지 커밋 내역이 있는 등 유지 보수가 되고 있는 것 같구요!

현재는 API를 연동하기 전이어서, 우선 그래프 뷰를 구현하였고
값은 viewmodel에서 더미값을 반환해주고 있습니다.

<img width="354" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/8490058/74a288a0-dbb9-4a2c-9390-2fcb5376d3be">

## 🌟 리뷰 요구 사항

> 차트 관련하여 코드가 많이 길어진 것 같아요. 다른 클래스를 만들어서 context 혹은 binding, 그리고 resource를 넘겨서라도 분리를 하는 게 좋을지가 고민입니다. 그 외에는 디자인 적으로 의견을 자유롭게 부탁드려요! (e.g. 글씨가 작다, 애니메이션이 느리다 등등)

2023-08-01 02:30 UTC, rhkrwngud445 requested changes
어려운 작업이었을텐데 고생 많았어요!
그래프 관련 코드가 익숙하지 않고 어렵다 보니 부연 적인 설명 주석 or 상수화를 해보면 좋을 것 같다는 생각이 드는데, 로피의 의견을 들어보고 반영해 보아도 좋을 것 같습니다!

2023-08-01 02:30 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
> +                return (value / 10000).toInt().toString()
상수화? 전체적으로 익숙하지 않은 값들이 많은데, 이 경우 주석이 더 효율적일 수도 있겠네요 한 번 고민해봐도 좋을 것 같습니다!

2023-08-01 02:30 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
> +    private fun setConsumptionChart() {
개인적인 생각, 희망) ChartManager(가명)을 생성하여, setChart(binding.chart)를 넘기면 촤라락하고 세팅을 해주는 클래스를 한 번 만들어 보는 것도 괜찮을 것 같은데, 방도가 떠오르면 같이 고민해 봐도 좋습니다!

2023-08-01 07:53 UTC, Choisehyeon requested changes
하티! 그래프 부분 구현하느라 수고많았어요👍
복잡한 부분이 많아서 구현이 힘들었을 것 같네요😂

하티랑 제가 consumption 부분이 겹쳐서 네이밍이 겹치는 부분이 많은 것 같아요! 
이 부분은 같이 얘기해보면 좋을 것 같습니다😄

2023-08-01 07:53 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/mapper/ConsumptionMapper.kt
> +}
Consumption 부분에 관해서 변수명을 같이 얘기 해봐야할 것 같아여!! MyPost안에도 consumption 부분이 들어가서 변수명이 겹치는 부분이 많은 것 같아요😂

2023-08-01 07:53 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
이 부분은 repository 연결하고나면 ViewModelFactory 사용하는거겠죠?? 😄

2023-08-01 07:53 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
> +                return (value / 10000).toInt().toString()
상수화하기에는 너무 많아보여서 주석이 좋은 것 같아요! 주석이 있으면 왜 이 상수를 사용했는지 알기 쉬울 것 같아요!😄

2023-08-01 07:53 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
> +    private fun setConsumptionChart() {
저도 클래스를 따로 분리해서 사용하는게 좋아보여요! 나중에 관리하기에도 편할 것 같습니다👍

2023-08-01 08:28 UTC, sujin9 commented on android/domain/src/main/java/com/domain/edonymyeon/model/Consumptions.kt
> +}
startMonth, endMonth를 갖고 해당 로직을 갖는 도메인을 추가적으로 만들게요! :)

2023-08-01 08:29 UTC, sujin9 commented on android/domain/src/main/java/com/domain/edonymyeon/model/Consumption.kt
> +data class Consumption(
@Choisehyeon 여기는 ConsumptionAmount로 네이밍을 수정할게요!

2023-08-01 08:40 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
네 맞아요 ~~ 😊

2023-08-01 13:04 UTC, sujin9 commented
차트 관련 클래스 만들고, 도메인/ui 모델들 클래스명도 수정했습니다 ~ 리뷰 부탁드려용 !

2023-08-01 14:22 UTC, Choisehyeon approved these changes
하티 피드백이 잘 반영된 것 같아요!!😄
도메인이 잘 분리되어서 다른 곳에서도 사용하기 편할 것 같아요!
그래프 그리는 부분도 주석 처리 되어 있어서 이해하기 쉬웠어요👍

이만 approve 하겠습니다!!

2023-08-01 14:22 UTC, Choisehyeon commented on android/domain/src/main/java/com/domain/edonymyeon/model/MonthRange.kt
> +}
도메인 분리👍👍

2023-08-02 05:12 UTC, rhkrwngud445 approved these changes
반영하느라 고생했어요 하티!
작은 코멘트 남겼는데, 확인해 주시면 감사하겠습니다
한개 뿐이라 Approve 해놓을게요!

2023-08-02 05:12 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/chart/LineChartManager.kt
> +    }
TextView를 밖에서(activity) 바꿔보는 건 어떨까요?! ex lambda?

2023-08-02 07:33 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/chart/LineChartManager.kt
> +    }
이 부분 같은 경우는, marker view에 쓰이는 textview가 아예 다른 레이아웃에 존재하고 있어서 어떻게 적용하면 좋을지가 고민되네요..
callback 형태로 진행하거나, 새로운 레이아웃 파일의 binding을 넘겨봐도 해결이 잘 안됩니다 ㅠㅠ
논의한 대로, 우선은 이대로 진행하고, 추후의 리팩토링의 영역으로 가져가는 게 좋을 것 같네요 !

2023-08-03 01:38 UTC, merged