Feat/#132 회원가입 페이지
woowacourse-teams/2023-edonymyeon pull request #172
Opened 2023-07-31 17:07 UTC by rhkrwngud445

## 🔥 연관 이슈

- close: #132 

## 📝 작업 요약
회원가입 기능 구현

## 🔎 작업 상세 설명
서버연결 및 도메인 로직 처리 추가

## 🌟 리뷰 요구 사항
전체적으로 로직이 있을 곳에 있는지? 좀 더 예쁜 코드를 짤 수 있는 방향이 있다면 편하게 말씀 주세요!

2023-08-02 03:28 UTC, Choisehyeon approved these changes
코비 회원가입 부분 구현하느라 수고 많았어요!!!👍
코드의 통일성에 대해서만 얘기해보면 될 것 같아요😄

2023-08-02 03:28 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/data/repository/AuthRepositoryImpl.kt
> +        }
회원 가입에 실패한 경우에 대한 에러 처리를 errorBody로 처리할 수 있는데 그 부분을 같이 상의해보면 좋을 것 같아요!!

2023-08-02 03:28 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/data/service/AuthService.kt
> +    suspend fun signUp(@Body userRegistrationRequestBody: UserRegistrationRequestBody): Response<Unit>
변수명을 통일하면 좋을 것 같아요! UserRegistrationRequst로 할 것인지? UserRegisterationRequestBody로 할 것인지?

2023-08-02 03:28 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/signup/SignUpActivity.kt
> +    }
by ViewModels로 통일하는건가요?? 😄

```
    private val viewModel: PostViewModel by lazy {
        PostViewModelFactory(PostRepositoryImpl(PostRemoteDataSource())).create(PostViewModel::class.java)
    }
```
다른 액티비티는 이렇게 적혀있어서 통일하는게 좋을 것 같아요!! by viewModels로 하는건지 by lazy로 하는건지!!

2023-08-02 04:31 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/signup/SignUpActivity.kt
> +    }
by viewModels로 하기로 했었어요 제가 수정할게요~!

2023-08-03 07:22 UTC, sujin9 requested changes
회원가입 페이지 구현하느라 수고 많았어요 코비!

다만 추가적으로 얘기해보고 싶은 부분이 몇 가지 있는데요,,!
1. 이메일이나 닉네임이 안 되는 경우에,
- 중복이 되어서 안 되는 건지
- 형식이 안맞아서 안 되는 건지
가 구분되지 않아서 헷갈리는 경우는 없을까요?

2. 비밀번호(비밀번호 확인) 입력받을 때, *** 로 표시되게 할 필요는 없을까요?
*** 표시가 나을지, 기존대로 비밀번호가 그대로 보이는 게 좋을지 고민해보아요!

2023-08-03 07:22 UTC, sujin9 commented on android/app/src/main/AndroidManifest.xml
> +        <activity android:name="com.app.edonymyeon.presentation.ui.signup.SignUpActivity" />
`android:exported` 속성을 정의하지 않으면 오류가 발생하는 것 같습니다!

[관련 링크](https://mynamewoon.tistory.com/32)

2023-08-03 07:22 UTC, sujin9 commented on android/app/src/main/AndroidManifest.xml
> +        <activity android:name="com.app.edonymyeon.presentation.ui.signup.SignUpActivity" />
더불어, 12번째 줄 `<uses-permission android:name="android.permission.INTERNET" />` 코드가 중복되어 오류가 발생해요! 아마도 머지 과정에서 합쳐진게 아닐까 싶은데, 혹시 코드를 지워주실 수 있을까요~? :)

2023-08-03 07:22 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/data/service/AuthService.kt
> +    suspend fun signUp(@Body userRegistrationRequestBody: UserRegistrationRequestBody): Response<Unit>
저도 로피의 의견처럼 이 부분 네이밍을 통일하면 좋을 것 같아요! :)

2023-08-03 07:22 UTC, sujin9 commented on android/domain/src/test/kotlin/com/domain/edonymyeon/model/PasswordTest.kt
> +internal class PasswordTest {
디테일한 테스트 짱이에용 👍

2023-08-03 07:22 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/signup/SignUpViewModel.kt
> +class SignUpViewModel(private val authRepository: AuthRepository) : ViewModel() {
로직이나 오류 처리 부분이 많아서 뷰모델 테스트도 추가해보면 좋을 것 같아요!

2023-08-03 08:23 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/data/service/AuthService.kt
> +    suspend fun signUp(@Body userRegistrationRequestBody: UserRegistrationRequestBody): Response<Unit>
짧은 Request로 할까요?!

2023-08-03 08:32 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/data/service/AuthService.kt
> +    suspend fun signUp(@Body userRegistrationRequestBody: UserRegistrationRequestBody): Response<Unit>
저도 Request 찬성이요 ~!
Response도 ResponseBody 말구 Response 이니까요 ~

2023-08-03 13:43 UTC, sujin9 approved these changes
일단 어푸룹 할게욥 !!

2023-08-03 15:03 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/application/EdonymyeonApplication.kt
> +}
!!

2023-08-03 15:29 UTC, merged