Feat/#134 한달, 여섯달간의 소비 금액을 확인하는 기능을 구현한다
woowacourse-teams/2023-edonymyeon pull request #192
Opened 2023-08-02 07:52 UTC by hectick

## 🔥 연관 이슈

- close: #134 

## 📝 작업 요약

한달, 여섯달간의 소비 금액을 확인하는 기능을 구현하였습니다.
아래 응답의 consumptions 리스트에 담기는 순서는 오래된 것부터 담깁니다. (3월 -> 8월 방향)
<img width="329" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/62106852/78a007d1-2866-4832-9999-cfdc12f2aa33">

## 🔎 작업 상세 설명

한달, 여섯달간의 소비 금액을 확인하는 기능을 구현
- 1, 6개월이 아닌 기간이 들어오면 예외처리
- repository를 통해 memberId, 조회 년도, 조회 달을 넘기면 해당 달에 해당하는 데이터를 한번에 불러와 소비,절약 금액을 계산하는 로직을 기간만큼 반복합니다. (예를들어 1개월이면 1번, 6개월이면 6번)

## 🌟 리뷰 요구 사항

> 요청에 대해 발생하는 예외가 아니라 서버 내에서 로직이 잘못되어 발생하는 예외는 500 에러로 처리했는데 괜찮을까요?(ConsumptionPerMonth 클래스 내에서 발생하는 예외들입니다) 예외 코드와 네이밍도 같이 봐주세요!

> 클래스들 네이밍이 참 어렵네용... 혹시 리뷰하시다가 좋은 네이밍 있으면 추천 부탁드립니다.

> 서비스를 간결하게 짜기가 참 어려운 것 같네유.. 좋은 리팩토링 방향 있으면 추천 부탁드립니다.

> ConsumptionTestSupport2는 호이가 ConsumptionTestSupport를 자기 브랜치에서도 만들었대서 충돌을 피하고자 이름에 2를 붙였습니다. 추후에 두 PR이 다 마지되면 하나로 수정하는 pr을 파려고 합니다.

2023-08-02 12:31 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/consumption/repository/ConsumptionRepositoryTest.java
> +        final List<Consumption> 칠월_소비들 = new ArrayList<>(소비내역을_10개_생성한다(2023, 7, 회원));
```java
 final List<Consumption> 육월_소비들 = 소비내역을_10개_생성한다(2023, 6, 회원);
```
개 킹받네유

2023-08-02 12:32 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionService.java
> +        for (int i = 0; i < periodMonth; i++) {
먼가 좀 더 고민해보고 싶어서 내일 다시 해볼게여 ....

2023-08-03 01:41 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/global/controlleradvice/GlobalExceptionHandler.java
> +        exceptionInfoToHttpStatus.put(SERVER_ERROR_CONSUMPTION_YEAR_NOT_SAME, INTERNAL_SERVER_ERROR);
BusinessLogicException이라는 별도의 클래스를 만들어서 감싸주었습니다!
exceptionHandler에 해당 예외를 잡아서 콘솔에 error 로그를 찍는 코드도 추가했는데,
혹시 에러 로그를 찍기 위해 더 추가할 코드가 있을까요?

그리고 도메인에서 서버에 관한 네이밍(SERVER_ERROR)을 알고 있는 것이 이상해서 BUSINESS_LOGIC_ERROR_CONSUMPTIONS_NULL 이런식으로 예외 네이밍을 바꿔주었습니다!

2023-08-03 01:42 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/domain/ConsumptionsPerMonth.java
> +        return purchasePrice;
아주 죠아요

2023-08-03 01:50 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/domain/ConsumptionsPerMonth.java
> +            if (consumption.getConsumptionType() == PURCHASE) {
반영!

2023-08-03 02:08 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionService.java
> +        return periodMonth != 1 && periodMonth != 6;
조회 기간은 별도의 enum 클래스로 빼서 관리하도록 하였습니다!

2023-08-03 02:10 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionService.java
> +    public RecentConsumptionsResponse findRecentConsumptions(final MemberId memberId, final Integer periodMonth) {
반영하였습니당!

2023-08-03 02:16 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/ui/ConsumptionController.java
> +                                                                             @RequestParam("period-month") final Integer periodMonth) {
periodMonth에 1개월, 6개월이 아닌 다른 개월수, 예를 들면 12개월을 추가해 주면 현재 시간 기준 12개월을 조회할 수 있을 것 같습니다.

> 지금 api로는 현재 시간을 기준으로 밖에 조회할 수 없으니 예전 내역을 보기 힘들 것 같아요

이 부분은 시작 달, 끝 달이 파라미터로 들어와야 하는 부분일까요? (예: 2020년 2월부터 2021년 2월까지 조회)

2023-08-03 03:25 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/repository/ConsumptionRepository.java
> +    @Query("SELECT c FROM Consumption c LEFT JOIN FETCH c.post p LEFT JOIN FETCH p.member m WHERE m.id = :memberId AND c.consumptionYear =:consumptionYear AND c.consumptionMonth =:consumptionMonth")
오 `@EntityGraph` 완전 개쩌러요

2023-08-03 03:25 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/repository/ConsumptionRepository.java
> +    @Query("SELECT c FROM Consumption c LEFT JOIN FETCH c.post p LEFT JOIN FETCH p.member m WHERE m.id = :memberId AND c.consumptionYear =:consumptionYear AND c.consumptionMonth =:consumptionMonth")
개행 수정하여씁니당!!

2023-08-03 03:44 UTC, This2sho requested changes
고생하셨습니다 이리내 🙇‍♂️

테스트도 열심히 짜셨군요  댓글 몇개 남겼으니 확인해주시면 감사하겠습니돠 🍤

2023-08-03 03:44 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/consumption/repository/ConsumptionRepositoryTest.java
> +        final List<Consumption> 육월_소비들 = new ArrayList<>(소비내역을_10개_생성한다(2023, 6, 회원));
육월 vs 유월 ?!

2023-08-03 03:46 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/consumption/domain/ConsumptionsPerMonthTest.java
> +
반영 완...

2023-08-03 03:46 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/consumption/repository/ConsumptionRepositoryTest.java
> +        final List<Consumption> 육월_소비들 = new ArrayList<>(소비내역을_10개_생성한다(2023, 6, 회원));
유월...~

2023-08-03 04:00 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/domain/ConsumptionsPerMonth.java
> +        }
&& 아니죠 || 입니다 ..ㅋ
그거 빼고는 반영~^^

2023-08-03 04:01 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/consumption/ui/ConsumptionController.java
> +                                                                             @RequestParam("period-month") final Integer periodMonth) {
네 만약 api 가 수정 된다면 
1. 시작 달, 끝 달 을 파라미터로 받던지
2. 시작달이나 끝 달을 기준으로 조회할 기간을 받던지 해야할 것같아용 

당장 api를 수정할 수는 없으니 지금은 어푸로부 하꼐여... ><

2023-08-03 05:40 UTC, jyeost approved these changes

2023-08-03 07:26 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionService.java
> +        for (int i = 0; i < periodMonth; i++) {
여러 개월에 걸친 데이터를 가져온다면 List<Consumption>안에 여러 개월의 데이터가 섞이지 않을까요..?

2023-08-03 07:26 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionService.java
> +    public RecentConsumptionsResponse findRecentConsumptions(final MemberId memberId, final Integer periodMonth) {
열심히 분리해보았습니당~ 확인해주세욥

2023-08-03 07:27 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionService.java
> +        for (int i = 0; i < periodMonth; i++) {
🥲어렵네유 쿼리 잘짜기..

2023-08-03 07:41 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/consumption/domain/ConsumptionsPerMonth.java
> +        }
the huck.... 😱

2023-08-03 11:16 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionService.java
> +    public RecentConsumptionsResponse findRecentConsumptions(final MemberId memberId, final Integer periodMonth) {
깔끔~~~~👍🏻

2023-08-03 11:18 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionService.java
> +    public RecentConsumptionsResponse findRecentConsumptions(final MemberId memberId, final Integer periodMonth) {
```suggestion
    /**
     * @param periodMonth 현재 기준으로 조회하려는 개월 수 
     */
     요거 추가하고 이케 해놓고 나중에 findRecentConsumptions() 사용하는 코드에 커서 올려봐욥!
```

2023-08-03 11:32 UTC, BackFoxx requested changes
아무리 그래도 쿼리를 for문으로 돌려 날리는 건 용납할 수 없읍니다 이리내 ,,
개선해오십시오

2023-08-03 11:32 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/consumption/application/ConsumptionService.java
> +        for (int i = 0; i < periodMonth; i++) {
리포지토리에서 꺼내온 Consumption 안에 consumptionDate라는 LocalDate가 있잖아용!
getMonth()로 필터링할 수 있지 않을까욥

2023-08-03 11:32 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/global/controlleradvice/GlobalExceptionHandler.java
> +        exceptionInfoToHttpStatus.put(SERVER_ERROR_CONSUMPTION_YEAR_NOT_SAME, INTERNAL_SERVER_ERROR);
오 씻 하나를 말하면 열을 하는 이리내

2023-08-03 11:45 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/consumption/domain/ConsumptionsPerMonth.java
> +        }
헉.. 헉.. 헉.. 🤦‍♂️

2023-08-03 11:48 UTC, This2sho approved these changes
리뷰 반영된거 확인했습니다.
고생했어유 🍤🧀

2023-08-03 11:48 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/consumption/domain/ConsumptionsPerMonth.java
> -        }
👍 훨씬 깔끔하네유

2023-08-03 11:48 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/consumption/domain/ConsumptionsPerMonth.java
> +                .allMatch(consumption -> consumption.isSameYearMonth(firstConsumption));
`allMatch` 이런 메서드가 있었군요 😱

2023-08-03 13:09 UTC, BackFoxx approved these changes
between으로 쿼리 개선을 해냈군요~~~ 짱이에요 믿고있었다구 이리내

2023-08-03 13:14 UTC, merged