fix: 로그인을 하지 않은 경우 추천/비추천을 할 수 없도록 수정
woowacourse-teams/2023-edonymyeon pull request #235
Opened 2023-08-08 13:02 UTC by sujin9

## 🔥 연관 이슈

- close: #209 

## 📝 작업 요약

로그인 하지 않으면 추천, 비추천 할 수 없습니다.

## 🔎 작업 상세 설명

로그인 하지 않은 상황에서 추천, 비추천을 수행 시 _**추천 기능은 회원만 이용할 수 있습니다.**_ 라는 문구를 보여줍니다.

## 🌟 리뷰 요구 사항

> 코드 변화가 많지 않아 리뷰는 금방 하실 수 있을 것 같아요! :)

2023-08-09 09:53 UTC, rhkrwngud445 approved these changes
고생했어요 하티~ 작은 리뷰 남겼는데 확인 부탁드립니다!
어프로브 할게요~!!

2023-08-09 09:53 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
뷰에서 상태를 가지고 있는 것보다 뷰모델에서 가지는 건 어떨까요?!

2023-08-09 12:50 UTC, Choisehyeon requested changes
하티 수고 했어요!!👍
이건 무슨 오류인지는 잘 모르겠는데 로그아웃을 하고 애뮬레이터를 다시 돌린 후에 글을 눌러 상세페이지로 가면 <img width="326" alt="스크린샷 2023-08-09 오후 9 49 35" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/50761690/ce733c6d-292e-4e94-86de-430f309dbf43">
이렇게 빈화면이 뜨더라구요!! 이 부분에 대해서는 확인해보면 좋을 것 같아용😄

2023-08-10 03:40 UTC, sujin9 commented
@Choisehyeon 
로그아웃을 하면, token에 null이 아니라 "" (빈 값) 이 들어가서 인증 오류가 발생했었어요. 해결했습니당!

2023-08-10 03:42 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
그러게요 뷰모델에서 알고 있는게 의미상 더 맞을 것 같네요!! 😆 감사합니당
이 부분은 #243 여기서 로그인 체크 로직이 많이 들어가서 이 PR에서 함께 반영하도록 할게요!! :)

2023-08-10 07:36 UTC, merged