Feat/#236 로그인 여부 기능 접근
woowacourse-teams/2023-edonymyeon pull request #243
Opened 2023-08-09 07:15 UTC by sujin9

## 🔥 연관 이슈

- close: #236

## 📝 작업 요약

- 로그인 여부에 따라 기능 접근 제한

## 🔎 작업 상세 설명

- 로그인 안 하고 내가 쓴 글 누르면 스낵바 > 로그인 페이지 이동
- 로그인 안 하고 글 작성 버튼 누르면 스낵바 > 로그인 페이지 이동
- 로그인 안 하고 알람 페이지 들어가면 로그인 안내 문구 노출
- 로그인 안 하고 마이페이지 들어가면 로그아웃 버튼 안 보임
- 스낵바 커스텀

## 🌟 리뷰 요구 사항

> 레이아웃 파일 수정이 많아요. 특히, 커스텀 스낵바를 위해 테마를 수정하다 보니 MaterialComponents Theme을 사용하게 되었고, 이에 따라 레이아웃에 꽤나 자잘한 수정이 많이 들어갔습니다. 자세한 변경 내역은 커밋 메시지를 펼쳐보면 자세하게 작성해두었어요. 이런 부분들을 염두에 두시고, 직접 실행해서 디자인적인 요소들도 많이 봐주시면 좋겠습니다.

2023-08-09 09:58 UTC, rhkrwngud445 requested changes

2023-08-09 09:58 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
> +        val token = PreferenceUtil.getValue(AuthLocalDataSource.USER_ACCESS_TOKEN) ?: ""
null로 처리하는 것이 아닌 빈 값으로 처리하는 이유가 있을까요?!

2023-08-09 09:58 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/util/ActivityUtil.kt
> +}
Activity 유틸보다는 View 유틸에 가깝다는 생각이 되는데, 하티와 로피의 생각은 어떤가요?!

2023-08-09 12:53 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/util/ActivityUtil.kt
> +}
ViewUtil이 좋을 것 같아요!!

2023-08-09 13:15 UTC, Choisehyeon requested changes
하티 수고했어요~!! 디자인 부분은 확인해봤는데 괜찮은 것 같아요😄
근데 제가 로그인을 하고 나면 main 페이지가 아니라 로그인 버튼을 누른 곳으로 돌아가는 것으로 보이는데 마이 페이지에서 로그인을 누른 후 로그인이 되어 돌아오면 이와 같이 
<img width="327" alt="스크린샷 2023-08-09 오후 10 11 19" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/50761690/5c5fdbfd-7b02-4407-8f82-041265870c54">
그래프에 아무것도 뜨지 않는 것 같은데 이 부분 확인 부탁드려요!!

2023-08-10 07:58 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
> +        val token = PreferenceUtil.getValue(AuthLocalDataSource.USER_ACCESS_TOKEN) ?: ""
이 부분은 기존 토큰 저장 방식을 따라했었는데요, sharedpreference에도 nullable하도록 수정하면서 이 부분도 개선했습니다!

2023-08-10 08:19 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/util/ActivityUtil.kt
> +}
반영하겠습니다!!

2023-08-11 01:53 UTC, sujin9 commented
오류,, 해결했슴니다,,,
약간 허무(?)한 결과이긴 한데요,,,! ㅋㅋㅋㅋ 
로그인이 안 된 상태에서 그래프의 visibility를 false로 지정해줬는데...
이걸 다시 true로 바꿔주지 않아서 발생한 문제였습니당 ㅋㅋㅋㅋ

2023-08-11 01:54 UTC, sujin9 commented
@Choisehyeon @rhkrwngud445 
리뷰 반영했습니당 확인부탁드려요 ~~~ 😆

2023-08-11 02:09 UTC, Choisehyeon approved these changes
오류 해결한 거 확인했어요!! 이제 그래프가 잘 보이네요👍
함수명만 같이 정해서 수정하면 좋을 것 같아유😀 
set으로 할지 init으로 할지? 
수고했어용 approve 하겠슴돠😊

2023-08-11 05:43 UTC, rhkrwngud445 approved these changes
문제없는거 확인했습니다 고생했어요 하티~

2023-08-11 07:38 UTC, merged