refactor/#256_날짜표시수정
woowacourse-teams/2023-edonymyeon pull request #260
Opened 2023-08-10 08:40 UTC by Choisehyeon

## 🔥 연관 이슈

- close: #256 

## 📝 작업 요약

날짜 표시를 수정하였습니다.

## 🔎 작업 상세 설명

현재 시간과 작성된 날짜를 비교해서 방금전, 몇분전, 몇시간전, 며칠전, 몇달전, 몇년전으로 나오게 구현했습니다.

## 🌟 리뷰 요구 사항

날짜 표시는 Ui의 영역이라고 생각해서 UiModel에서 처리하도록 해주었습니다! 그런데 좀 더 예쁘게 리팩토링하고 싶은데 방법이 안 떠올라서 괜찮은 의견 있으면 리뷰 남겨주시면 좋을 것 같아요!! 우선은 postdetailactivity와 mypost에서 보이도록 했고 전체 게시글 부분은 핫게시글 뷰가 머지된 다음에 반영하겠습니다!

2023-08-11 03:07 UTC, sujin9 requested changes
복잡한 작업이었을텐데 고생 많았어요 로피!
리뷰는 코멘트에 남겼으니 확인해주세요 ~ 🌹

2023-08-11 03:07 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/DateUiModel.kt
> +    private fun getTimeAgo(diffTime: Long): String {
더 나은 코드가 떠오르진 않네요..! 
다만, 이 로직을 실제로 테스트를 하려면 기다려야 하는 단점이 있을 것 같아서요.
이 로직에 대한 테스트 코드가 있다면 좋을 것 같아요!

2023-08-11 03:07 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/DateUiModel.kt
> +        private const val TIME_MAXIMUM_DAY = 30
이걸 30으로 고정하는 게 편리하려나요..?
혹은 LocalDateTime의 `lengthOfMonth()` 를 사용하기에는 어려운 구조일까요?

2023-08-11 03:07 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/DateUiModel.kt
> +            else -> "${month}년 전"
sec 분 전, min 시간 전 과 같이
변수명과 단위가 일치하지 않아서 로직을 이해하기가 좀 더 어려워지는 것 같습니다 😢 
혹시 왜 다르게 하신건지 알 수 있을까요 ~?

2023-08-11 05:59 UTC, rhkrwngud445 commented
로피! 제 생각은 표시는 UI의 영역이지만 위는 계산로직도 포함되어 있는 것 같아 보여요!
UI모델이 아닌 Domain 레이어 역할이라고 생각되는데, 로피의 의견은 어떤가요?!

2023-08-11 06:11 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/DateUiModel.kt
> +    private fun getTimeAgo(diffTime: Long): String {
테스트를 하려면 도메인로직에 있는게 좋아보이긴하네요!

2023-08-11 06:11 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/DateUiModel.kt
> +        private const val TIME_MAXIMUM_DAY = 30
한 번 고민해보겠습니다!

2023-08-11 06:11 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/DateUiModel.kt
> +            else -> "${month}년 전"
이 부분은 수정해보겠습니당😄

2023-08-11 06:26 UTC, rhkrwngud445 requested changes
로피 고생했어요~!
저도 계산로직이 domain 레이어로 옮겨지면 좋을 것 같습니다!
고민해보시고 궁금하신 점 있으면 편하게 말씀주세요~!

2023-08-11 06:26 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/DateUiModel.kt
> +            else -> "${month}년 전"
문자열이 string.xml로 빠져도 좋을 것 같아요!

2023-08-11 06:53 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/DateUiModel.kt
> +            else -> "${month}년 전"
코비 이 부분을 string.xml로 빼려면 context가 필요한데 UiModel에서 context를 사용해서 빼주는게 맞는걸까요? 아니면 companion object를 말하는 걸까요?

2023-08-11 07:34 UTC, Choisehyeon commented
피드백 반영했습니다!! 확인 부탁드려요😄

2023-08-11 15:50 UTC, sujin9 commented
👀 !!
<img width="646" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/8490058/7803c4b0-d8a1-44e0-ba39-b5db0ed162dc">

2023-08-11 16:11 UTC, sujin9 approved these changes
변경된 코드랑 테스트 코드들 모두 확인했어요!
ui 로직이 깔끔해졌네요 굿 👍 
지금 오류 발생하는 거만 수정해주시면 될 것 같아용.
어푸루브 하겠숨니당 ~~~

2023-08-12 11:33 UTC, rhkrwngud445 approved these changes
잘 분리 된 것 같아요 로피!
고생했습니다! string.xml 관련해서 리뷰 남겨 드렸었는데, 추후 고민해보면 좋을 것 같아요!

2023-08-12 13:46 UTC, merged