Refactor/#263 핫게시글을 캐싱한다
woowacourse-teams/2023-edonymyeon pull request #274
Opened 2023-08-11 08:22 UTC by jyeost

## 🔥 연관 이슈

- close: #263 

## 📝 작업 요약

핫 게시글이 캐싱되어 있다면 캐싱 값을 쓰고, 안되어있다면 핫 게시글을 구하여 캐싱한다.

## 🔎 작업 상세 설명

redis를 사용하여 핫 게시글을 캐싱하도록 하였습니다.
캐싱 저장소로 레디스를 고른 이유는 저번 캐싱 테코톡에서 레디스가 나와서 아는 팀원들이 많을 것 같아서 골랐습니다.

### **아래의 레디스 설치를 한 후 리뷰 해주세용** 

레디스는 key:value로 저장하는 형식인데요 
현재는 핫 게시글의 아이디들인 List<Integer>와 isLast인 boolean 두가지를 저장합니다.

그러나 api요청에 따라서 조회하는 값이 달라지기 때문에 (현재 size 와 page를 요청으로 받고있음)
HOT_POST_SIZE:%s_PAGE:%s 와 같이 여러 값이 들어올 수 있도록 했습니다 
나중에 스케줄링으로 캐시를 비워줄때는 HOT_POST 키워드를 가지고 있는 모든 키를 삭제할 예정 입니다.
지금 서비스를 캐싱되어 있다면 캐싱 값을 쓰고 없으면 핫게시글을 새로 구하여 캐싱하고 요청을 만들고 있기 때문에 삭제 로직만 추가하면 될 것 같아용 

또 테스트에서 같은 레디스 서버를 공유하고 있기 때문에, 같은 키값을 쓰지 않도록 이미지 이름 생성 방식과 비슷하게 
전략 패턴으로 구분하였습니당 ~~~

레디스 사용 명령어 입니다.
```
레디스 설치
brew install redis

레디스 서비스 시작
brew services start redis

레디스 클라이언트로 접속
redis-cli

---- 접속 후 ----

모든 키 조회
keys *

저장소 비우기
FLUSHALL

원하는 값 찾기 (last 조회시)
get key

원하는 값 리스트 찾기 (hotPostIds 조회시)
LRANGE key 0 -1
(0은 시작하는 인덱스 -1은 끝나는 인덱스 입니다 )
```

현재 각 테스트를 따로 돌리면서 쿼리 나가는 것을 보고 캐싱이 된 값을 찾아오는지
디비로 부터 조회하는지 확인하고 있는데요... 다른 좋은 방법이 있다면 알려주세영....

2023-08-11 11:02 UTC, BackFoxx requested changes
고생하셨어요 께로!!
캐싱,, 캐싱이 되는지 안되는지 확인하는 방법을 모르겠어서 성능적인 리뷰는 못 드릴 것 같아요 🥲
대신 서비스와 관련해 리팩토링 할만한 점을 하나 남겨두었어욥

2023-08-11 11:02 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostReadService.java
>      public PostSlice<GeneralPostInfoResponse> findHotPosts(final HotFindingCondition hotFindingCondition) {
캐싱과 관련된 코드가 많이 노출돼있어서 약간 캡슐화해주면 좋겠다고 생각하는데
코멘트로 어떻게 설명해야 할 지 모르겠어서 제가 브랜치 파서 리팩토링을 해봤어요
요거랑 비슷한 느낌으로 최대한 캐시 관련된 작업을 PostReadService에서 숨겨주세요
[캐싱 작업 따로 뺀 브랜치](https://github.com/woowacourse-teams/2023-edonymyeon/commit/e1e23486c1cd5683fca4b45c31a7940fb166f389)

2023-08-11 21:43 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/cache/CacheIsLastService.java
> +                .hasKey(key));
`hasKey` 도 boolean을 반환하는데 `Boolean.TRUE.equals`로 한번 더 감싸준 이유가 있나요?!

2023-08-12 04:03 UTC, This2sho approved these changes
고생하셨습니다 케로👍
테스트 해보진못했지만 일단 코드만 보고 리뷰남겼습니다~

2023-08-12 16:17 UTC, hectick requested changes
캐싱...넘 어려워오..ㅜㅜㅜㅜ
변수명 리팩터링되면 다시 꼼꼼히보도록 하겟읍니다..

2023-08-12 16:17 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/cache/CacheIsLastService.java
> +public class CacheIsLastService {
블라블라캐싱서비스 이런 의미가 더 와닿을거같아용

2023-08-12 16:17 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/cache/CacheIsLastService.java
> +            throw new EdonymyeonException(POST_HAS_NEXT_NOT_FOUND_IN_CACHE);
어떤 요청이 들어오면 이 예외가 발생하는건가용

2023-08-12 16:19 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/cache/CachePostIdsService.java
> +        redisTemplate.setValueSerializer(new Jackson2JsonRedisSerializer<>(Long.class));
저도 궁금합니당!!

2023-08-14 06:52 UTC, BackFoxx approved these changes
아주훌륭해요케로~~~~블로그 써주실거죠?

2023-08-14 06:52 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostReadService.java
> +        return findHotPostFromRepository(hotFindingCondition);
깔끔해져서 보기 좋아졌어요!! 😊
요것도 아예 전략패턴으로 일원화하면 더 이쁘게 보이긴 하겠지만
이정도로도 충분히 이쁜 것 같아욥

2023-08-14 06:52 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/application/PostServiceHotPostsTest.java
> +@SpringBootTest
요거 이번에 도입한 @IntegrationTest로 바꾸어주세요!

2023-08-14 06:52 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/CacheConfig.java
> +        return new HotPostCachePolicy(new TestCacheKeyStrategy());
굳잡맨굳잡~~~

2023-08-14 07:07 UTC, hectick approved these changes

2023-08-14 07:07 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/cache/util/ProductCacheKeyStrategy.java
아주 조아요

2023-08-14 07:07 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/PostReadService.java
> +        return findHotPostFromRepository(hotFindingCondition);
깰꼼쓰~

2023-08-14 07:16 UTC, merged