Fix/#280_내가쓴글페이지 수정반영오류
woowacourse-teams/2023-edonymyeon pull request #282
Opened 2023-08-14 06:32 UTC by Choisehyeon

## 🔥 연관 이슈

- close: #280 

## 📝 작업 요약

내가 쓴글 페이지에서 글을 수정한 후 다시 돌아오면 반영이 안되는 오류 수정

## 🔎 작업 상세 설명

내가 쓴 글 페이지에서 글을 선택하여 들어간 후 수정한 다음 뒤로 가기하면 수정된 글이 반영되지 않는 오류 수정하였습니다! 
SwipeRefreshLayout을 사용하여 위로 당기면 글이 새로고침 되는 기능도 추가하였어요!!

## 🌟 리뷰 요구 사항

추가 된 내용이 많지 않아서 리뷰하는데 오래 걸리지는 않을 것 같아요😄

2023-08-15 13:30 UTC, rhkrwngud445 requested changes
고생했어요 로피! 작은 코멘트 남겼는데 확인 부탁드릴게요~!

2023-08-15 13:30 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostActivity.kt
> +        loadNewData()
잠시 휴대폰 홈화면으로 갔다오면 새로 갱신 되는 걸까요?!

2023-08-15 13:30 UTC, rhkrwngud445 commented on android/app/src/main/res/layout/activity_my_post.xml
> +        <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
저도 써야겠네요👍

2023-08-16 02:20 UTC, sujin9 approved these changes
수고했어요 로피 ~!
코비가 남겨준 부분 외에는 크게 얘기드릴 부분이 없는 것 같아 어푸루브 할게요 :)

2023-08-16 02:20 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostActivity.kt
> +        setAppbar()
여기도 `initAppbar()`!

2023-08-16 02:20 UTC, sujin9 commented on android/app/src/main/res/layout/activity_my_post.xml
> +        <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
저두요! 😊 
필요한 곳들 찾아서 적용 초ㅑ르르 함 하죠! 👍

2023-08-16 05:34 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostActivity.kt
> +        setAppbar()
이 부분은 수정하겠슴돠!!

2023-08-17 01:31 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostActivity.kt
> +        loadNewData()
지금 이 부분에서 크게 고민이 되는게 내가 쓴 글에서 상세페이지로 이동한 후 거기서 수정 페이지로 이동하면 이전의 상세페이지가 finish가 되고 수정 페이지에서 수정을 한 후 상세페이지를 finish로 이동하는게 아니라 새로운 상세 페이지를 열게되고 상세페이지에서 뒤로가기 버튼을 누르고 내가쓴글 페이지에 돌아오도록 구현이 되어있어요! 
근데 이러면 상세페이지로 registerForActivityResult를 사용해서 ResultCode를 넣고 넘어갔다가 수정을 한 후 돌아오게 되면 ResultCode가 Cancel이 된 채 돌아오게 되더라구요! 그래서 이부분을 어떻게 해결해야할 지 계속 고민 중인데 아직 방법을 못 찾았어요😂

2023-08-17 13:54 UTC, rhkrwngud445 approved these changes

2023-08-17 13:56 UTC, merged