Feat/#281 flyway 반영
woowacourse-teams/2023-edonymyeon pull request #290
Opened 2023-08-14 13:04 UTC by hectick

## 🔥 연관 이슈

- close: #281 

## 📝 작업 요약

데이터베이스 버전관리를 위한 도구인 flyway를 도입하였습니다.

## 🔎 작업 상세 설명

[이돈이면 기술블로그](https://velog.io/@idonymyeon/Flyway를-도입했다)를 참조해주세요

## 🌟 리뷰 요구 사항

> V1_init.sql에 있는 쿼리 잘 썼는지 한번씩 검토 부탁드립니다.

## prod 모드로 테스트 실행해보실 여러분들을 위한 application-prod.properties Mysql 데이터베이스 셋팅

여기에는 데이터베이스 url을 넣어주세옹
```
spring.datasource.url=${MYSQL_ADDRESS}
```

여기에는 CRUD 권한이 있는 유저 정보를 넣어주세옹
```
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
```

여기에 테이블 수정 권한이 있는 유저 정보를 넣어주세옹
```
spring.flyway.user=${MYSQL_FLYWAY_USERNAME}
spring.flyway.password=${MYSQL_FLYWAY_PASSWORD}
```
유저를 만들고 권한을 주는 방법을 까먹으셨다구옹?
```
mysql -u root -p // 접속

use mysql; //mysql 스키마 사용
select host, user, plugin, authentication_string from user; //유저 조회

create user 'kero'@'localhost' identified by '비밀번호임니다';

grant all privileges on 스키마이름.* to 'kero'@'localhost'; //모든 권한 부여할 경우
grant insert, select, update, delete on 스키마이름.* to 'kero'@'localhost'; //CRUD 권한 부여할 경우
```

2023-08-14 20:39 UTC, hectick commented
properties 파일의 주석들은 merge 되기 전에 지우고 merge하도록 하겟읍니당~

2023-08-14 21:56 UTC, hectick commented on backend/src/main/resources/db/migration/mysql/V1__init.sql
> +    foreign key (post_id) references post (id) on delete cascade
이때는 양방향의존 안생기게하려고 이렇게 했었는데 여기 on delete cascade 대신에 PostService에서 Post가 지워질때 Consumption도 지워지게 바꿔볼까유? 마침 PostConsumptionService도 있으니까유! (다른 이슈 파서)
현재 서버의 데이터베이스들에 FK 제약조건 이름이 랜덤으로 정해져서 추후에 제약조건을 flyway로 자동으로 없애거나 수정하긴 어려울 것 같아서, 먼저 수정하고 flyway를 반영해볼까 생각해봤어유

2023-08-16 03:24 UTC, jyeost requested changes
이리내 코드는 잘 봣습니다 !!!
저 근데 직접 돌려보려 하니까 어려워서...ㅠㅠ 
난주에 시간 될때 도움주십셔...

2023-08-16 03:24 UTC, jyeost commented on backend/src/main/resources/db/migration/mysql/V1__init.sql
> +    created_at datetime(6),
이건 다른 얘기긴 한데, 
create_at 컬럼 업데이트 이전 데이터들 다 채워주고 not null 제약넣어야 하는것 아닌쥐요?? 
@ 여우

2023-08-16 04:00 UTC, hectick commented on backend/src/main/resources/db/migration/mysql/V1__init.sql
> +    age integer,
오
감사합니다

2023-08-16 04:00 UTC, hectick commented on backend/src/main/resources/db/migration/mysql/V1__init.sql
> +create table if not exists profile_image_info (
동의함니다 같이 얘기해보면 좋을 것 같아요

2023-08-16 04:31 UTC, BackFoxx commented on backend/src/main/resources/db/migration/mysql/V1__init.sql
> +    foreign key (post_id) references post (id) on delete cascade
이벤트를 도입해보면 어떨까요?

2023-08-16 04:34 UTC, BackFoxx commented on backend/src/main/resources/db/migration/mysql/V1__init.sql
> +    created_at datetime(6),
mySQL에서 timestamp랑 datetime은 기본 not null입니다!
nullable 설정을 해줘야 null을 넣을 수 있어요

2023-08-16 04:38 UTC, BackFoxx approved these changes
수고했어요!~

2023-08-16 05:54 UTC, This2sho approved these changes
적용한거랑 블로그 확인했습니다!
flyway를 사용하더라도 사용자가 직접 DDL을 관리해줘야 하는군요!
고생하셨습니다 이리내 바로 어프루부 할게유 🍤

2023-08-16 05:55 UTC, jyeost approved these changes

2023-08-16 05:55 UTC, jyeost commented on backend/src/main/resources/db/migration/mysql/V1__init.sql
> +    created_at datetime(6),
헉 그러면 modified_at은 처음 생성될때 create_at이랑 같은 시각이 들어가는 건가여??

2023-08-16 06:14 UTC, hectick commented
V{데이터베이스가 바뀌었을때 1 증가}.{테이블 추가될때마다 1 증가}.{스키마 수정될때 1 증가}
ㄱㅊ?

2023-08-16 07:12 UTC, merged