Feat/#284 카카오 로그인 구현
woowacourse-teams/2023-edonymyeon pull request #298
Opened 2023-08-15 23:37 UTC by This2sho

## 🔥 연관 이슈

- close: #284 

## 📝 작업 요약

- 카카오 로그인 기능 구현
- 카카오 로그인 구현을 위해 회원 필드 추가(socialType, socialId)

## 🔎 작업 상세 설명

1. 안드로이드가 인증 완료 후, `accessToken`과 함께 카카오 로그인 요청을 보냄
2. 해당 `accessToken`으로 카카오 리소스 서버에 해당 유저의 id(카카오) 요청
3. 해당 id가 존재하면 가져오고 없는 경우 새로 생성(이메일, 비밀번호, 닉네임 UUID)
4. 해당 회원의 이메일, 비밀번호로 base64 인코딩 (이 부분은 기존 로그인과 같음..)

- Session으로 변경하려고 했으나, 기존 로그인도 변경이 많을 것(안드로이드)으로 예상되서 현재는 기존 로그인 방식으로 구현함.. 추후 변경 예정 

## 🌟 리뷰 요구 사항

> 2번 과정을 처음에는 `AuthController`에 두었으나, 테스트 코드 모킹 및 Response 생성을 Service에 두기 위해 `AuthService`로 이동하였슴니다..
하지만, 카카오에게 보내는 url, HttpHeader등이 포함되어 있어서.. 좀 이상합니다
의견 부탁드려요

2023-08-16 02:35 UTC, hectick reviewed
고생하셨네유^^

2023-08-16 02:35 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/auth/ui/AuthController.java
> +            throws JsonProcessingException {
`ResponseEntity<Void>` 아닌가욥

2023-08-16 02:35 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +    }
이 함수는 반환값을 Member로 하고,
`tokenGenerator.getBasicToken(member.getEmail(), member.getPassword());` 부분은 Controller에서 해주는게 어떤가요

2023-08-16 02:35 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +    }
이부분을 별도의 KakaoLoginRequestSender같은 클래스로 빼버리고, 컨트롤러에서 이 클래스를 필드로 갖는 것은 어떤가요?
그럼 테스트할때 모킹할수 있을 것 같아요

2023-08-16 02:35 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +    }
enum을 클래스 내부에 숨겨논 이유가 무엇인가요

2023-08-16 04:55 UTC, jyeost reviewed
빨리 구현해주시느냐 수고하셧어영~~

다만 리뷰에 남긴 것 처럼 KakaoLoginResponse를 만들어 주는 부분을 따로 캡슐화를 해주고 
테스트가 문서화를 위한 테스트만 있는 것 같아서 현재 소셜 로그인에서 사용하는 테스트 케이스 추가 됐으면 좋겠어요~

2023-08-16 04:55 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +
저도 이 부분이 서비스로직은 아닌 것 같아요 !
또 다른 소셜 로그인이 추가되거나 변경될 가능성을 생각해서 만들어야 할 것 가타영

2023-08-16 04:55 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +                .nickname("#" + socialType.name() + UUID.randomUUID())
오옹 전부 랜덤으로 만들어주는군영
근데 로직이 있으니 메서드 명으로 설명 되었으면 좋겠어요

2023-08-16 04:55 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +                .orElseGet(() -> joinSocialMember(kakaoLoginResponse.id(), SocialType.KAKAO));
3.해당 id가 존재하면 가져오고 없는 경우 새로 생성(이메일, 비밀번호, 닉네임 UUID)

이렇게 구현했다고 했는데, 회원 가입시에는 사용자에게 개인정보 동의를 받고 있잖아요??
소셜 로그인 시도할때 동의를 받고 시작하는 건가용...???

2023-08-16 06:18 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
>      }
좋심다~

2023-08-16 06:18 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/ui/AuthController.java
> +            throws JsonProcessingException {
처음에 찍어보다가 안바꾸고 PR을 날려버렸네유..

2023-08-16 06:57 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +    }
도메인을 컨트롤러로 넘기기가 싫어서.. 이렇게 했는데
Dto 하나 만들어서 넘기도록 하겠슴돠!

2023-08-16 06:57 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +    }
좋슴돠~

2023-08-16 07:07 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +    }
enum에 로직이 없고 `Member`에서만 사용될 거 같아 내부에 뒀습니다~!

2023-08-16 08:48 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/domain/TokenGenerator.java
> +    public String getBasicToken(final String email, final String password) {
Spring으로 관리되어도 된다고 생각했스므니다!

2023-08-16 08:48 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +
좋습니다!

2023-08-16 08:50 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +                .nickname("#" + socialType.name() + UUID.randomUUID())
`of(final Long socialId, final SocialType socialType)` 시그니처만 보면
소셜 아이디와 소셜 타입으로 회원을 생성하는 정팩메로 생각할 수 있지 않을까유? 🥺

2023-08-16 08:54 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +                .orElseGet(() -> joinSocialMember(kakaoLoginResponse.id(), SocialType.KAKAO));
<img width="481" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/48519860/1203ff7c-5ab9-4fef-aade-969914106da7">

이렇게 카카오 로그인 시 동의를 받고 있고 카카오에서 받는 값은 식별자 뿐입니다.
이메일, 비밀번호, 닉네임은 모두 UUID로 생성해줘서 개인정보는 카카오 계정의 식별자? 밖에 없고

저희가 만든 `개인정보 처리방침`을 말하시는 거면 안드로이드 담당자(하티)에게 물어보시면 될 거 같슴돠~!

2023-08-16 10:19 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +                .orElseGet(() -> joinSocialMember(kakaoLoginResponse.id(), SocialType.KAKAO));
그렇군여 화긴햇슴돠~

2023-08-16 10:24 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +                .nickname("#" + socialType.name() + UUID.randomUUID())
시그니처까지 봐야 이해가 되는것 가타서여 ㅎㅎ
정팩매가 생성자랑 다른 가장 큰 장점은 메서드 명으로 로직을 설명할 수 있다 같은데
그것이 잘 안드러나는 것 같아서유ㅎㅎ
근데 큰 지적은 아니니 넘어가도 됨미당

2023-08-16 10:35 UTC, jyeost approved these changes
화긴 햇습니다 수고했습니당~~~

2023-08-16 13:06 UTC, BackFoxx requested changes
굳잡입니다 호이~~~ 컨디션 안 좋아보였는데도 수고 많으셨어욥
나중에 소셜로그인 추가될 때를 대비해서 아주 쪼끔만 더 유연한 코드가 되었음 하는 마음으로 코멘트 남겼습니다

2023-08-17 00:44 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +    }
흠.. 일단 레포지토리단에서는 동일한 메소드를 사용할 수 있을거 같지만, 서비스 단에서 들어오는 request와 response는 oauth를 제공해주는 사이트마다 다를 거 같아서 이렇게 구현했슴돠!

2023-08-17 00:49 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
> +    }
oauth 같이 다른 회사에서 제공해주는 스펙은 바뀔 가능성도 있고
DTO는 구체적으로 하는게 낫지 않을까유??

2023-08-17 00:53 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/application/KakaoAuthResponseProvider.java
> +        return restTemplate.postForObject(KAKAO_INFO_REQUEST_URL, kakaoRequest, KakaoLoginResponse.class);
오홍 스프링 http 통신용으로 내장되있는게 RestTemplate이라 이걸 썼는데
okhttp 확인해보겠습니다~!

2023-08-17 01:04 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +    private Long socialId;
반영하겠슴돠~!

2023-08-17 01:52 UTC, BackFoxx approved these changes
데일리미팅에서 호이가 해준 말이 일리가 있어서 어프루브 하겠습니다!
나중에 소셜로그인 종류가 추가되면 또 고민해보기로 해요~

2023-08-17 05:16 UTC, merged