Feat/#285 회원탈퇴 구현
woowacourse-teams/2023-edonymyeon pull request #299
Opened 2023-08-16 04:20 UTC by This2sho

## 🔥 연관 이슈

- close: #285 

## 📝 작업 요약

- 회원 탈퇴 기능을 구현하였습니다. (이슈에 정리해둠)

## 🔎 작업 상세 설명
- 탈퇴한 회원으로 로그인할 경우 예외처리 하였습니다.
- 탈퇴한 회원의 닉네임을 `Unknown`으로 표시하도록 하였습니다..

주요 기능 및 로직에 관해 설명해주세요.

## 🌟 리뷰 요구 사항

> 특정 기간이 지난 후, 삭제 체크된 회원들을 자동으로 삭제한다. 이 부분은 추후 구현해야 할 거 같습니다..!

2023-08-16 05:16 UTC, jyeost approved these changes
탈퇴한 회원의 게시글을 조회하는 부분도 테스트가 있으면 좋을듯??합니다??
호이씨 테스트 귀찮으신가요???

2023-08-16 05:16 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +        member.delete();
회원 탈퇴를 복구 하지 않을 터이니, 해당 회원의 프로필 사진이 있다면 
사진도 삭제되어야 할것 같아요 (저장소도 디비도 !!)
(지금 프사를 설정하는 로직이 없지만 나중에 추가하려면 까먹을 것 같아서용)

2023-08-16 05:16 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/auth/application/AuthServiceTest.java
> +    @Test
저희컨벤션 정할때 모킹은 최대한 안하기로 하지 않았나유??
로직을 확인하는 테스트가 Integration Test와 서비스 레이어 둘 다 있다면 하나는 모킹으로 해줘도 될 것 같은데, 지금 테스트가 꼼꼼하지도 않은데 그냥 실제로 테스트 하시져 ㅇ.ㅇ!

2023-08-16 05:42 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
> +    MEMBER_IS_DELETED(3006, "삭제된 회원입니다."),
이거 근데 badRequest로 내려가나여??

2023-08-16 08:05 UTC, hectick approved these changes
^^ 업보 청산하느라 고생이 많네유

2023-08-16 09:28 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +    private static final String UNKNOWN = "Unknown";
일단 임의로 `Unknown`으로 표시해뒀습니다!

2023-08-16 09:37 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +        member.delete();
꼼꼼한 리뷰 감사합니다 👍

2023-08-16 10:12 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/auth/application/AuthServiceTest.java
> +    @Test
탈퇴한 회원의 게시글 조회 하는 테스트 추가하도록 하겠슴돠~!

2023-08-16 11:07 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/auth/application/AuthServiceTest.java
> +    @Test
통합테스트에서 예외에대한 테스트만 이뤄지고 있고, 해당 요청이 정상 처리 되는 테스트는 docs에서 모킹으로 해주고 있어서요!
이 레이어에서는 직접 확인해보는게 어떨까 생각했슴니당 ~

2023-08-16 13:29 UTC, BackFoxx requested changes
고생많으셨어요 호이!!
하지만 도메인 객체에 @Builder.. 허가할 수 없습니다

2023-08-16 13:29 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +@Builder
nullable하지 않은데 값이 null인 필드를 가진 인스턴스 객체가 속출할 수 있기 때문에 도메인 객체에 빌더는 매우 위험해 보입니다.. 생성자나 정팩메를 사용해 객체생성을 할 수 있게 해주세요! 🥲

2023-08-16 13:29 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +    public void delete() {
'탈퇴' 를 의미하는 더 나은 단어들이 있어보여요!
개인적으로는 quit이나 leave가 괜찮아보이는데 호이는 어떤가요
https://blog-ko.engram.us/withdraw/

2023-08-16 13:29 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +    public void delete() {
controller에서는 withdraw라는 이름을 쓰고 있네요? 여기에도 withdraw가 적절해 보이는데 👀

2023-08-17 01:43 UTC, BackFoxx approved these changes
현재는 일정이 너무 빡빡하고 버그없이 잘 돌아가기 때문에 어프루브를 하겠습니다!
방학이나 레벨 4 때 고쳐주세요~

2023-08-17 05:18 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +    public void delete() {
필드를 `deleted`로 해나서 메서드를 생각없이 `delete`로 했네요 🥺
`withdraw()`로 수정하겠씀니다👍

2023-08-17 05:49 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/domain/Member.java
> +@Builder
필드에 null이 들어갈 수 있군요...!
지금 회원 객체에 계속 필드 추가하면서 생성자로 생성하는게 다 깨져서 이후에 수정하도록 하겠습니다!

2023-08-17 06:18 UTC, merged