Feat/#22_로그인_뷰
woowacourse-teams/2023-edonymyeon pull request #31
Opened 2023-07-13 11:18 UTC by rhkrwngud445

🔥 연관 이슈
close #22 

📝 작업 요약
로그인 화면 추가

🔎 작업 상세 설명
- 도현체 폰트 추가
로그인 화면 xml 작성
포인트 컬러 배경 solid, stroke 2개 추가

🌟 리뷰 요구 사항
리뷰 예상 시간: 10분

2023-07-13 12:53 UTC, sujin9 reviewed
고생했어요 코비 ~! 짱짱 😆
몇 가지 궁금한 점과 생각을 남겨보았어요 :)

2023-07-13 12:53 UTC, sujin9 commented on android/app/src/main/res/layout/activity_login.xml
> +            app:layout_constraintStart_toEndOf="@id/space_password_left"
`app:layout_constraintStart_toStartOf="@id/tv_email"`
"이메일"과 "비밀번호"의 왼쪽 시작 위치가 동일하게 정렬이 되어있기 때문에
굳이 동일한 Space를 추가하지 않고 이렇게 표현할 수 있지 않을까? 하는 생각이 들어요!
코비는 어떻게 생각하시나요?

2023-07-13 13:56 UTC, Choisehyeon requested changes
로그인 뷰 구현하느라 고생했어요!
저도 하티랑 같은 부분에서 궁금중이 있어서 질문 남겼습니다😄

2023-07-13 13:56 UTC, Choisehyeon commented on android/app/src/main/AndroidManifest.xml
> +            android:exported="true"></activity>
저희 앱이 LoginActivity에서 시작해야하는 건 맞으니까 각각 작업을 진행한 이후에, LoginActivity에서 시작하도록 수정하는게 괜찮지 않을까요??

2023-07-13 13:56 UTC, Choisehyeon commented on android/app/src/main/res/layout/activity_login.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
저도 ScrollView가 왜 필요한지 궁금합니다!! 해상도가 달라져도 비율로 설정하면 스크롤 뷰로 구현하지 않아도 괜찮을 것 같은데 혹시 이렇게 하신 이유가 뭔지 저도 궁금해요😄

2023-07-13 14:09 UTC, rhkrwngud445 commented on android/app/src/main/res/layout/activity_login.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
이것 또한 디자인 영역으로 보입니다 
비율에 맞게 뷰를 구성하면서 가로가 긴 디바이스는 세로도 길어질거에요.
아래 여백이 넉넉치 않은 경우에는 디바이스 길이를 넘어갈텐데 그 상황에 어떻게 대처를 할 지 디자인 부분에서 고민이 필요해 보입니다

2023-07-13 14:15 UTC, rhkrwngud445 commented on android/app/src/main/res/layout/activity_login.xml
> +            app:layout_constraintStart_toEndOf="@id/space_password_left"
"이메일" Text와 EditText와 여백이 다릅니다 체인이 잘 못 연결된거 같아요.
내일 EditText 마진(체인)을 수정해볼게요🤣

2023-07-14 06:55 UTC, Choisehyeon approved these changes
수고했어요~!!

2023-07-14 06:56 UTC, rhkrwngud445 commented on android/app/src/main/res/layout/activity_login.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
-회의 결과-
- 대부분 디자인에서 ScollView가 사용됨, 디자인적 수정이 일어나는 것보다 ScrollView 통일되는 것이 낫다고 판단되어 ScrollView를 사용하는 것으로 결정

2023-07-14 06:56 UTC, sujin9 approved these changes
고생했어요 코비 ~ 👍

2023-07-14 06:56 UTC, rhkrwngud445 commented on android/app/src/main/AndroidManifest.xml
> +            android:exported="true"></activity>
로그인이 개발되기 전까지 MainActivity에서 앱이 시작하도록 결정

2023-07-14 06:57 UTC, merged