Feat/#6 메인 페이지
woowacourse-teams/2023-edonymyeon pull request #34
Opened 2023-07-16 08:05 UTC by rhkrwngud445

## 🔥 연관 이슈

- close: #6

## 📝 작업 요약

바텀 네비게이션 구현 및 프레그먼트 연결

## 🔎 작업 상세 설명

바텀 네비게이션을 show/hide 방식으로 구현, 2차 데모데이 때 발표할 프레그먼트 외에 준비 중인 페이지 TextView를 출력하도록 함
build.gradle에 fragment-ktx 추가(commit 등 프레그먼트 트랜젝션 명령어를 간단하게 사용가능)

## 🌟 리뷰 요구 사항

> 리뷰 예상 시간 및 집중 리뷰 부분을 작성해주세요.
MainActivity 위주로 봐주시면 좋을 것 같습니다:) ViewModel등 라이브러리를 활용한 더 좋은 방안도 있을까요..?

2023-07-16 12:14 UTC, BackFoxx commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/alarm/AlarmFragment.kt
> +}
개행!

2023-07-17 05:00 UTC, Choisehyeon requested changes
코비 수고했어요👍 ViewModel을 사용해서 bottomNavigation 연결하는 부분은 좀 더 찾아봐야할 것 같아요!

2023-07-17 05:17 UTC, sujin9 reviewed
고생했어요, 코비!
로피의 말처럼, bottom navigation에 viewModel 적용하는 것 관련해서는
좀 더 찾아볼 필요가 있을 것 같아요.

하지만, bottom navigation이 구현되어야 다른 프래그먼트 및 기타 액티비티로의 이동 구현도 될 수 있다보니, 
뷰모델을 연결하는 데에 시간이 좀 소요될 것 같다면 우선 머지한 뒤에 추후 리팩토링을 해도 될 것 같네요! :)

2023-07-17 05:17 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +
동감합니다!
binding이랑 view model도 초기화 방법을 통일하면 좋을 것 같아요 :)

2023-07-17 05:17 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/category/CategoryFragment.kt
> +        return inflater.inflate(R.layout.fragment_preparing_page, container, false)
바인딩 적용은 추후에 해주시나요~!? ㅇ.<

2023-07-17 05:31 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +
저도 통일되면 좋을 것 같네요:) 
lazy를 선택한 이유는 한번만 초기화가 되면 되고 변경 가능성이 없다고 판단되어 by lazy를 선택했습니다!

2023-07-17 05:32 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/category/CategoryFragment.kt
> +        return inflater.inflate(R.layout.fragment_preparing_page, container, false)
해당 화면을 구현 할 때 적용하려고 합니다😎

2023-07-17 05:32 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/alarm/AlarmFragment.kt
> +}
🧐

2023-07-17 05:34 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +
네 저도 코비의 생각이 맞는 것 같아요! by lazy로 통일하면 좋을 것 같아요👍

2023-07-17 05:34 UTC, Choisehyeon approved these changes
approve 하겠슴돠!

2023-07-17 06:49 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +
동의합니다! :)

2023-07-17 06:50 UTC, sujin9 approved these changes
수고하셨어요 ~!

2023-07-17 07:07 UTC, merged