Feat/#335 알림 설정 기능 구현
woowacourse-teams/2023-edonymyeon pull request #371
Opened 2023-09-04 05:42 UTC by BackFoxx

## 🔥 연관 이슈

- close: #335 

## 📝 작업 요약

어떤 알림을 받고 받지 않을지 사용자가 선택할 수 있는 API를 구현합니다.

## 🔎 작업 상세 설명

![Animation](https://github.com/woowacourse-teams/2023-edonymyeon/assets/95093193/44e827ac-c536-4772-b5c3-22272b9d4171)
알림 설정이라고 하면 그냥 활성화/비활성화만 하면 되는 줄 알았는데,
어떤 알림이 비활성화되면 어떤 알림도 따라 비활성화되거나 반대로 활성화되어야 하는 등
알림의 성격에 따라 다른 알림에 영향을 주어야 하는 저주받은 도메인이었습니다.

그래서 ActivationManager, DeactivationManager라는 인터페이스를 만들고
어떤 알림이 활성화/비활성화된 이후
해당 알림의 성격에 알맞는 Manager 구현체를 동작하게 하는 방식으로 구현했습니다.

각 Manager가 어떤 일을 수행하는지는
클래스 내부의 javadoc으로 설명을 적어두었습니다.

주석만으로는 이해가 부족하다면 코멘트를 남겨주시거나
직접 물어봐 주세요!

## 🌟 리뷰 요구 사항

> 미처 생각하지 못했던 도메인 제약이나 버그가 있을 것 같습니다.
도메인 기능을 중점으로 리뷰해주시면 감사하겠습니다~

2023-09-05 08:38 UTC, jyeost requested changes

2023-09-05 08:38 UTC, hectick commented on backend/src/test/resources/truncate.sql
> -TRUNCATE TABLE SETTINGS_DEPENDENT_SETTINGS;
<데이터베이스에 엔티티 변경사항이 잘 반영되는지 확인하는 법>
application.properties에서 prod-test 옵션으로 변경하고
application-prod-test.properties에 주석처리된 부분들을 로컬 mysql 로 설정해준 후, 애플리케이션을 실행하면 테이블 스키마가 달라서 예외가 터지는 것을 볼 수 있어요!

2023-09-05 08:44 UTC, This2sho requested changes

2023-09-05 08:44 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/setting/domain/SettingType.java
> +    public static final SettingType NOTIFICATION_PER_THUMBS = new SettingType("1003", Category.THUMB, Weight.FIVE);
`SettingType` 자체를 Enum으로 안하고 class로 한 이유가 있나요?!

2023-09-05 08:44 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/setting/domain/SettingType.java
> +    public static final SettingType NOTIFICATION_THUMBS = new SettingType("1001", Category.THUMB, Weight.TEN);
특정 카테고리 내에서 하나의 설정만 가능하기 때문에 10짜리가 필요없을거 같아유!

2023-09-06 07:12 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/domain/Category.java
> +    ALL, THUMB, COMMENT, REMINDING
헙 좋아요~!

2023-09-06 07:13 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/application/SettingEventListener.java
> +    @EventListener
헙 큰일 날거에요!
수정해 두겠습니다

2023-09-06 08:11 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/domain/SettingType.java
> +    public static final SettingType NOTIFICATION_THUMBS = new SettingType("1001", Category.THUMB, Weight.TEN);
없앴어용!! 특정 카테고리의 10짜리 설정을 없앴더니 Manager도 2개 줄었네용

2023-09-06 08:14 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/domain/SettingType.java
> +    public static final SettingType NOTIFICATION_PER_THUMBS = new SettingType("1003", Category.THUMB, Weight.FIVE);
다시 보니 enum으로 해도 상관없을 듯 하네용!
바꿨습니다~!

2023-09-06 08:27 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/application/SettingService.java
> +                .orElseThrow(() -> new EdonymyeonException(ExceptionInformation.MEMBER_ID_NOT_FOUND))
이쁘고 깔끔하게 수정했어요!
갠적으로 되게 이쁘게 바뀌어서 쫌 자랑하고 싶음

2023-09-06 15:57 UTC, BackFoxx commented on backend/src/test/resources/truncate.sql
> -TRUNCATE TABLE SETTINGS_DEPENDENT_SETTINGS;
작성 완료~~!!

2023-09-07 01:53 UTC, hectick requested changes
알림 구현 기능하느라 고생하시는군요 🦊
반영해주었으면 하는 사항이 있어 리퀘스트 체인지 드립니다

2023-09-07 01:53 UTC, hectick commented on backend/src/main/resources/db/migration/mysql/V1.3.0__setting.sql
> +alter table setting add foreign key (member_id) references member (id);
여기 뽀린키 걸때, 뽀린키 제약조건 이름을 안걸면 우리가 모르는 임의의 값이 제약조건 이름이 되서 추후에 flyway 스크립트로 뽀린키를 삭제하거나 수정할 일이 있을 때 db에서 제약조건 이름을 확인해봐야할 것 같아요. (운영 서버와 테스트 서버의 제약 조건 이름이 다를 수 있다는 것은 덤)
그래서 새로 추가되는 테이블들은 미리미리 제약 조건 이름을 정해주는게 좋겠읍니다

예시)
```suggestion
alter table setting add constraint fk_setting_member_id foreign key (member_id) references member (id);
```

<img width="735" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/62106852/2f708521-14e1-4f48-96ac-3f7ab94de613">

2023-09-07 01:53 UTC, hectick commented on backend/src/main/resources/application.properties
> +spring.profiles.active=dev
이게 머죠~

2023-09-07 01:53 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/setting/application/activationmanager/ActivatingPrimaryManager.java
> +    }
파라미터로 target을 받고 있는데 쓰고 있지 않아요!
그리고 이 메서드는 들어오는 target이 active 상태라는 것이 꼭 보장되어야 할 것 같은데
target이 active 상태가 아니라면 비즈니스 로직 예외를 던져주는 것은 어떤가요?

2023-09-07 01:53 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/setting/application/activationmanager/DeactivatingSameWeightsManager.java
> +    }
여기도 target이 active 상태라는 것이 보장되어야 할 것 같아요. (위와 같음)
서비스 로직을 보고나서 이걸 보면 이해가 되지만, 추후 유지보수 하는 사람이 잘못 가져다 쓸 수 있으니까요!
뿐만 아니라 deactivate하는 manager들도 비슷한 맥락으로 deactive 상태가 보장되어야 할 것 같습니다

2023-09-07 01:53 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/setting/application/SettingService.java
> +        setting.ifInactive(() -> activateSetting(member, setting));
오오..👍

2023-09-07 07:39 UTC, BackFoxx commented on backend/src/main/resources/db/migration/mysql/V1.3.0__setting.sql
> +alter table setting add foreign key (member_id) references member (id);
좋은 조언입니다

2023-09-07 07:39 UTC, BackFoxx commented on backend/src/main/resources/application.properties
> +spring.profiles.active=dev
큰일날뻔~

2023-09-07 07:54 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/application/activationmanager/ActivatingPrimaryManager.java
> +    }
요기서 target을 사용하지 않지만 ActivationManager의 인터페이스 스펙을 지키려면 어쩔 수 없는 것 같아요 🥹

active가 아니라면 예외 던지는 건 합리적인 것 같아요!
각 Manager 구현체마다 같은 검증 로직을 담는 건 별로인 것 같아서,
Manager 인터페이스를 추상 클래스로 바꾸고
추상 클래스 쪽에서 공통적인 검증 작업을 하도록 바꿨습니덩

2023-09-07 07:57 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/application/activationmanager/DeactivatingSameWeightsManager.java
> +    }
(위와 같음)

2023-09-07 07:57 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/application/SettingService.java
> +        setting.ifInactive(() -> activateSetting(member, setting));
람다 짱이에요진짜!!!!!

2023-09-07 08:00 UTC, hectick approved these changes
굿이네용~ approve 완.

2023-09-07 08:23 UTC, jyeost commented on backend/src/main/resources/db/migration/mysql/V1.3.0__setting.sql
> +alter table setting add foreign key (member_id) references member (id);
@hectick 이리내씨 왜 init file 작성때 뽀링키 이름 설정 안해서 저히를 괴롭게 만드시나요 ?????

2023-09-07 10:20 UTC, jyeost requested changes

2023-09-07 15:45 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/application/SettingRepository.java
> +@Repository
히잉!!

2023-09-08 03:02 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/setting/application/SettingService.java
> +        setting.ifInactive(() -> activateSetting(member, setting));
이렇게 하면 만약 Active 상태인 ALL 토글을 클릭했을 때
`ifActive` 에서 InActive 상태가 되고
`ifInActive` 에서 다시 Active 상태가 되는거 아닌가요?

2023-09-08 03:08 UTC, This2sho requested changes
고생하셨습니다 여우!
보고 커맨트 몇개 남겼는데 맞는지 확인 한번만 해주세염

2023-09-08 03:08 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/setting/application/activationmanager/DeactivatingSameWeightsManager.java
> +public class DeactivatingSameWeightsManager extends ActivationManager {
얘는 설정을 끄는 친군데 ActivationManger내욤..?!

2023-09-08 03:08 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/setting/application/SettingService.java
> +        setting.ifInactive(() -> activateSetting(member, setting));
이거 Active 상태인 ALL 토글을 클릭하면
`ifActive()` 에서 InActive 상태가 되고
`ifInActive()`에서 Active 상태가 되는거 아닌가욤..?!

2023-09-09 16:01 UTC, jyeost approved these changes
여우 코드 바뀐것들은 확인했습니다 ㅎㅎ 
서비스 로직도 어렵고 그걸 객체지향으로 풀기는 더 어려웠을 것 같은데.. 보고 많이 배웠습니다 !

다만 제가 말씀 드렸던 다른 설정들이 전부 꺼지면 전체 설정도 꺼진다. 이 부분이 바뀐것 같지는 않았어요 
그치만 다른 설정이 꺼지면 전체설정도 굳이 꺼저야하나?? 하는 의문이 들었고 사실 필수적인 것 같지도 않아서 괜찮을 것 같아요 ㅎㅎ 
리뷰가 좀 늦어져서 죄송하고 남은 기능도 열심히 해주시길 바랍니다 !!! 화이팅 입니다 !!!

2023-09-10 03:35 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/application/activationmanager/DeactivatingSameWeightsManager.java
> +public class DeactivatingSameWeightsManager extends ActivationManager {
activation/deactivation을 나눈 기준이 
어떤 설정을 on 한 다음에 진행하는 후처리 작업 -> ActivationManager
어떤 설정을 off 한 다음에 진행하는 후처리 작업 -> DeactivationManager
요렇게 구분한 거에욥! 그래서 ActivationManager 안에 설정을 off하는 작업이 있을 수도 있고 없을 수도 있어용

2023-09-10 03:35 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/setting/application/SettingService.java
> +        setting.ifInactive(() -> activateSetting(member, setting));
고쳤어욥 ㅠ-ㅠ

2023-09-10 06:08 UTC, This2sho approved these changes
수정사항 확인했습니다 여우🦊

고생하셨습니다링 👍

2023-09-10 09:13 UTC, merged