Feat/#375 댓글수 조회 스크랩수 제거
woowacourse-teams/2023-edonymyeon pull request #377
Opened 2023-09-05 15:17 UTC by hectick

## 🔥 연관 이슈

- close: #375 

## 📝 작업 요약

`게시글 상세 조회, 게시글 전체조회, 핫게시글 조회, 검색 결과` 응답 형태에 현재 게시글에 달린 댓글 수가 반영되도록 하였습니다.
스크랩 관련된 변수들(?)은 모두 제거하였습니다.

## 🔎 작업 상세 설명
 - post 패키지에 있는 dto들의 패키지를 좀 나누었습니다.. dto가 넘 많아욥,.
 - ReactionCountResponse에서 scrapCount 제거
 - 게시글 상세 조회 api에서 isScrap 제거
 - commentCount 기존에 0으로 들어가던 것을 수정
    - db에서 게시글을 조회할 때 count쿼리로 같이 조회해오도록 하였습니다만, 엔티티안에 쿼리가 있는 상황에 대해 어떻게 생각하시는지..

## 🌟 리뷰 요구 사항

> 댓글수가 잘 조회되는지, 스크랩 수가 잘 제거되었는지, 제가 빠뜨린 부분은 없는지 확인 부탁드립니다.
댓글수를 조회해오는 더 좋은 방법 있으시면 추천해주세요

2023-09-06 14:53 UTC, jyeost approved these changes
이리내상~~ dto도 깔꼼빠리 하게 정리해주시고 구현도 꼼꼼하게 잘 해주셨네요
미션으로 바쁜 와중에 넘 잘해주신 것 같아서 존.경. 스럽습니다... ㄷㄷ

코드상으로는 큰 문제는 없을것 같아서 어푸로부 합니다 

다만 두가지 의문? 건의? 사항이 있는데염
첫번째는 쿼리 실행 계획 작성해주세염!! 나중에 디비 최적화할때 다시 작성할라면 
헷갈릴 것 같아서여... (함 돌려보는 것조 좋죵)

두번째는 내가 쓴 글 조회에서는 댓글 수와 조회수가 안보여도 되는 가? 에여
저희 뷰에는 둘 다 안나오긴 하지만 내가 쓴 글에서 다른 유저들의 반응을 한 눈에 볼 수 없다면 글 쓰는 재미가 줄어들지 않을까... 하는 노파심이 잇습니다... 흥흥

2023-09-06 14:53 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
> +    @Formula("(select count(*) from comment c where c.post_id = id and c.deleted = false)")
로직이 복잡할 것 같아서 걱정했는데
서브쿼리를 이렇게 구현하는 방법이 있었군요 !
이 필드는 db 에 저장되진 않는 건가요??
싱기하군여...

이렇게 POST <-> Comment 양방향 의존 안생기고, 쿼리도 분리되어 저는 보기 좋은 것 같아요 !

다만 쿼리에서 count(*) 는 1row를 다 읽는 걸로 알고 있어요 !
count(c.id) 처럼 유니크 컬럼만 세어주면 될 것 같아용 ㅎㅅㅎ

2023-09-06 14:53 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/comment/integration/steps/CommentSteps.java
> +    public static ExtractableResponse<Response> 댓글을_생성한다(
이 클래스 내용 IntegrationFixture로 이동해보는 건 어떤가요?

2023-09-06 14:53 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/dto/response/WriterResponse.java
> +public record WriterResponse(String nickName) {
이 클래스 안쓰는 것 같아용~

2023-09-06 14:53 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/dto/response/PostResponse.java
> +public record PostResponse(Long id) {
CreatedPostResponse나 PostIdResponse 가 적절한 것 같아염

2023-09-06 16:24 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/comment/integration/steps/CommentSteps.java
> +    public static ExtractableResponse<Response> 댓글을_생성한다(
죠아욤~

2023-09-07 01:26 UTC, BackFoxx approved these changes
수고하셨어요~~! 새벽에 PR좀 그만 날려요
엔티티 클래스 안에 SQL이 있다면 문제가 있겠지만
JPQL이기 때문에 저는 괜찮다고 생각합니다
전체적으로 문제가 없어 보여서 저는 어프루브 할게요~!

2023-09-07 01:26 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/dto/response/SpecificPostInfoResponse.java
> -                false, // TODO: 스크랩 기능 구현 필요
거슬렸는데 드디어 사라지네요~~ 굿입니당

2023-09-07 01:26 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostReadService.java
> +     */
주석이 생겼군요!! 짱짱

2023-09-07 01:26 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
> +    private int commentCount;
호옹 😮
근데 데이터베이스에서 쓰는 SQL이 아니라 객체끼리의 관계를 나타내는 JPQL이기 때문에
엔티티 클래스 안에 있어도 문제되지 않는다고 생각을 합니당

2023-09-07 02:26 UTC, This2sho requested changes
코드 확인했습니다. 이리내 상 🧀
작성한 코드 확인했고 커맨트 남길게 별로 없네유.
고생하셨슴돠~🙇‍♂️

2023-09-07 05:41 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
전체 게시글조회, 상세 게시글 조회, 핫게시글조회, 게시글 검색 모두 댓글 수가 필요하기 때문에 무조건 조회되도록 해보았습니다~!
댓글수가 필요하지 않은 것은 내가쓴글 조회밖에 없는데, 상대적으로 전체 게시글에 대한 조회가 빈번하게 일어날 것 같아서요~!

2023-09-07 05:48 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
> +    private int commentCount;
JPQL이 아니라 native SQL이라고 하네요 🥲
그래서 RDBMS의 종류를 교체하는 경우 이식성에 안 좋을 수 있다는 점에 유의해야 할 것 같습니다

2023-09-07 06:32 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/post/domain/Post.java
죠습니다.

2023-09-07 06:33 UTC, This2sho approved these changes

2023-09-07 08:41 UTC, merged