Feat/#78 게시글 soft delete
woowacourse-teams/2023-edonymyeon pull request #406
Opened 2023-09-08 12:05 UTC by hectick

## 🔥 연관 이슈

- close: #378 

## 📝 작업 요약

게시글과 게시글 이미지에 soft delete를 도입했습니다.
flyway의 init 파일은 로컬 환경에서 fk 이름 report_ibfk_1가 post_id가 아닌 member_id에 걸리는 것을 확인해서 수정했습니다.
    -> V1.2.2에서 report 테이블에서는, post_id 와 연관된 fk가 드롭되어야 하는데 member_id와 연관된 fk가 드롭되는 상황이 발생
    -> 서버에서는 report_ibfk_1가 post_id에 걸렸고, 잘 드롭되었습니다. 로컬에서 실행할 때 fk가 이상하게 걸리지 않게 하기 위한 수정입니다.

## 🔎 작업 상세 설명

별다른게 없네요

## 🌟 리뷰 요구 사항

> delete 과정이 잘 이루어지는지 검토부탁합니다.

## 추가 논의사항
디스커션에 올려놓았으니 확인해주세요
[Soft delete 정책 논의](https://github.com/woowacourse-teams/2023-edonymyeon/discussions/405)

2023-09-11 04:50 UTC, jyeost approved these changes
굳~~~~ 확인 했씁니다 !!!!
수고 많으셨습니다 ><

2023-09-11 04:50 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +        //todo: 주석 처리된 부분은 이미지를 soft delete 시킬 때, 실제 이미지도 지울 것인가? 입니다.
저는 아직 초기 데이터이니 softdelete로 관리하는 것이 좋다고생각합니다

2023-09-11 04:50 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
>      }
게시글이 삭제되면 이 삭제 아이디가 걸려있는 알람 내역은
물리적 삭제를 해주어야 할 것 같아요 !

2023-09-11 04:50 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java
> +    // todo : 여기 부분 맞게 했나요? 헷갈립니다.
이건 다른 질문인데 이 위에 76 라인 contains로 쓴 이유가 있나요???
postImageInfo 도메인 안에서 비교해 주는 것이 나을 것 같기도.... ????

2023-09-11 04:50 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java
> +    }
헷갈리면 단위테스트를 추가해 보는것은 어떤가염?ㅅ!

2023-09-11 11:18 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
>      }
ㅁㅈㅁㅈ 이게 머지가 얼른 되어줘야 이 기능 구현이 됩니다

2023-09-11 11:40 UTC, BackFoxx approved these changes
수고했어요~~!

2023-09-11 11:40 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/comment/application/PostCommentServiceImpl.java
> +        comments.forEach(Comment::delete);
오 왜 ⸌◦̈⃝⸍ʷʰʸ 수동으로 구현돼있어요?
Spring JPA Repository의 메서드 네이밍으로 만든 delete 메서드 실행하면
이거랑 동일한 방식으로 동작하는 걸로 아는데 아니었나 보네욥
[자료](https://velog.io/@park2348190/JPA의-delete-쿼리-메서드)

2023-09-12 04:39 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java
> +    // todo : 여기 부분 맞게 했나요? 헷갈립니다.
contains는 잘못된 이미지 이름이 들어오는 것도 고려했습니다!
postImageInfo 안으로 집어넣도록 하겠습니당

2023-09-12 06:31 UTC, This2sho requested changes
고생하셨습니다 이리내 🙇‍♂️
삭제할 때, update로 한번 해보시고 의견을 주시죠

2023-09-12 06:31 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/comment/application/PostCommentServiceImpl.java
> +        comments.forEach(Comment::delete);
Repository 단에서 아래 처럼 update로 bulk 연산하면 1번에 처리됩니다리..
```java
@Modifying(clearAutomatically = true)
@Query("update Comment c set c.deleted = true where c.post.id = :postId")
void findDeleteAllByPostId(@Param("postId") Long postId);
```

기존 쿼리: 전체 조회 1번 + 댓글 수 만큼 업데이트 N번-> N + 1
적용시 : update 1번

2023-09-12 06:31 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java
> +    // todo : 여기 부분 맞게 했나요? 헷갈립니다.
넴 문제 없어 보입니다!

2023-09-12 06:31 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +        //todo: 주석 처리된 부분은 이미지를 soft delete 시킬 때, 실제 이미지도 지울 것인가? 입니다.
토론에 댓글 남겼슴돠!

2023-09-12 06:44 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/comment/application/PostCommentServiceImpl.java
> +        comments.forEach(Comment::delete);
좋은데용~

2023-09-12 07:26 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/comment/application/PostCommentServiceImpl.java
> +        comments.forEach(Comment::delete);
이 방법이면 사진들도 soft delete 할때 
```java
@Query("update ImageInfo i set i.deleted = true where i.comment_id in :commentIds")
void findDeleteAllByPostId(@Param("commentIds") List<Long> commentIds);
```
하면 되겠는데용?!

2023-09-12 09:14 UTC, merged