Feat/#407 알림 구현
woowacourse-teams/2023-edonymyeon pull request #408
Opened 2023-09-10 12:26 UTC by BackFoxx

## 🔥 연관 이슈

- close: #407 

## 📝 작업 요약

알림 설정 기능을 만들었으므로,
1. 사용자가 알림을 수신하겠다는 설정을 켜놓은 경우
2. 해당 알림을 실제로 발송하는
기능을 구현했습니다.

## 🔎 작업 상세 설명

발송할 수 있는 알림은 총 4가지입니다.
* 좋아요/싫어요 건당 알림
* 좋아요/싫어요 10건당 알림
* 댓글 알림
* 소비/절약 확정하지 않은 게시글이 있는 경우 오후 8시마다 리마인드

사용자는 설정 페이지에서 위 4가지 알림을 각각 켜거나 끌 수 있고,
**켜져 있는 알림에 한해서만** 실제로 푸시 알림을 전송합니다.

* 'org.awaitility:awaitility:4.2.0' <- 스케줄러의 편리한 테스트를 도와주는 테스트 라이브러리

## 🌟 리뷰 요구 사항

버그 ,, 있을 수 있습니다. 잡아주세요

2023-09-11 06:03 UTC, jyeost approved these changes
테스트도 꼼꼼하게 짜주시고 !!!!
넘 수고 많았습니다.... 역시 대단합니다 여우 !!!!!!

이 pr이 어서 반영되어서 눈으로 보고 싶어요 ....  ><

2023-09-11 06:03 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationServiceTest.java
> +        final Post post = postTestSupport.builder().member(writer).build();
예외 발생 쩌네요 ㄷㄷ :+1

2023-09-11 07:51 UTC, hectick requested changes
여우씌 고생이 많아유~

2023-09-11 07:51 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/member/repository/MemberRepositoryTest.java
> +    }
현재 삭제된 회원도 조회가 됩니다!
```
    @Test
    void 작성한_게시글_중_확정하지_않은_게시글이_있는_사용자를_찾아낸다_탈퇴된_회원은_빼고(
            @Autowired MemberConsumptionService memberConsumptionService
    ) {
        final Member member = memberTestSupport.builder().build();
        final Post post1 = postTestSupport.builder().member(member).build();

        final Member member2 = memberTestSupport.builder().build();
        final Post post2 = postTestSupport.builder().member(member2).build();

        final Member member3 = memberTestSupport.builder().build();
        final Post post3 = postTestSupport.builder().member(member3).build();
        member3.withdraw();

        memberConsumptionService
                .confirmPurchase(new ActiveMemberId(member.getId()), post1.getId(), 4000L, new YearMonthDto(2023, 9));

        final List<Member> members = memberRepository.findAllHavingUnConfirmedPost();

        assertThat(members).containsExactly(member2);
    }
```

2023-09-11 07:51 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationEventListenerTest.java
> +        settingService.toggleSetting(SettingType.NOTIFICATION_PER_THUMBS.getSerialNumber(), new ActiveMemberId(writer.getId()));
여기도 글작성자가 게시글쓰고 탈퇴해도 글작성자에게 알림이 가요!
글 작성자가 탈퇴하는, writer.withdraw(); 추가한 테스트 케이스도 만들어주세욥 (따봉, 댓글 모두 다!)

2023-09-11 07:51 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/member/repository/MemberRepositoryTest.java
> +    }
그리고 케로가 말한, 게시글이 삭제되었을때 알림내역도 이벤트로 삭제하는거? todo 추가해주세욥

2023-09-11 07:51 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationEventListenerTest.java
> +        thumbsService.thumbsUp(new ActiveMemberId(liker.getId()), post.getId());
위에 따봉_저장이_완료된_후에는_알림_발송_후_저장한다 테스트랑 차이가 안보이는데, 제가 못찾는 건가유?

아래처럼 예외 발생하도록 모킹을 해야할 것 같은 느낌이 드는데..
```
doThrow(new BusinessLogicException(NOTIFICATION_REQUEST_FAILED)).when(notificationSender).sendNotification(any(), any());
```

2023-09-11 07:51 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationServiceTest.java
> +        verify(super.notificationSender, never()).sendNotification(any(), any());
super는 왜 붙어있는 것인가요?

2023-09-11 07:51 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +            sendNotification(post.getMember(), ScreenType.POST, post.getId(), THUMBS_PER_10_NOTIFICATION_TITLE);
여기 earrly return 있으면 좋을 것 같아욤

2023-09-11 08:45 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationEventListener.java
> +
비동기를 사용하면 트랜잭션 관련해 문제가 어쩌구저쩌구 해서 안 쓰고 있었는데,
생각해보니 비동기를 사용해 알림을 전송하는 작업 자체가 트랜잭션과 관련이 없네용!
비동기 어노테이션을 사용해 빠르게 구현했읍니다

2023-09-11 12:14 UTC, BackFoxx reviewed
아....ㄱㅐ힘들다,,,,,

2023-09-11 12:14 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationEventListenerTest.java
> +        thumbsService.thumbsUp(new ActiveMemberId(liker.getId()), post.getId());
헉 그러네요 왜 ⸌◦̈⃝⸍ʷʰʸ 빠졌지 .. 추가했습니다

2023-09-11 12:14 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationServiceTest.java
> +        final Post post = postTestSupport.builder().member(writer).build();
굿굿

2023-09-12 06:47 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/comment/domain/Comment.java
> +    }
동의보감

2023-09-12 08:13 UTC, This2sho approved these changes
고생하셨습니다 여우 🦊

2023-09-12 12:27 UTC, hectick approved these changes

2023-09-12 12:29 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +        }
로깅할 필요가 있나요?

2023-09-13 01:58 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +        }
원래 회원이 탈퇴했다면 sendNotification() 호출 이전 게시글 조회 / 댓글 조회같은 작업에서 이미 걸러졌어야 정상인데,
무언가 버그가 있어서 걸러지지 않고 왔다는 뜻이기 때문에 로깅할 필요가 있다고 생각했어요!
적고보니 쫌 더 주의깊게 볼 필요가 있는 로그인 것 같아, info에서 warn으로 레벨을 변경했습니다

2023-09-13 02:04 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/repository/MemberCustomRepositoryImpl.java
> +    public List<Member> findAllHavingUnConfirmedPost() {
넹!

2023-09-13 02:04 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long>, MemberCustomRepository {
넹!

2023-09-13 02:04 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/repository/MemberCustomRepository.java
> +    List<Member> findAllHavingUnConfirmedPost();
원래 JPARepository의 메서드명으로 만드려면 만들 수는 있겠지만
findAllByPost_ConsumptionIsNull 이렇게 의도를 알아보기 힘든 메서드명을 써야 하고
사실 저게 잘 동작하는지도 테스트를 안 해봐서,
커스텀한 리포지토리를 써야 하더라도 조금 더 의도를 쉽게 파악할 수 있는 메서드명을 사용하고 싶었어요

2023-09-13 02:05 UTC, merged