Feat #353 알림기능
woowacourse-teams/2023-edonymyeon pull request #413
Opened 2023-09-11 06:02 UTC by rhkrwngud445

## 🔥 연관 이슈

- close: #353 

## 📝 작업 요약

알림 설정 기능 및 알림을 읽었는지 여부를 서버연동하였습니다!

## 🔎 작업 상세 설명

## 🌟 리뷰 요구 사항

서버요청에 따라 분기가 움직이게 해서 간단하게 처리했어요!

2023-09-11 11:04 UTC, sujin9 requested changes
안녕하세요 코비! 알람이 잘 되어서 기분이 좋네요 ㅎ.ㅎ
고생 많았어요~~

[ 실 기기 테스트 ]
우선 직접 기기 두 대로 알림을 테스트해봤는데요..!
- 인앱 상태에서 알림이 온 경우, notification에 앱 아이콘 및 알림 내용이 뜨지 않아요. 
 => `AlarmService` 클래스에서 `NotificationCompat.Builder` 부분이 알림 내용을 정해주는 부분인데,
 여기서 `message` 대신 `message.notification`을 이용해보세요 :)
 
- 인앱/백드라운드 상황 모두, 알람을 클릭하면 앱 메인화면으로 이동해요.
=> 이 부분은 함께 고민해보죠..!
[ 리뷰 사항]
`AlarmService` 클래스에 토큰 관련 로그를 포함하여 확인이 끝난 로그들은 지우셔도 좋겠어요 :)
그리고 메소드가 길고 역할이 불분명한 것 같아서 분리해주면 더 좋을 것 같아요!

[ 개선 제안 ]
그리고 알림 페이지에서 알림 메시지가 세로로 위에 배치되어 있어서 가운데 정렬해도 괜찮을 것 같아요.
다만 내용이 길어지면 기존처럼 위에 있는 게 나을 것 같기두 해서... 이 부분은 다들 어떻게 생각하시나요!?? 🤔

2023-09-11 11:17 UTC, Choisehyeon approved these changes
코비 알림 구현하느라 고생많았어요!!
comment 남긴 부분은 추후 반영해주시면 될 것 같아요! 
approve 하겠습니다!

인앱/백드라운드 상황 모두, 알람을 클릭하면 앱 메인화면으로 이동해요.
=> 이 부분은 저는 알림화면이나 아니면 작성한 글 상세페이지로 바로 이동하면 좋을 것 같아요!!

[ 개선 제안 ]
그리고 알림 페이지에서 알림 메시지가 세로로 위에 배치되어 있어서 가운데 정렬해도 괜찮을 것 같아요.
다만 내용이 길어지면 기존처럼 위에 있는 게 나을 것 같기두 해서... 이 부분은 다들 어떻게 생각하시나요!?? 
==> 알림이 오는 길이가 정해져 있을 것 같은데 그 길이에 맞게 설정하는게 좋을 것 같아요!! 지금 아직 기획이 확실히 정해진 것 같지 않은 것 같아서 확실히 정해지면 그 때 길이에 맞추는게 어떨까요??

2023-09-11 11:17 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/alarmsetting/AlarmSettingViewModel.kt
> +            preferenceRepository.saveNotificationPreference("0001").onSuccess { response ->
Enum class 사용해도 괜찮지 않을까요??

2023-09-11 11:17 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/alarmsetting/AlarmSettingViewModel.kt
>      }
SwitchEvent와 SwitchClicked 이름이 통일되면 좋을 것 같아요😀

2023-09-11 11:38 UTC, sujin9 requested changes
`AlarmService`에서 
``` kotlin
val intent = when (message.data["navigateTo"].toString()) {
```

`navigateTo` 로 바꿔주면 포그라운드에서 알림 클릭했을 때 이동 잘 되네요 ~

2023-09-11 12:28 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +                navigateToPostDetail(postId, notificationId)
```suggestion
val bundle: Bundle? = intent.extras
if (bundle != null) {
    val postId: Long = bundle.getString(NOTIFICATION_POST_ID)?.toLongOrNull() ?: 0
    val notificationId: Long = bundle.getString(NOTIFICATION_ID)?.toLongOrNull() ?: -1
   navigateToPostDetail(postId, notificationId)
}
```

2023-09-11 12:31 UTC, sujin9 requested changes

2023-09-11 12:31 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +        private const val NOTIFICATION_CLICK_EVENT = "click_action"
!!
```suggestion
        private const val NOTIFICATION_CLICK_EVENT = "navigateTo"
```

2023-09-11 12:34 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +        private const val NOTIFICATION_CLICK_EVENT = "click_action"
AlarmService에서도 사용되고 MainActivity에서도 사용되는데, FCM 관련 상수들을 따로 관리해도 좋을 것 같다는
개인적인 의견을 조심스럽게 얘기해봅니다 :)

2023-09-11 12:37 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +                navigateToPostDetail(postId, notificationId)
안드로이드 공식문서에 Bundle getInt(), getLong()은 아예 없네용!!
[안드로이드 Bundle](https://developer.android.com/reference/android/os/Bundle)

2023-09-11 12:43 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +                navigateToPostDetail(postId, notificationId)
헉 공식문서까지,, 꼼꼼하게 보셨네요 로피! 👍 

코드로는 함수가 떠서 몰랐는데, 
공식문서 상에는 getLong()이 없다니... 신기하네요 😞 

BaseBundle.java
<img width="500" alt="스크린샷 2023-09-11 오후 9 40 17" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/8490058/28c3884a-a165-4200-ae8f-ffa912b355cf">

2023-09-11 12:50 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +                navigateToPostDetail(postId, notificationId)
오오 제가 잘못봤어요😂 공식문서에 inherited Method안에 들어있네요!
그럼 되야하는데 왜 안되는 걸까요..?

2023-09-11 17:07 UTC, rhkrwngud445 commented
일단 버그만 수정해서 푸쉬해 놓았습니다! 미션이 남아있는 관계로..😂 코드 관련한 리팩은 추후에 진행해볼게요!

2023-09-13 06:26 UTC, sujin9 requested changes
이런 ㅠㅠ 미션이 많이 어렵긴 하죠..

다만, 몇 가지 누락된 부분이 있어서 리뷰 다시 남겨요. 수정 부탁드릴게요!

(1)
`MainActivity` > **companion object** 에서
```kotlin
private const val NOTIFICATION_CLICK_EVENT = "click_action"
```
`navigateTo`로 수정해주세요.

(2)
리뷰에 남긴 것처럼, token 등이 노출되지 않도록
배포 전 Log는 지우는 게 좋을 것 같아요.
token이 보이는 Log들은 삭제 부탁드려요.

그 외에는 코멘트로 남겨놨습니다! :)

2023-09-13 06:26 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/data/service/fcm/AlarmService.kt
>              .setContentText(message.data["content"])
```suggestion
.setContentText(message.notification?.body)
```
여기도 수정해주셔야 해요!

2023-09-13 06:26 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/data/service/fcm/AlarmService.kt
>              .setSmallIcon(R.drawable.ic_bottom_nav_alarm_off)
```suggestion
.setSmallIcon(R.mipmap.ic_edonymyeon_round)
```
background에서 오는 알림과 통일이 되고, 어떤 앱에서 온 알람인지 명확하게 하기 위해서
알람 아이콘이 앱 아이콘이면 좋을 것 같아요 :)

2023-09-14 08:50 UTC, sujin9 approved these changes
수정 사항들 잘 반영된거 확인했고 알람도 잘 작동하네요!!
이만 어푸루부 할게요 ~ :)

추가적으로, 다음 업데이트에는 (1)코드 리팩토링과 (2)알람을 읽고 돌아왔을 때 읽음 여부가 반영되도록 (3)알람도 위에서 아래로 스와이프하면 새로고침이 되면 좋을 것 같습니다 ;) 이 부분들은 추후 반영 부탁드려요!

2023-09-14 09:17 UTC, merged