Refactor/#409 session 로그인
woowacourse-teams/2023-edonymyeon pull request #414
Opened 2023-09-11 19:09 UTC by This2sho

## 🔥 연관 이슈

- close: #409 

## 📝 작업 요약

- basic auth 에서 session으로 로그인 방식 변경
- 그에 따른 테스트 코드 수정..
- **이 PR은 안드로이드에서 Session 처리 후 머지 하겠습니다**

## 🔎 작업 상세 설명

basic auth 적용하였습니다.
그로 인한 많은 테스트들의 변경이 있었습니다...
+ RestDocs에서 로그인 시, `Response`에 `Set-Cookie` 헤더로 `JSESSIONID`가 담기는 걸 넣고 싶었으나 MockMvc(가짜 요청)에서 아무리 해도 안되서 포기하였습니다.. 추가로 로그인이 필요한 API에서 이전에는 Request 헤더에 `AUTHORIZATION` 을 명시해줬는데 이 또한 Session이 필요하다는걸 명시하고 싶었지만 방법을 못찾고 포기했습니다.. <- 이 두 방법을 아시는 분이 있다면 가르켜주세요

## 🌟 리뷰 요구 사항

> 커밋 순서대로 보시는걸 추천합니다. (테스트 코드는 노가다라 RestAssured, MockMvc에서 어떻게 로그인 요청을 보내는지 정도만 보시면 될 거 같슴돠)

2023-09-14 00:58 UTC, BackFoxx requested changes
멋지네요 호이~~!!
궁금한 점 몇가지 남겨놓았어욥

2023-09-14 00:58 UTC, BackFoxx commented on backend/src/main/resources/application.properties
> +server.servlet.session.cookie.secure=true
머선 설정인지 주석이 있으면 좋겠읍니다.

2023-09-14 00:58 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/comment/docs/CommentControllerDocsTest.java
> +                .sessionAttr(USER.getSessionId(), 사용자.getId());
오옹 세션을 사용할 때는 sessionAttr를 설정하면 되는군요

2023-09-14 00:58 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/post/integration/PostCommentCountIntegrationTest.java
> +                .sessionId(sessionId)
오옹 RestAssured의 세션아이디 설정은 이렇게 하면 되는군요

2023-09-14 00:58 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/auth/ui/argumentresolver/AuthArgumentResolver.java
> +        if (Objects.isNull(session)) {
[request.getSession()의 실행 전략](https://july1012.tistory.com/entry/getSession-getSessiontrue-getSessionfalse-차이점)을 확인해보셨음 좋겠어요~!
위 코드는 세션이 있으면 가져오고, 없으면 새로 만들어서 가져오기 때문에
이 if문에는 어떤 경우에도 걸리지 않습니다

2023-09-14 00:58 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/auth/ui/argumentresolver/AuthArgumentResolver.java
> +        session.setMaxInactiveInterval(USER.getValidatedTime());
만료기한이 지나면 유효하지 않은 세션으로 판단하는 코드는 따로 추가하지 않아도 괜찮나요?

2023-09-14 02:20 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/ui/SessionConst.java
> +    USER("userId", 30 * 60);
30분 입니다리..! `30 * MINUTES` 로 바꿔놓을게유

2023-09-14 02:22 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/ui/argumentresolver/AuthArgumentResolver.java
> +        if (Objects.isNull(session)) {
오홍 기본이 true인가 보군요..!

2023-09-14 03:03 UTC, hectick requested changes
테스트가 session으로 변경되면서 dev와 충돌이 꽤 생기는 것 같네요.
어서 pull 받아서 다시 올려주세요~~

2023-09-14 03:03 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/auth/docs/AuthControllerDocsTest.java
> +                requestFields(로그인_요청_파라미터)
뭔가 header에 Set-Cookie가 들어간다는 것을 문서화하면 좋을 것 같은데, 찾아보니 이것은 톰캣측에서 해줘가지고 mockmvc 테스트로는 헤더가 아직 생성이 안되는 것 같네유.. 
그리고 문서화하는 내용이 변경되었으니 docs 폴더 안의 authentication-api.adoc 에서 response-headers 문서화하는 부분도 제거해주세용 ~

2023-09-14 04:13 UTC, jyeost approved these changes
화긴햇습니다 ~~~ !

2023-09-14 04:13 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/auth/ui/argumentresolver/AuthArgumentResolver.java
> +        session.setMaxInactiveInterval(USER.getValidatedTime());
그르게여... 만료기간이 지나면 expired 하고, 지나지 않으면 refresh하는 로직이여야 할 것 같아여

2023-09-16 10:14 UTC, This2sho commented on backend/src/main/resources/application.properties
> +server.servlet.session.cookie.secure=true
> 두 설정 모두 세션 쿠키에 대한 보안 관련 설정인데
server.servlet.session.cookie.same-site=none
: 모든 요청에서 Cookie 전송 가능
server.servlet.session.cookie.secure=true
: Https 요청일 때만 쿠키를 보내겠다는 옵션.

Https만 사용해서 보안을 강화하는 옵션인줄 알았으나, Chrome의 문제를 해결하기 위한 옵션인거 같습니다.
안드로이드와 통신할 때는 굳이 필요없는 거 같아 삭제하도록 하겠슴다!

2023-09-17 09:07 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/ui/argumentresolver/AuthArgumentResolver.java
> +        session.setMaxInactiveInterval(USER.getValidatedTime());
session에서 설정 시간이 지나면 WAS가 내부적으로 세션을 삭제한데유

2023-09-17 09:12 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/ui/argumentresolver/AuthArgumentResolver.java
> +    }
원래 `Objects.requireNonNull(parameter.getParameterAnnotation(AuthPrincipal.class)).required()` 이렇게 되어있었는데 너무 길이서 메소드로 추출했습니다.

2023-09-17 09:14 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/auth/ui/argumentresolver/AuthArgumentResolver.java
> +    }
로직이 사용되는 건 Controller 인자에 `@Authprincipal`가 있는지 확인하고
해당 `@Authprincipal`의 `required` 값이 `true`인지 `false`인지 확인해서
`true`인데 인증 정보가 없으면 예외, `false`이면 `AnonymousMemberId`를..

2023-09-17 10:00 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/auth/ui/argumentresolver/AuthArgumentResolver.java
> +    }
오홍. 이미 argumentResolver에서 AuthPrincipal 어노테이션이 있는 것만 받기에, requrieNonNull이 왜 필요한가 궁금했던 것인데, 인텔리제이가 nullPointerException이 뜰 수 있다구 경고를 하는군여..

2023-09-17 12:47 UTC, hectick approved these changes
고생하셨습니다 호이씨.

dev 풀 받고나서 테스트 코드에 남아있는 basic auth 레거시들도 잘 처리 부탁드립니다용

2023-09-18 04:02 UTC, BackFoxx approved these changes
수고하셨습니다~! 풀 한번 하신 후 머지해주세욥

2023-09-18 06:16 UTC, merged