#427 알림 버그 해결하기(4가지)
woowacourse-teams/2023-edonymyeon pull request #430
Opened 2023-09-14 06:15 UTC by BackFoxx

## 🔥 연관 이슈

- close: #427 

## 📝 작업 요약

수행한 작업을 1~2줄 사이로 요약해주세요.

## 🔎 작업 상세 설명

* [ ] 내가 작성한 게시글에 내가 댓글을 남겨도 알림이 간다
* [ ] 소비/절약 확정이 완료된 게시글은 좋아요 알림을 안 받게 하자
* [ ] 로그아웃해도 알림이 간다
* [ ] 회원탈퇴 후에도 DB에 알림 발송 기록이 쌓인다

다른 디바이스로 로그인하면 나머지 디바이스는 로그아웃 시켜주자 -> 호이의 세션 로그인 PR이 머지된 이후 구현 가능
리마인드 알림이 가지 않는다 -> 오후 8시 이후 구현 가능
게시글 작성일로부터 4주 미만인 게시글만 리마인드 알림을 발송한다 -> 오후 8시 이후 구현 가능

## 🌟 리뷰 요구 사항

> 버그 별로 커밋을 수행하였으니
커밋별로 분리해서 봐주시면 될 것 같습니다~!

2023-09-14 08:27 UTC, hectick requested changes
고생하십니다,,

알림 기능은 실제 앱을 써보면서 버그를 찾아야해서 번거롭군용,,

2023-09-14 08:27 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +        if (memberConsumptionService.isPostConfirmed(post.getId())) {
isPostConfirmed 메서드를 memberConsumptionService 안에 두는 것은 조금 위험해 보여요.
아까 여우가 언급했던, 소비확정/절약확정 부분이 member 패키지에서 consumption 패키지로 이사를 가게 된다면, 이 인터페이스와 구현체는 통째로 사라지게 되는데, 이 메서드도 다른 클래스로 이사를 하게 되고, 지금 클래스까지 영향을 받게 될 것 같아요.

ConsumptionRepository를 직접 이용하거나,
isPostConfirmed 메서드를 ConsumptionService로 위치를 이동시키는 것,
둘 중 하나를 고르는게 어떤가요?

2023-09-14 08:27 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
>              log.warn("탈퇴한 회원에 대한 알림 전송 시도입니다.");
여기 로그 지워도 될 것 같아요.
현재 탈퇴한 회원들의 게시글까지 앱에 노출되고 있는데,
그런 게시글에 댓글/추천 비추천이 달릴때마다 warn 로그를 찍을 필요는 없을 것 같아요

2023-09-14 15:46 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +        if (memberConsumptionService.isPostConfirmed(post.getId())) {
쓰면서도 계속 갑갑했던 부분인데 ....
낮에 넌지시 했던 이야기를 기억하고 있었군요 이리내 진자 이럴때 진짜 대박멋있다.............
ConsumptionService로 옮겼더니 자연스러워졌네요!

2023-09-15 06:17 UTC, jyeost requested changes

2023-09-15 07:14 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
>          }
하지만 좋아요 등록 / 댓글 작성 후 발행한 이벤트를 소비하는 용도가 알림 뿐이 아닐 수도 있어요!
예를 들어 댓글을 남긴 후 발행한 SavedCommentEvent를 지금은 NotificationService에서만 감지해 사용하고 있지만
댓글에 사용한 사진을 복제용 DB에 복사하는 작업이라던가
댓글 정보를 이용한 통계 쿼리를 실행하는 작업을 실행하기 위해 SavedCommentEvent를 소비할 수도 있습니다.

이를 감안했을 때, 서비스 쪽에서 이벤트 발행 이전에 
알림 도메인에만 적용되는 제약사항을 걸어두는 건 
확장성 면에서 좋지 않다고 판단합니다 😮

2023-09-16 04:04 UTC, hectick approved these changes
변경된 부분 확인해서 어푸루부 합니다!

아래 두개 기능은 아직 구현이 안된 것이지요?!?
다른 디바이스로 로그인하면 나머지 디바이스는 로그아웃 시켜주자 -> 호이의 세션 로그인 PR이 머지된 이후 구현 가능
게시글 작성일로부터 4주 미만인 게시글만 리마인드 알림을 발송한다 -> 오후 8시 이후 구현 가능

2023-09-16 13:34 UTC, hectick approved these changes

2023-09-16 13:34 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/member/repository/MemberCustomRepository.java
> +    List<Member> findAllHavingUnConfirmedPostWithInDays(int days);
UnConfirmed -> Unconfirmed

2023-09-18 04:26 UTC, jyeost approved these changes

2023-09-18 05:36 UTC, merged