Feat/#53 회원 정보 수정
woowacourse-teams/2023-edonymyeon pull request #432
Opened 2023-09-14 09:05 UTC by This2sho

## 🔥 연관 이슈

- close: #53

## 📝 작업 요약

- 회원 정보 수정하는 기능 구현
- API 작성

## 🔎 작업 상세 설명

별거 없슴돠. 회원 정보 수정이에요
이미지 업로드 하는 부분을 같이 개선할려고 했는데 이건 따로 파서 해야될거 같네유
(+ 회원 정보 수정을 `PUT` 으로 했는데, `PUT` 에 MultiPartFile 업로드를 처리하면 안된다~라는 [글](https://blog.outsider.ne.kr/1001)이 있긴한데 어떻게 하는게 좋을까염?

## 🌟 리뷰 요구 사항

> 업데이트 할 때 생각하지 못한 오류 찾아주세염

2023-09-16 04:39 UTC, hectick requested changes
호이씨 회원정보 수정하는 테스트 코드도 추가좀 해주세여

> 이미지 업로드 하는 부분을 같이 개선할려고 했는데 이건 따로 파서 해야될거 같네유
> (+ 회원 정보 수정을 PUT 으로 했는데, PUT 에 MultiPartFile 업로드를 처리하면 안된다~라는 [글](https://blog.outsider.ne.kr/1001)이 있긴한데 어떻게 하는게 좋을까염?

저 글은 브라우저를 통해 PUT으로 보냈는데 자꾸 PUT으로 처리를 못하고 POST로 받는 것이 문제상황 아닌가요? (아니라면 정정해주세여)
현재 게시글 수정에는 PUT 메서드로 multipartFile 파일을 잘 받고 있는데, 프로필 이미지 수정도 PUT으로 가도 괜찮지 않을까욥..?

그리고 현재 호이가 올린 글에서 문제가 되었던 CommonsMuiltipartResolver는 더이상 지원되지 않고 StandardMultipartResolver를 이용하는 것 같습니다.
https://ryumodrn.tistory.com/140

찾아보니 POST 하드코딩하는 부분이 없네요
<img width="816" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/62106852/ba770ac6-1cb2-42a1-8a5e-b2533653033a">

2023-09-16 04:39 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +                memberRepository.findByNickname(updateNickname).isPresent()) {
레포지토리에서 닉네임으로 찾아와서 isPresent를 체크해주는 것보다는 memberRepository.existsByNickname(updateNickname)을 쓰는 것은 어떤가요

2023-09-16 04:39 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +            throw new EdonymyeonException(MEMBER_NICKNAME_INVALID);
현재 문구가 "회원 닉네임이 잘못되었습니다"인데,
"이미 존재하는 닉네임입니다"라는 정보를 담는 enum을 추가해주는 것은 어떤가요

2023-09-16 04:39 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +            return new MemberUpdateResponse(member.getId());
이미지가 없으면 member에서 이미지를 없애주어야하지 않을까요?
또, 현재 코드는 닉네임을 바꾸고, 이미지가 없는 요청이 들어오면 **이미지가 없어지지도 않고, 닉네임도 못 바꿔주는걸요**🧐

2023-09-17 11:34 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +            return new MemberUpdateResponse(member.getId());
1. 이미지만 바꾸는 경우
```
이미지 : 바꿀 이미지
닉네임 :
```
2. 닉네임만 바꾸는 경우
```
이미지 :
닉네임 : 바꿀 닉네임
```
3. 모두 바꾸는 경우
```
이미지 : 바꿀 이미지
닉네임 : 바꿀 닉네임
```

위에 3가지 경우만 생각하고 구현했는데, 일단 위에서 닉네임을 업데이트해주고 반환했어야 됐네여..
그리고 프로필 이미지를 아예 삭제하는 경우도 고려해야겠네여...

2023-09-17 11:55 UTC, This2sho commented
> 저 글은 브라우저를 통해 PUT으로 보냈는데 자꾸 PUT으로 처리를 못하고 POST로 받는 것이 문제상황 아닌가요?

**"API를 설계할 때, 데이터와 파일을 함께 보내는 API가 바람직하지 않다."** 가 문제 상황이였습니다. 

조금 더 자세한 설명이 있는 글이 있어서 첨부합니다.
https://mangkyu.tistory.com/218

2023-09-17 12:39 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +            return new MemberUpdateResponse(member.getId());
이부분은 추후 안드로이드와 api 협의가 이루어져야겠네요
기존 이미지가 유지될땐 어떻게 알려줄지, 삭제만될땐 어떻게 알려줄지 등등..

2023-10-07 14:07 UTC, BackFoxx reviewed
리뷰가 심각하게 늦어져 정말 면목없습니다 호이 ..
사과의 의미로 지금까지의 API 변경으로 인해 일어난 conflict는 제가 해결해 두었습니다

그런데 지금 서버쪽에서 구현된 API가
<img width="627" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/95093193/7f0d0aec-2bbb-4ed2-84ef-05c74f91350a">
이거랑 형태가 다른데, 아직 협의가 완료되지 않아서 그런거죠?

2023-10-11 01:45 UTC, This2sho commented
# API 변경된거 반영

이번에 하면서 프로필 이미지 저장하는 로직(파일 쓰기 or S3)이 오래 걸린다고 생각해서 비동기로 빼보고 싶었는데

비동기를 사용하면 트랜잭션이 분리가 되는데 이미지 저장 결과(성공/ 실패)가 나오고 디비에 쓰는거라 비동기로 빼기가 어렵더라고여..

조금 더 오래걸릴 거 같아서 API 수정된거만 반영해서 PUSH 했습니다..!

+ 추가로.. 하면서 `Member`에 기능들이 점점 많아지는 거 같아서 
기존에 사용하던 nickname, password 등을 값 객체로 변경해보는거 어떨까요?

2023-10-11 08:55 UTC, This2sho commented
회원 프로필 사용하는 Response 동작하도록 변경했습니다.

2023-10-12 11:41 UTC, hectick approved these changes
호이씨 빨리 마지해주시죠

nickname, password 값 객체는 좋습니다

2023-10-12 11:41 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/image/ImageFileUploader.java
> +            throw new EdonymyeonException(IMAGE_UPLOAD_FAIL);
EdonymyeonException 아니구 BusinessLogicException 아닐까욤

2023-10-12 11:41 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/support/MockMultipartFileTestSupport.java
>                      "newImages",
이거 buildImageForPost()라 한 이유가
form data로 들어오는 필드 이름이 newImages이라서(게시글 전용 필드) 그랬던거거덩요
물론 현재는 ServiceTest에서만 사용중이라 필드 이름이 이상해도 잘 돌아가는 것 같긴 하지만
CommentControllerDocsTest, MemberControllerDocsTest 등등 에서는 이 builder를 쓰면 오류가 나거든요 필드명이 일치하지 않기 때문에.. (그래서 거기서는 new 생성자로 생성하고 있읍니다)
buildImageForPost를 유지하고 필요하다면 따로 buildImageForProfile 메서드를 만들어 사용하는게 어떨까요?

다음은 MemberControllerDocsTest입니다
<img width="929" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/62106852/6ef2921d-2165-4ea3-aa59-31926fdad029">

2023-10-13 06:25 UTC, hectick requested changes

2023-10-13 06:25 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/member/ui/MemberController.java
> +
버전 2로 바꿔야 함

2023-10-13 06:26 UTC, hectick requested changes

2023-10-13 06:26 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/member/application/dto/response/MyPageResponse.java
> +public record MyPageResponse(Long id, String nickname, String profileImage) {
기존 버전 1
새로운거 버전2
dto 각각 만들어야 함

2023-10-16 10:52 UTC, This2sho commented
- API 버전 대응하도록 적용했습니다.
- 테스트용 MockMultipartFile Post용, Profile용 분리했습니다.
- Docs에도 버전 적어줬습니다..

DTO 하나 바꼈는데.. 파일이 47개 바뀌네요..
API 버전을 올리고 파일 변경을 최소할 좋은 방법이 있다면 같이 얘기해보시죱

2023-10-16 11:05 UTC, This2sho commented
- API 버전 대응하도록 적용했습니다.
- 테스트용 MockMultipartFile Post용, Profile용 분리했습니다.
- Docs에도 버전 적어줬습니다..

DTO 하나 바꼈는데.. 파일이 47개 바뀌네요..
API 버전을 올리고 파일 변경을 최소할 좋은 방법이 있다면 같이 얘기해보시죱

2023-10-16 16:00 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/member/repository/MemberRepository.java
> +    Optional<Member> findByNickname(String nickname);
findByNickname() 지워주는 것이 어떤가염??

2023-10-16 16:06 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/member/integration/MemberIntegrationTest.java
> +        final MyPageResponseV2 myPageResponseV2 = response.as(MyPageResponseV2.class);
요청은 version1 인데 응답은 2네여....

2023-10-16 16:15 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/member/docs/MemberControllerDocsTest.java
> +        final RestDocumentationResultHandler 문서화 = document("profile",
문서에 V1 V2 둘다 이름이 `profile`이라서 V2만 떠여....

2023-10-17 01:04 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
>      }
앗.. 그렇네여 👍

2023-10-17 01:36 UTC, hectick approved these changes
이 장기간 PR을 드디어 끝내는군요
고생하셧읍니다 호이씨

2023-10-17 01:36 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/member/docs/MemberControllerDocsTest.java
> +        final RestDocumentationResultHandler 문서화 = document("profile",
그러게욤 문서에 버전1 회원정보 조회가 안보이네욤

2023-10-17 01:36 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/member/ui/MemberController.java
> +    @GetMapping("/members/check")
다른건 다 profile인데 얘는 members인것도 좀 킹받네요

2023-10-17 01:36 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/image/ImageFileUploader.java
> +            throw new BusinessLogicException(IMAGE_UPLOAD_FAIL);
린네상 runtimeException도 BusinnessLogicException으로 바꿀 예정임돠
이거 그대로 갖다 붙이면 되겟네욤

2023-10-17 01:38 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +        member.updateMember(updateRequest.nickname(), member.getProfileImageInfo());
저도 Member에 정보 수정하는 메서드를 어떻게 할 지 고민을 많이 했는데..
1. 여러 메서드를 통해 하나씩 변경 (Setter 처럼)
2. 하나의 메서드로 한번에 변경

정보 수정에 변경이 생기면 코드에 영향이 얼마나 미칠까 생각했을 때
1번의 경우, 도메인에 메소드 추가 + 서비스 변경
2번의 경우, 도메인에 메소드 파라미터 추가 + 서비스 변경

2번이 파라미터 추가로 조금 덜 변경한다. 로 생각했습니다.. (사실 변경될게 별거 없어서 의미 없을 지도)

그리고 추가로 고려한게 회원 정보 수정이 `PUT`이라 변경사항을 고려하지 않아도 되서 2번으로 구현했습니다..

@BackFoxx , @hectick 생각도 궁금하네염

2023-10-17 01:46 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/ui/MemberController.java
> +    @GetMapping("/members/check")
핳.. GET 메소드 -> 해당 리소스의 정보를 가져온다..
하지만, 이렇게하면 "/members/nickname" 헤더에 회원 정보가 있다면 "hoy" 이런 정보가 반환 값으로 주는게 맞겠져
근데 이게 회원의 정보를 가져온다기보다 "회원들 중에 해당 닉네임 또는 이메일을 가진 회원이 있느냐?" 라고 생각해서
/members/ `check` 동사형을 사용했습니다..

더 좋은 URI 가 있다면 추천해주세염

2023-10-17 02:44 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/member/integration/MemberIntegrationTest.java
> +        final MyPageResponseV2 myPageResponseV2 = response.as(MyPageResponseV2.class);
앗..! 😅 수

2023-10-17 04:36 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/member/ui/MemberController.java
> +    @GetMapping("/members/check")
checkDuplicate 라던지...

2023-10-17 04:41 UTC, jyeost commented on backend/build.gradle
> -
의존성 추가보다 이쫏이 관리하기 좋을 것 같네여... dev에만 설정하면 되니까...

2023-10-17 07:53 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/ui/MemberController.java
> +    @GetMapping("/members/check")
그게 더 좋네염

2023-10-17 07:54 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/ui/MemberController.java
> +    @GetMapping("/members/check")
하티랑 말해보고 된다고 하면 바꿀게염

2023-10-17 07:59 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/member/docs/MemberControllerDocsTest.java
> +        final RestDocumentationResultHandler 문서화 = document("profile",
앗 그렇네요 반영하겠습니댜 👍

2023-10-17 08:11 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/ui/MemberController.java
> +    @GetMapping("/members/check")
`/profile/check-duplicate` 로 반영했슴돠

2023-10-17 08:11 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/image/ImageFileUploader.java
> +    public ImageInfo from(final MultipartFile multipartFile) {
이름은 정팩매처럼 지어져 있는데 static은 없네요 🥸신기한 형태로다 의도하신 겁니까?

2023-10-17 08:24 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +        member.updateMember(updateRequest.nickname(), member.getProfileImageInfo());
여기서 profileImage의 null 여부를 검사해서 null이 아닌 경우 updateWithProfileImage를 실행하고,
updateWithProfileImage는 private로 감추고
회원 정보 업데이트 API는 하나만 호출할 수 있도록 선택지를 줄여주는 건 어떤가요?

2023-10-17 08:27 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +        member.updateMember(updateRequest.nickname(), member.getProfileImageInfo());
왜냐면 이미지 정보가 없는 MemberUpdateRequest를 가지고 updateWithProfileImage를 호출하면 NPE가 발생할 가능성이 높은데, NPE 가능성을 다루는 코드가 updateWithProfileImage 안에 따로 없어서요.

2023-10-17 08:38 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +        member.updateMember(updateRequest.nickname(), member.getProfileImageInfo());
저는 1번이요!! 프로필 이미지 정보를 더이상 회원 도메인에서 관리하지 않게 될 때 updateMember() 메서드를 수정하게 될텐데, 이 때 프로필 사진을 수정하지 않고 닉네임만 수정하는 사용자들의 코드에도 변경의 영향이 갈 수 있으므로
수정하는 정보에 따라 메서드를 잘게 나누는 것이 단일 책임 원칙에 적합한 설계가 아닐까 생각을 합니다.

하나의 메서드만을 사용하더라도 변경에 유연하게 설계하고 싶다면
파라미터로 저렇게 닉네임과 프로필사진 정보를 나열하기 보다,
파라미터로 Map을 넣고 Map의 키로 닉네임과 프로필사진정보를 담도록 설계하면 좀 더 유연하지 않을까 생각하는데

이건 또 호이 입장에서는 조금 귀찮을 수 있겠네요. 아직 닉네임이 VO로 분리되지도 않았고,,
호이짱이 마음가는 대로 해주시면 될 것 같습니다

2023-10-17 08:51 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +        member.updateMember(updateRequest.nickname(), member.getProfileImageInfo());
아 updateMember()에서 이미 해주고 있네..? public으로 되어있어서 API인 줄 알았당
내부적으로 호출되는 메서드들인데 왜 ⸌◦̈⃝⸍ʷʰʸ private가 아니라 public으로 되어있어요?

2023-10-17 08:53 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/member/application/MemberServiceTest.java
> +    void 닉네임만_변경되는_경우() {
이 메서드들을 호출해서 나가는 쿼리를 다시 천천히 보시고
뭔가 잘못됐음을 느꼈다면 그 이유를 [이 블로그](https://velog.io/@backfox/김춘배와-알아보는-Transactional-이모저모-1-테스트코드)를 참고해 알아내보세요~

2023-10-17 11:35 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/image/domain/Domain.java
> +        }
메소드 안에 null 체크 로직이 있어서 `@nullable` 어노테이션을 사용해보겠습니다 👍

2023-10-17 11:39 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/image/ImageFileUploader.java
> +    public ImageInfo from(final MultipartFile multipartFile) {
이 부분은 이미지를 실제 저장하는 부분과 DB에 저장하는 데이터를 분리할려고 만들었는데..
메소드 명을 멀로 할지 몰라서 일단 하나의 인자를 변경해주는 `from`으로 만들었습니다.
`from` 이라는 메소드 명은 정팩메에만 써야하는 걸 까 요 ? ! 🧐

2023-10-17 11:52 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +        member.updateMember(updateRequest.nickname(), member.getProfileImageInfo());
Member의 변경이 일어나서 `@Transactional` 어노테이션을 붙여줬고
public으로 선언한 이유는 `@Transactional` 이 프록시 패턴을 사용하여 
`MeberService` interface를 만들 때 `updateWithoutProfileImage`이 public이여야 `TxMemberService`도 구현할 수 있기 때문으로 알고있스므니다.

2023-10-17 12:20 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/member/application/MemberServiceTest.java
> +    void 닉네임만_변경되는_경우() {
오홍.. 저는 테스트 메서드에서 `@Transactional`을 붙혀서 `Repository`에서 회원을 다시 조회 해오지 않고 
검증하려고 사용했는데...(아래 회원 정보 수정 경우들은 이미지 삭제를 비동기로 처리해서 `@Transactional`을 안썼었습니다..큐큐)

저 멋쟁이 블로그에 의하면 **개발자의 실수를 바로바로 인식해 잡아내는 것이 테스트 코드의 역할인데도
테스트 레이어에서 생성된 트랜잭션에 의해 실제 버그가 가려진다.** 가 핵심이네요 👍

의식해서 `flush`를 하는 것도 괜찮겠지만. .이 또한 실수할 수 있으니 `@Transactional` 어노테이션은 깔끔하게 삭제하겠습니다

좋은 블로그 공유 감사합니다 멋쟁이 여우씨 👍 (다음에도 부탁드려요 😉)

2023-10-17 12:39 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/member/application/MemberServiceTest.java
> +    void 닉네임만_변경되는_경우() {
피드백 바로바로 반영해주는 멋쟁이 호이씌~~~

2023-10-17 13:50 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
> +        member.updateMember(updateRequest.nickname(), member.getProfileImageInfo());
public일 필요가 없는 메서드였네염;;

2023-10-17 14:28 UTC, BackFoxx approved these changes
험난한 여정을 통과한 당신~! 어프루브 하나 드립니다~

2023-10-17 18:07 UTC, merged