Feat/#446 뒤로가기 두번 앱종료
woowacourse-teams/2023-edonymyeon pull request #447
Opened 2023-09-16 18:48 UTC by sujin9

## 🔥 연관 이슈

- close: #446 

## 📝 작업 요약

뒤로가기를 연속으로(짧은 시간 내에) 두 번 하면 앱이 종료되도록 구현하였습니다.

## 🔎 작업 상세 설명

말 그대로, 뒤로가기를 두 번 해야 앱이 종료됩니다.
`onBackPressed()`가 deprecated 되어서, [onBackPressedDispatcher](https://developer.android.com/reference/androidx/activity/OnBackPressedDispatcher)를 이용하여 구현했습니다.

더불어, MainActivity 리팩토링도 진행했는데..
- 함수를 호출 순서로 정렬했고,
- observe 부분 함수로 분리했어요.

이 부분 리팩토링 이슈를 새로 파서 했어야 할 것을.... 미안합니다. 😢 

## 🌟 리뷰 요구 사항

> 리뷰는, 기능이 간단하고 코드 변화가 많지 않아 간단하게 빨리 할 수 있을 것 같습니다.

우선 이 기능을 구현한 이유는,
최근 안드로이드가 물리적 백버튼이 없어지는 추세에 소프트웨어 백 버튼을 이용할 수 있게 제공하고 있고,
저 역시도 안드로이드지만 ios처럼 스와이프 제스처를 이용한 백 기능을 이용 중이에요.
다만 (1) 물리적 백 버튼을 사용할 때보다 실수로 앱이 꺼지는 빈도가 높아져서 이를 방지하고 싶었고,
(2) 이러한 기능이 있으면 좋겠다는 피드백을 받았던 게 떠올라 구현하게 되었습니다.

그래서 얘기하고 싶은 게 뭐냐면요.. **몇 가지 여러분의 의견이 궁금해요 !** 
1. 구현하기 전에 논의를 했어야 했는데... 이 기능이 필요한 기능일지, 없는 게 나을지 여러분의 의견이 궁금합니다.
(참고로, 다른 앱들 중 해당 기능이 있는 앱은 반 정도 되는 것 같네요 🤔)
2. 소프트웨어 백 기능을 사용하는 경우, 현재의 snackbar 메시지가 적절한 지도 모르겠네요 ㅠ.ㅠ

2023-09-17 05:26 UTC, Choisehyeon requested changes
메인 액티비티에서 물리적 백버튼을 실수로 잘못 눌러서 앱이 종료되는 걸 방지하기 위함인거죠?
물리적 백버튼을 사용하기 보다는 소프트웨어 백버튼을 사용하기를 원하면 물리적 백버튼을 막는 방법도 있을 것 같은데 물리적 백버튼이 있는데 눌리지 않는 것 보다 하티 방법처럼 하는게 좋아보이긴 하네용😄
문구는 뒤로 버튼 보다 뒤로가기 버튼은 어떨까요??

2023-09-17 05:26 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +            if (System.currentTimeMillis() - backClickedTime >= 1500) {
이 1500이라는 숫자는 어떻게 정하게 된건가요??🧐
1500이라는 숫자가 무엇을 의미하는지 알기 어려울 수도 있을 것 같아서 상수화하는 건 어떨까요😊

2023-09-30 06:39 UTC, sujin9 commented
> 메인 액티비티에서 물리적 백버튼을 실수로 잘못 눌러서 앱이 종료되는 걸 방지하기 위함인거죠?
물리적 백버튼을 사용하기 보다는 소프트웨어 백버튼을 사용하기를 원하면 물리적 백버튼을 막는 방법도 있을 것 같은데
물리적 백버튼이 있는데 눌리지 않는 것 보다 하티 방법처럼 하는게 좋아보이긴 하네용😄😄

정확히는, 물리적 백버튼이 최근 스마트폰들에서는 많이 보이지 않아서요
최근 안드로이드 폰의 경우,
스크린 하단에 물리적 백버튼이 보이거나 vs 아이폰처럼 스와이프 백을 할 수 있도록 선택해서 설정 가능한 경우가 대부분이에요.
그래서 정확히는, 물리적 백버튼이든 스와이프 백이든 잘못 눌러서 바로 나가지지 않도록 하면 어떨까~ 라는 의미였습니다.

> 문구는 뒤로 버튼 보다 뒤로가기 버튼은 어떨까요??
그게 더 직관적일 것 같네요! :)

2023-09-30 06:39 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +            if (System.currentTimeMillis() - backClickedTime >= 1500) {
오 좋아요!! 👍

2023-10-04 08:15 UTC, Choisehyeon approved these changes
하티 리뷰 반영한거 확인했어요👍
이만 approve 하겠습니돠!!

2023-10-04 08:43 UTC, rhkrwngud445 approved these changes
고생많았어요! 제안 하나 드렸는데, 괜찮으시면 반영해주세요~!

2023-10-04 08:43 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +        this.onBackPressedDispatcher.addCallback(this, backPressedCallback)
this를 명시한 이유가 있을까요?!🤔

2023-10-04 08:43 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +        this.onBackPressedDispatcher.addCallback(this, backPressedCallback)
```suggestion
    private fun setOnBackCallback() {
        var backClickedTime = 0L
        
        this.onBackPressedDispatcher.addCallback(
            this,
            object : OnBackPressedCallback(true) {
                override fun handleOnBackPressed() {
                    if (System.currentTimeMillis() - backClickedTime >= FINISHING_APP_TIME) {
                        backClickedTime = System.currentTimeMillis()
                        binding.root.makeSnackbar(getString(R.string.main_ask_back_click))
                    } else {
                        finish()
                    }
                }
            },
        )
```

이렇게 멤버변수 수를 줄이는 건 어떨까요?!

2023-10-05 09:31 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +        this.onBackPressedDispatcher.addCallback(this, backPressedCallback)
앗,, 아뇨 큰 이유는 없었습니다 😅 
굳이 필요가 없는 부분이었네요!

2023-10-05 09:34 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
> +        this.onBackPressedDispatcher.addCallback(this, backPressedCallback)
depth가 너무 깊어지지 않을까 고민했어요 🤔 
다만, 저 callback은 해당 함수에서만 쓰이기 때문에 멤버변수 수를 줄이고 제안해주신 것처럼 표현하면 
코드를 전체적으로 읽을 때 좀 더 가독성 측면에서 좋을 것 같기도 하네요!

2023-10-05 09:40 UTC, merged