Refactor 461 alarm
woowacourse-teams/2023-edonymyeon pull request #467
Opened 2023-09-27 09:18 UTC by rhkrwngud445

## 🔥 연관 이슈

- close: #461 

## 📝 작업 요약

알람 포그라운드 버그 수정 및 함수 분리

## 🔎 작업 상세 설명

## 🌟 리뷰 요구 사항

> 5분이면 충분합니다

2023-09-30 08:44 UTC, sujin9 requested changes
안녕하세요 코비! :)
함수 분리가 되니 보기 더 편해져서 좋네요 :)

다만, 한 가지 체크 부탁드려요.
앱을 실행 중인 상태에서, 게시글 A와 B 순서대로 추천 반응을 남기면 알람 두 개가 와요
이 알람 두 개를 눌러보면 둘 다 게시글 B로 이동합니다.
코비도 이 부분 한 번 테스트해보시고 확인해주시면 좋겠네요 :)
(저는 API 33 버전에서 테스트 진행했습니다)

2023-09-30 08:44 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/data/service/fcm/AlarmService.kt
>          super.onNewToken(token)
`onNewToken`을 override 해준 이유는 무엇인가요?

2023-09-30 08:44 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/login/LoginViewModel.kt
> +        Log.d("this", "1")
안 쓰는 로그는 삭제해주세요 :)

2023-09-30 10:44 UTC, sujin9 requested changes

2023-09-30 10:44 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/data/service/fcm/AlarmService.kt
> +            0,
```suggestion
            System.currentTimeMillis().toInt(),
```

pendingIntent에 들어가는 requestCode는 다른 PendingIntent와 구별하기 위해 사용되는, 마치 `고유값`과 같은 개념이에요. 
동일한 requestCode 가 같은 경우에는 마지막 PendingIntent 로 치환됩니다.
그래서 requestCode에 다른 값이 들어가도록 하여 구분을 지어보니,
리뷰에 남겨드렸던 문제가 해결되는 것 같아요. 
(이 부분도 반영해서 코비의 환경에서도 잘 동작하는지 테스트 한 번 해주세요!)

requestCode를 저는 다음과 같이 코드 수정을 제안드렸는데, 
주 요점은 **requestCode가 다른 pendingIntent가 오도록 하는 것**이니 더 나은 방법이 있다면 그 방법대로 해주셔도 됩니다!

2023-10-17 07:43 UTC, Choisehyeon approved these changes

2023-10-17 18:41 UTC, sujin9 commented
수정된거 확인했습니다. notificationId를 쓰니 더 직관적이고 좋은 것 같아요!! 굿굿 어푸루브 할게요 ~~
안쓰는 로그들은 제가 삭제햇서욥 !

2023-10-17 18:41 UTC, sujin9 approved these changes

2023-10-18 01:13 UTC, merged