Refactor/#469 화질저하 리팩토링
woowacourse-teams/2023-edonymyeon pull request #475
Opened 2023-10-04 07:57 UTC by Choisehyeon

## 🔥 연관 이슈

- close: #469 

## 📝 작업 요약

사진을 촬영하여 올릴 시에 화질 저하 문제 개선

## 🔎 작업 상세 설명

이전에는 사진 촬영 시에 TakePicturePreview를 사용해서 사진의 썸네일 이미지를 Bitmap으로 얻어와 화질이 낮았던 문제가 생겼고 이를 개선함

## 🌟 리뷰 요구 사항

화질을 개선하는 방법이 카메라로 사진을 찍어서 그 사진을 저장한 후 uri를 통해 가져오는 방법 밖에 없는 것 같아서 그렇게 진행하였습니다! 
혹시  다른 좋은 방법이 있다면 알려주시면 감사하겠습니다😄 
Provider를 사용하여서 앱의 내부 캐시 저장소에 이미지를 임시 저장하도록 하고 갤러리에는 저장되지 않도록 하였습니다. 
캐시 저장소에 파일을 생성해서 이미지를 넣고 uri를 가져와서 launcher로 전달하기 위해서는 uri를 var 변수로 만들어야 했는데 혹시 더 좋은 방법이 있거나 리팩토링 해야할 부분이 있다면 알려주세요😊

그리고 카메라로 찍은 이미지가 회전하는 부분은 다른 pr에 넣어놔서 카메라 사진을 찍으면 회전이 되어서 나올겁니당😂
카메라 화질이 좋아졌는지도 확인 부탁드려요! 
애뮬레이터에서는 카메라를 찍어서 화질을 확인하는게 어려워서 갤럭시 노트 10+에서 확인했을 때는 화질이 좋았는데
다른 기기들도 확인해봐야할 것 같아여~!!

2023-10-04 09:07 UTC, rhkrwngud445 requested changes
고생했어요~! 
궁금한 점들 코멘트로 남겼어요! 이부분만 확인 부탁합니다~!

2023-10-04 09:07 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        takeCameraImage.launch(cameraUri)
경로만 넣어주면 알아서 내부 캐싱을 해주는걸까요?! 궁금합니다!

2023-10-04 13:55 UTC, Choisehyeon commented on android/app/src/main/res/xml/file_paths.xml
> +        name="my_images"
캐시 디렉터리의 경로를 지정하기 위한 코드인데요! 
위 코드는 my_images라는 이름의 캐시 디렉터리가 현재 디렉터리에 생성됩니다.
 
edonymyeon 네이밍을 써주는게 좋을 것 같네요! name을 변경해주도록 하겠습니다😄

2023-10-04 14:04 UTC, Choisehyeon commented on android/app/src/main/AndroidManifest.xml
> +        </provider>
> 일반적으로 타 앱과 데이터를 공유하려면 File URI를 통해 앱내 이미지에 대한 접근을 허용하였다. 하지만 안드로이드 7,0부터는 앱 외부에서 file://와 같은 File URI의 노출을 금지하는 StrictMode API보안 정책을 적용 및 호환상의 이유로 앱에서 파일 경로를 공유하는 것이 금지되었다.

> 이에따라 안드로이드에서는 Content URI를 활용하여 앱 내 데이터를 내보내고 이에 대한 임시 엑세스 권한을 부여하여 파일을 공유해야 한다. 이렇게 진행하면 권한 관리 및 안드로이드 시스템에서 제공하는 보안기능을 모두 활용할 수 있다.

이런 이유로 content URI를 가져와야하는데요! 이를 위해 File Provider를 사용해야했고 이렇게 manifest에 선언을 해주어야했습니다!
meta-data 요소는 FileProvider가 사용할 파일 경로를 정의하는 데 사용되고, file_paths.xml 파일을 로드하여 FileProvider가 사용할 파일 경로를 정의하는 일을 합니다!!

2023-10-04 14:14 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        takeCameraImage.launch(cameraUri)
``` 
val photoFile =
File.createTempFile("IMG_", ".jpg", this.cacheDir)
```

위 메서드를 통해 파일 이름은 "IMG_"로 시작하고 확장자는 ".jpg"로 끝나는 임시 파일을 생성되고 앱의 내부 캐시 디렉터리에 저장됩니다. 

```
cameraUri = FileProvider.getUriForFile(this, "$packageName.provider", photoFile)
```
이 코드를 통해 임시 파일의 Uri를 제공합니다!

this.cacheDir 캐시에 저장하기 위해서는 paths.xml에서도 cache-path로 작성해주어야 그 파일의 uri를 얻을 수 있어요!!

2023-10-04 15:34 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        takeCameraImage.launch(cameraUri)
아아 저도 이 부분에 대해서 고민을 하고 있었는데요!!
Android 시스템은 공간이 부족하거나 기타 이유로 인해 캐시 파일을 언제든지 삭제되고, 앱이 제거되면 삭제되기는 하지만 
사진을 찍고 uri를 얻기 위해 임시 파일을 생성하는 것이기 때문에 필요하지 않을 때 바로 삭제를 해주는게 좋을 것 같은데 시점이 고민이네요🧐

처음에는 액테비티가 destroy될 때 캐시 파일을 제거해주면 되겠다고 생각을 했어요!
그런데 destroy될 때 캐시 파일을 삭제하게 되면 uri가 유효하지 않아서 configuration change가 일어났을 때에도 uri가 유효하지 않게 될텐데 언제 캐시 파일을 제거해 주는 게 좋을까요??😂

2023-10-04 15:56 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        takeCameraImage.launch(cameraUri)
contentUri를 viewModel에서 가지게 하는 방법이 일단 생각나네요!
Activity에서 isChangingConfigurations 속성이 있네요 이것 활용해도 될 것 같습니다~

2023-10-04 15:59 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        takeCameraImage.launch(cameraUri)
uri가 안드로이드 의존이라 isChangingConfigurations 사용하시면 됩니다!

2023-10-05 07:06 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        takeCameraImage.launch(cameraUri)
오,, 이런 게 있는 지는 저도 처음 알았네요!!
아래 레퍼런스들을 참고해봐도 좋을 것 같아요! :)
https://developer.android.com/reference/android/app/Activity#isChangingConfigurations() 
https://grep.app/search?current=3&q=isChangingConfigurations&filter[lang][0]=Kotlin

2023-10-05 07:17 UTC, sujin9 approved these changes
안녕하세요 로피 !
확인해보니 화질 깨지던 현상이 사라졌네요 😊 👍 
제가 궁금한 점이나 리뷰들을 코비가 잘 남겨주셔서, 
더 추가적으로 드릴 말씀은 없는 것 같아 찾아본 레퍼런스 링크만 남겼어요 ㅎㅎ

2023-10-05 07:17 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        takeCameraImage.launch(cameraUri)
오,, 이런 게 있는 지는 저도 처음 알았네요!!
아래 레퍼런스들을 참고해봐도 좋을 것 같아요! :)
https://developer.android.com/reference/android/app/Activity#isChangingConfigurations()
[https://grep.app/search?current=3&q=isChangingConfigurations&filter[lang][0]=Kotlin](https://grep.app/search?current=3&q=isChangingConfigurations&filter%5Blang%5D%5B0%5D=Kotlin)

2023-10-06 16:14 UTC, sujin9 commented
앗차차
```kotlin
        private val contentValues = ContentValues().apply {
            put(MediaStore.Images.Media.DISPLAY_NAME, "ImageTitle${LocalDateTime.now()}")
            put(MediaStore.Images.Media.MIME_TYPE, "image/jpeg")
        }
```
공부 겸 코드 다시 보다가 발견했는데요!
`PostEditorActivity` 에 사용하지 않는 변수가 있서용! 👀

2023-10-12 04:37 UTC, Choisehyeon commented
오오 감사해요!!! 코드 수정 후 불필요한 변수가 생겼는데 모르고 있었네요😄 지웠습니다!

2023-10-16 04:40 UTC, rhkrwngud445 approved these changes
굳~

2023-10-16 04:44 UTC, merged