Feat/#468 회원정보수정
woowacourse-teams/2023-edonymyeon pull request #477
Opened 2023-10-04 10:07 UTC by sujin9

## 🔥 연관 이슈

- close: #468 

## 📝 작업 요약

회원정보수정 뷰 구현

## 🔎 작업 상세 설명

회원정보수정 뷰를 구현했습니다.
또한 기존 회원정보가 뷰에 보이도록 했어요.

연휴동안 api까지 해서 올리려고 했는데, 아직 api 배포가 되지 않아서 이 부분은 추후 실제 잘 되는지까지 확인해서 올릴게요.
우선 뷰 먼저 리뷰 요청 보냅니다!

## 🌟 리뷰 요구 사항

> 뷰,,라서 오래 걸릴 것 같진 않습니다만! 아래 포인트들 확인 부탁드려요. api 배포 전까지 머지되면 좋겠네요 😆 

### 리뷰 포인트 1
사진 선택 부분은 `PickVisualMedia`를 이용했습니다.
- 갤러리 관련하여 별도의 권한을 요구하지 않는다는 장점이 있고,
- SDK 버전이 30 미만이거나, SDK Extensions의 버전이 2미만일 경우에는 ACTION_OPEN_DOCUMENT가 자동으로 실행되므로 버전 문제도 없을 것으로 보여요.
- 프로필 사진 선택의 경우, 딱 한 장만 빠르게 쉭쉭 고를 수 있어 좋은 것 같구요.

ref.
https://developer.android.com/training/data-storage/shared/photopicker?hl=ko 
https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia 

여러분의 의견은 어떠신가요?

### 리뷰 포인트 2
기존 이미지(string)를 보여주고, 사진을 선택하면(Uri) 보여주고, 수정하면 사진(File)을 서버로 보내야 하는 상황이에요.
다음과 같은 방향으로 하고자 하는데, 놓치고 있는 부분이나 개선점이 있는지 궁금해요!

처음 viewModel이 init될 때 newImage는 기존 이미지 string값을 갖고 있습니다.
사진을 선택하면, newImage의 Uri를 string으로 변환하여 넣어줍니다. (바꾸려고 선택한 사진이 보이도록 하기 위해서)

서버로 전송할 때는,
original 이미지랑 비교했을 때 이미지가 바뀜 -> File로 만들어서 혹은 null (이미지 지운 경우) 전송
이미지가 바뀌지 않음 -> 무조건 null 전송
과 같은 매커니즘으로 하려고 하고 있어요.

2023-10-04 15:15 UTC, Choisehyeon approved these changes
하티 고생했어요😄
애뮬레이터로 확인해봤는데 뷰가 예쁘게 구현되었네요👍

저도 갤러리에서 이미지를 가져올 때 어떤 방식으로 가져올지 고민이 많았었는데요!
확실히 PhotoPicker를 사용하면 코드가 매우 간단해져서 보기에 좋더라구요. 
근데 이게 13 버전만 PhotoPicker가 잘 동작하고 나머지 버전에서는 ACTION_OPEN_DOCUMENT로 사진을 선택할 수 있는게 사진을 여러 장 가져올 때는 너무 단점으로 느껴져서 저는 intent로 갤러리에 접근하는 방식으로 구현했어요😄

근데 프로필 사진을 선택하는 경우에는 한 장만 선택하면 되는 거라서 photo picker를 사용해도 괜찮을 것 같아요! 
다만, 프로젝트 내에서  PostEditorActivity에서는 갤러리를 통해서 접근하는 방식을 사용하고 여기 회원 정보 수정에서는 photo picker를 사용하는데 같은 방식으로 구현하는게 좋을 지 그게 고민이네요🧐

2023-10-04 15:15 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateActivity.kt
> +        pickMultipleImage.launch(PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly))
photo picker를 활용하면 코드가 간단해지네요😄

2023-10-04 16:17 UTC, rhkrwngud445 requested changes
고생했습니다! 코멘트 2개 정도 남겼는데 확인 부탁드려요~!

2023-10-04 16:17 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateViewModel.kt
> +        _newProfileImage.value = null
null로 변경하여 livedata event를 발생시키는 이유가 있을까요?!

2023-10-04 16:17 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateActivity.kt
> +        pickMultipleImage.launch(PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly))
👍
<img width="892" alt="스크린샷 2023-10-05 오전 1 16 05" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/33768873/f4266431-c0dc-4cc9-945d-c41ca4970c19">
이것도 고려해볼만 하네요!

2023-10-05 09:08 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateViewModel.kt
> +        _newProfileImage.value = null
아이쿠 이 부분은 코드를 지운다는 걸 깜빡했네요! 고마워요 ~

2023-10-05 09:22 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateActivity.kt
> +        pickMultipleImage.launch(PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly))
오,, 이런 게 있군요!!
궁금해서 찾아보니, google play service를 이용하여 이러한 작동 원리를 갖는다고 해요.
https://medium.com/@debuggingisfun/android-photo-pickers-backward-compatibility-145a1f263ed 

그래서 실제로 이전 버전에서도 photo picker가 제대로 실행되는 지 보고 싶어서 
에뮬레이터도 돌려 보고, 내부 테스트를 올려 play store로도 다운을 받아보았는데
Android 10, 12 버전에서는 잘 적용이 되지 않더라구요 ㅠ_ㅠ 어떤 기준으로 되는 건지 좀 더 봐야할 것 같습니다..

2023-10-05 09:25 UTC, sujin9 commented
@Choisehyeon 피

> 근데 이게 13 버전만 PhotoPicker가 잘 동작하고 나머지 버전에서는 ACTION_OPEN_DOCUMENT로 사진을 선택할 수 있는게 사진을 여러 장 가져올 때는 너무 단점으로 느껴져서 저는 intent로 갤러리에 접근하는 방식으로 구현했어요😄 근데 프로필 사진을 선택하는 경우에는 한 장만 선택하면 되는 거라서 photo picker를 사용해도 괜찮을 것 같아요!

PhotoPicker를 사용하면 선택할 사진 개수 제한도 정할 수 있어 편리할 수 있을 것 같은데, 
로피의 말처럼 `ACTION_OPEN_DOCUMENT`가 좀 불편할 수 있을 것 같긴 해요 ㅠㅠ 
다만 프로필 사진의 경우 한 장 빠르게 선택하면 되는 거라 괜찮을 것 같다고 생각해서 구현하긴 했습니당

> 다만, 프로젝트 내에서 PostEditorActivity에서는 갤러리를 통해서 접근하는 방식을 사용하고 여기 회원 정보 수정에서는 photo picker를 사용하는데 같은 방식으로 구현하는게 좋을 지 그게 고민이네요🧐

저도 통일성이 고민입니다.. 성격이 다른 페이지라 상관없지 않을까 싶기도 하구요 🤔

2023-10-05 12:52 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateActivity.kt
> +        pickMultipleImage.launch(PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly))
저도 이 방법으로 구현을 해봤는데 실행이 안되더라구요ㅜㅜ

2023-10-11 07:06 UTC, rhkrwngud445 approved these changes
고생했어요~~

2023-10-11 07:08 UTC, merged