Feat/#476 회원정보수정 연동
woowacourse-teams/2023-edonymyeon pull request #481
Opened 2023-10-12 04:32 UTC by sujin9

## 🔥 연관 이슈

- close: #476 

## 📝 작업 요약

회원정보수정 및 닉네임 중복체크 api 연동했어요 !

## 🔎 작업 상세 설명

회원정보 수정 가능 (이미지 업로드, 이미지 삭제, 닉네임 변경)
수정 버튼이 비활성화 되는 경우
- 변화사항이 없는 경우
- 닉네임이 중복되는 경우
- 닉네임 글자수가 안 맞는 경우

## 🌟 리뷰 요구 사항

> 혹시나 놓친 오류 상황이 있다면 얘기해주세요.. 
위의 수정 버튼 비활성화 관련 -> 현재 테스트서버에 `세호짱` `레아공주` 계정 만들었으니 테스트할 때 이용하시면 됩니다 !

2023-10-12 07:23 UTC, Choisehyeon requested changes
안녕하세요 하티😉😉
근로하면서 기능 구현하느라 힘드셨을텐데 수고하셨습니다👍
닉네임을 변경하고 이미지를 변경하는 부분 잘 동작하는 거 확인했습니다!

QA 하면서 찾은 오류인데요!
1. API 33 버전에서 이미지 선택하는 버튼을 빠르게 연속으로 클릭하면 photoPicker가 누른 횟수 만큼 뜨는 오류가 있어요! 
2. 이미지를 갤러리에서 고르고 수정하기 버튼을 빠르게 클릭하면 어플이 종료되는 오류가 있어요!
두 가지 오류 다 버튼이 한 번만 클릭되도록 해야할 것 같아요~ 이 두 개의 오류 말고는 발견한 오류는 없습니다!!

2023-10-12 07:23 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateViewModel.kt
> +        }
when절로 리팩토링 해봐도 될 것 같아요!!

2023-10-16 04:37 UTC, rhkrwngud445 approved these changes
고생했어요~ 작은 코멘트하나만 확인 부탁해요~

2023-10-16 04:37 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateActivity.kt
> +            if (it == true) {
it으로도 충분할 것 같네요!

2023-10-18 08:48 UTC, Choisehyeon approved these changes
하티 잘 되는 거 확인했어요👍👍

2023-10-18 09:20 UTC, rhkrwngud445 approved these changes

2023-10-18 12:07 UTC, merged