feat/#17 게시글 상세 페이지 뷰 및 추천/비추천 기능 구현
woowacourse-teams/2023-edonymyeon pull request #49
Opened 2023-07-17 13:02 UTC by sujin9

## 🔥 연관 이슈

- close: #17 

## 📝 작업 요약

게시글 상세 페이지 관련 뷰를 그리고,
추천/비추천 관련 기능을 구현하였습니다.

## 🔎 작업 상세 설명

- 게시글 상세 페이지 뷰를 구현하였습니다.
    - 조회수/댓글수/스크랩수에 대한 Custom View를 구현하였습니다.
    - 추천/비추천과 비율을 보여주는 프로그레스 바를 구현하였습니다.
   
- 게시글 관련 Ui Model 및 도메인 모델, 그리고 둘을 잇는 Mapper를 구현하였습니다.

- ViewModel - Livedata를 데이터 바인딩에 적용하여 옵저빙 되도록 구현하였습니다. 

- 추천/비추천을 수행하면 프로그레스바가 변경됩니다.

## 🌟 리뷰 요구 사항

추가된 부분이 많아 시간이 좀 소요될 수 있을 것 같습니다.
도메인 모델이 잘 짜여졌는지, 
그리고 PostDetailActivity, PostDetailViewModel을 중심으로 MVVM 패턴에 맞게 잘 작성되었는지를 중심으로 봐주시면 좋을 것 같아요! :)

2023-07-17 17:57 UTC, rhkrwngud445 requested changes
고생했어요 하티!
ViewModel 잘 써준거 같아요!좀 더 바인딩을 활용해서 Activity, ViewModel 코드를 줄일 수 있을거 같긴 한데, xml을 왔다 갔다 하는 단점도 있으니 어떤 방향으로 개발 하면 좋을지 이야기 해봐도 좋을 것 같아요!

코멘트 조금 남겨 놓았으니 확인부탁해요~👍

2023-07-17 17:57 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModel.kt
> +    private val _recommendation = MutableLiveData<RecommendationUiModel>()
분리를 함으로써 추천여부가 변경이 될 때 post데이터가 또한 변경이 되는 점을 예방할 수 있겠네요👍

2023-07-18 01:41 UTC, Choisehyeon requested changes
고생했어요 하티😄
도메인 부분에 대한 검증은 같이 고민해봐야할 것 같아요!💪

2023-07-18 01:41 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
> +    }
ViewModel 초기화 하는 부분을 통일하면 좋을 것 같아서 같이 얘기해봐야 할 것 같아요!

2023-07-18 01:41 UTC, Choisehyeon commented on android/domain/src/main/java/com/domain/edonymyeon/model/Recommendation.kt
> +    val downCount: Int,
upCount와 downCount에 대한 검증을 해주면 좋을 것 같아요!

2023-07-18 01:41 UTC, Choisehyeon commented on android/domain/src/main/java/com/domain/edonymyeon/model/Post.kt
> +    val content: String,
이 부분에 대해서 검증이 필요한지에 대해 같이 고민해야할 것 같아요😄

2023-07-18 01:41 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
> +                }
이 부분을 함수로 추출해도 괜찮아보여요!

2023-07-18 04:49 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
> +                }
해당 아이콘을 selector drawable을 이용한 커스텀 체크박스로 수정하면서 40~44 라인이 필요없어졌어요!
해당 라인은 삭제하도록 하겠습니다 :)

2023-07-18 06:00 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
> +    }
캠퍼스에서 얘기한 대로 `by viewModels` 를 활용하는 걸로 통일할게요!  :)

2023-07-18 06:04 UTC, sujin9 commented on android/domain/src/main/java/com/domain/edonymyeon/model/Post.kt
> +    val content: String,
좋아요! 
이 부분은 논의해서 title, price, content에 대한 입력을 받는 로피의 코드를 합친 후에
같이 리팩토링 해보는건 어떨까요 ~?

2023-07-18 06:10 UTC, sujin9 commented on android/app/src/main/res/layout/activity_post_detail.xml
> +                    android:layout_height="12dp"
이 부분은 제가 우선 고정값으로 뒀던 건데 수정한다는 걸 잊어버렸네요!! :(
비율값으로 수정했습니다. 알려줘서 고마워요!! 😃

2023-07-18 09:03 UTC, sujin9 commented
남겨주신 피드백들도 적용하고,
Count 도메인 모델을 구현하여 적용하였습니다.
또한 Recommendation과 Count domain model에 대한 테스트도 추가적으로 구현했습니다!
다시 한 번 리뷰 부탁드려요,, 🌹

2023-07-18 09:11 UTC, rhkrwngud445 approved these changes
테스트가 꼼꼼하네요! 수고했어요 하티!

2023-07-18 11:01 UTC, Choisehyeon approved these changes
도메인에 대한 검증과 테스트를 잘 해주셨네요! 하티😄
수고했어요!!👍

2023-07-18 11:16 UTC, merged