Feat/#18 게시글 작성,수정 페이지 구현
woowacourse-teams/2023-edonymyeon pull request #51
Opened 2023-07-17 15:02 UTC by Choisehyeon

## 🔥 연관 이슈

- close: #18 

## 📝 작업 요약

게시글 작성/수정 페이지 뷰 구현
게시글 작성/수정 페이지 카메라 촬영 구현
게시글 작성/수정 페이지 갤러리 사진 선택 구현

## 🔎 작업 상세 설명

- 게시글 작성/수정 페이지에서 edittext를 사용하여 글을 작성할 수 있도록 하였습니다.
    - 여기서 제목은 30글자, 내용은 1000글자를 max로 지정했습니다.
- 카메라 촬영과 갤러리 선택을 통해 사진을 선택할 수 있고 최대 10장까지 고를 수 있도록 하였습니다. 
    - 10장이 넘어가면 Toast 메세지를 출력합니다. 
- 사진을 선택하면 하단의 리사이클러뷰로 사진이 보여집니다. 
    - 사진에서 x버튼을 클릭하면 사진을 삭제할 수 있습니다.
- 카메라와 저장소에 접근하고자 권한을 받도록 구현했습니다. 

## 🌟 리뷰 요구 사항

>  카메라와 갤러리를 사용해야해서 코드가 길어져서 리뷰하는데 시간이 좀 걸릴 것 같아요! 어댑터를 listadapter로 처음 구현해보았는데 그 부분에 대해서 리뷰 해주시면 좋을 것 같고, ViewModel 과 binding 부분에 대해서도 리뷰 부탁드려요! 저도 MVVM 패턴을 맞게 쓰고 있는지 궁금합니다 많은 의견 부탁드려요😄

2023-07-18 02:14 UTC, sujin9 requested changes
고생 많았어요, 로피!! 👍 😊 
몇 가지 의견들을 코멘트에 남겨보았어요~
그리고 앱을 실행해봤는데요, 카메라로 사진을 촬영하면 
권한을 물어보는 부분이 뜨지 않고 권한 이슈로 앱이 종료되어 버려요! 😢

2023-07-18 02:14 UTC, sujin9 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +            Toast.makeText(applicationContext, "사진은 10장까지 선택 가능합니다.", Toast.LENGTH_LONG).show()
Toast를 사용해주셨는데 Snackbar도 한 번 고려해주시면 좋을 것 같아요! :)

Toast 같은 경우에는 set/getView가 deprecated 되어 커스텀이 어렵고,
Snackbar 같은 경우 사용자와 상호작용(간단한 액션)을 하거나 
메시지를 스와이프해서 지우는 등의 이벤트가 가능하여 더 편리할 것 같다고 생각이 들어요 :)

[공식문서](https://developer.android.com/reference/android/widget/Toast)
[참고할 만한 블로그](https://brunch.co.kr/@oemilk/91)

2023-07-18 02:24 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
넵 수정하겠습니다!

2023-07-18 02:25 UTC, Choisehyeon commented on android/app/src/main/res/layout/activity_post_editor.xml
> +            android:textColorHint="@color/gray_434343"
저도 구분하는게 좋을 것 같아요! 같은 색깔로 하다보니 구분이 안되는 것 같았어요!

2023-07-18 02:25 UTC, Choisehyeon commented on android/app/src/main/res/layout/activity_post_editor.xml
> +        <View
오오 이런게 있었네요! 감사합니다😄

2023-07-18 02:36 UTC, rhkrwngud445 requested changes
고생했어요 로피! 전체적으로 어렵고 많은 코드인데 빠르게 잘 해주었네요!
Camera, 갤러리 좀 더 자료 조사가 필요 할 거 같아서 일단 다른 부분만 리뷰를 했습니다!
저도 좀 더 좋은 방법이 있나 찾아 볼게요~!😀

2023-07-18 02:36 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/adapter/PostEditorImagesAdapter.kt
> +        val diffUtil = object : DiffUtil.ItemCallback<String>() {
따로 분리가 되어도 좋을 것 같아요!

2023-07-18 02:36 UTC, rhkrwngud445 commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/viewholder/PostEditorImagesViewHolder.kt
> +        }
ViewHolder의 itemView를 활용해서 좀 더 캡슐화를 할 수 있을 거 같아요!

2023-07-18 04:39 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +            Toast.makeText(applicationContext, "사진은 10장까지 선택 가능합니다.", Toast.LENGTH_LONG).show()
이번 같은 경우에는 상호작용이 필요없을 것 같아 Toast로 구현을 해봤는데 Snackbar로 구현하는게 나중에 확장성을 위해서도 좋을 것 같네요!

2023-07-18 04:42 UTC, Choisehyeon commented on android/app/build.gradle.kts
> +    implementation("androidx.activity:activity-ktx:1.7.2")
이 부분은 제가 라이브러리를 가져올 때 잘못 추가해서 가져온 부분인 것 같아요! 수정할게요!

2023-07-18 04:49 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +    private lateinit var adapter: PostEditorImagesAdapter
한 번 초기화 되고 나면 변경될 일이 없기 때문에 by lazy를 쓰는게 맞을 것 같네요!

2023-07-18 05:03 UTC, Choisehyeon commented on android/app/src/main/AndroidManifest.xml
> +        tools:ignore="ScopedStorage" />
이 부분은 sdk 28 버전에서 카메라에 접근해 사진을 찍고 그 사진을 가져올 때 WRITE_EXTERNAL_STORAGE를 사용해주어야해서 넣어줬습니다. android 10(28) 이후부터는 ScopedStorage를 사용해서 미디어 접근을 할 수 있는데 28의 경우에는 WRITE_EXTERNAL_STORAGE 권한을 사용해야했기 때문에 ScopedStorage를 제한해야 경고가 뜨지 않아요😂

2023-07-18 05:27 UTC, Choisehyeon commented on android/app/build.gradle.kts
> +    implementation("androidx.activity:activity-ktx:1.7.2")
by viewModels()를 사용하기 위해서 필요한 종속성이라 추가해주었습니다!

2023-07-18 06:22 UTC, Choisehyeon commented on android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
> +        registerForActivityResult(ActivityResultContracts.TakePicturePreview()) { bitmap ->
> public class [ActivityResultContracts.TakePicturePreview](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContracts.TakePicturePreview) extends [ActivityResultContract](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContract)
An [ActivityResultContract](https://developer.android.com/reference/androidx/activity/result/contract/ActivityResultContract) to [take small a picture](https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE()) preview, returning it as a [Bitmap](https://developer.android.com/reference/android/graphics/Bitmap.html).

이 코드는 바로 Bitmap을 반환하기 때문에

2023-07-18 12:25 UTC, Choisehyeon commented
리뷰 반영해서 수정해보았습니다! 퍼미션에 대한 분기처리도 작성해서 올렸습니다😄
확인 후 리뷰 부탁드려요!!

2023-07-18 13:56 UTC, sujin9 reviewed
고생 많았어요 로피!! 😍
고칠 점 없이 잘 수정된 것 같아요~

다만, 마지막으로 현재 에뮬레이터(API 28), 실 기기(API 33)에서 테스트 해봤는데요 !
28 버전에서는 카메라 실행 시 권한을 묻는 다이얼로그가 발생한 후 촬영까지 이어지고,
33 버전에서는 권한이 없다는 스낵바 메시지만 발생해요.
이 때, 권한을 얻기 위해 직접 앱 설정에 들어가 권한을 받는 과정이 번거로울 수도 있다고 생각이 들어요!
그래서 저는 이 부분에 대해서 개선이 필요할 것 같다고 생각이 들었는데, 코비와 로피의 의견은 어떠신가요? 🤔

이미 알고계셨을 수도 있겠지만, 조금 찾아보니 API 33부터 READ_EXTERNAL_STORAGE이 세분화가 되었다는 것 같아요!
이 부분에 대한 분기처리도 필요한건 아닐까 하는 생각이 드는데, 한 번 참고해보셔도 좋을 것 같아요! :)
어려운 부분이 있거나 고민되는 부분이 있다면 내일 같이 얘기해요 ~ 😄 
([참고 블로그 링크](https://salmonpack.tistory.com/46))

2023-07-19 01:44 UTC, Choisehyeon commented
권한 부분 관련해서 33의 경우 권한이 없이 갤러리에 접근 및 TakePicturePreview를 사용할 수 있어서 권한을 분기처리 해서 적용해 주었습니다!
저도 권한이 없을 때 스낵바만 보여지고 설정 화면에 직접 들어가야하는 것이 사용자들이 번거로울 수 있는 작업이라는 생각이 들어 스낵바를 사용해서 상호작용을 하면 앱 설정화면으로 이동해서 권한을 설정할 수 있도록 수정해주었습니다!!😄

2023-07-19 05:07 UTC, sujin9 approved these changes
기능도 피드백도 많았는데 
고생했어요 로피!! :)

2023-07-19 06:37 UTC, rhkrwngud445 approved these changes
어려운 기능인데 빠르게 구현해 주셨네요! 고생했습니다 로피!

2023-07-19 07:40 UTC, merged