Feat/#499 알림메시지 변경하기
woowacourse-teams/2023-edonymyeon pull request #511
Opened 2023-10-19 04:37 UTC by BackFoxx

## 🔥 연관 이슈

- close: #499 

## 📝 작업 요약

원하는 알림 항목의 알림 메시지를 수정할 수 있는 API를 제공한다.

## 🔎 작업 상세 설명

* PUT 메서드로 /admin/notification/message 를 호출하여 알림 메시지를 수정할 수 있습니다.
* 권한 설정이 되어있지 않으므로 uri만 알고 있다면 누구나 호출할 수 있습니다.
* 알림 메시지에 %title, %comment, %count를 포함하는 경우 각각 포스트 제목, 댓글 내용, 따봉 개수로 치환해 표시합니다.
예) [%title] 글에 댓글이 달렸습니다. -> [아 소고기 먹고싶다~~~] 글에 댓글이 달렸습니다.

## 🌟 리뷰 요구 사항

예상치 못한 버그가 있을 수 있읍니다.

2023-10-30 08:39 UTC, jyeost requested changes
안녕하세여 여우!!!! 
잘 해주셨군여... 
제가 시켜놓고 리뷰 너무 늦게봐서 죗성합니다....

pr이 알림 메세지를 추가 & 어드민으로 알림 메세지를 변경 
이 두가지 기능을 담고 있으니 읽기 힘들더라고여... 
나눠서 줬으면 조앗을거 같은데,,,,, ㅜㅜ

그리고... 제목 길이나 댓글 길이가 길면 ... 으로 축약해달라고 부탁드렸는데 
어디에 구현 되어 있는지 못찾았어여...ㅜㅜ 알려주심 감사홥돠

2023-10-30 08:39 UTC, jyeost commented on backend/src/main/resources/db/migration/mysql/V1.4.0__notification_content.sql
> +(
전 이넘으로 관리할 생각을 했는데 여우는 어드민까지 생각해서 
DB 에 저장해주셨군여 !!

이 pr이 머지되면 테스트 서버와 운영서버에 직접 insert 해주는 건가요??

2023-10-30 08:39 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/notification/ui/NotificationController.java
> +    public ResponseEntity<Void> updateNotificationMessage(@RequestBody NotificationContentRequest notificationContent) {
나중에 어드민이 커지면 그쪽 컨트롤러로 옮겨가는 게 성격이 맞아보며유

2023-10-30 08:39 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/notification/domain/Notification.java
>  @Entity
getter를 직접 만들어 준 이유가 있나요??

2023-10-30 08:39 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +                = notificationMessageRepository.findById(notificationContentId)
멍가... 알람 메세지를 바꾸는 일은 자주 있지 않고... 
자주 쓰일 것 같은데... 
스프링 띄우면서 빈 등록할 때... 로컬에 저장해서 거기서 꺼내오는 방법이 없을꽈.... 
고민 중.... 
업데이트 시에 같이 업데이트도 해주면서 ,,,, 업을꽈.... 

개행 너무,,, 마음이 답답함니다

2023-10-30 08:39 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/member/repository/MemberRepository.java
> +    Optional<Member> findByNickname(String nickname);
이거 왜 추가되어 잇나묭

2023-10-30 08:39 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +                    notificationContent.getTitle(notificationContentParameters)
body는 안보내고 있는 것 같아요 !

2023-10-30 08:39 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/notification/domain/notification_content/domain/NotificationContent.java
> +    private String applyDSLs(final String target, final Map<String, String> parameters) {
applyDSL이 무슨 뜻인지 모르겠어요...

2023-10-30 11:26 UTC, hectick requested changes
🦊👏
좀만 더 고생해주십시옹!!

2023-10-30 11:26 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationService_NotificationMessageTest.java
> +            assertThat(savedNotification.get(0).getBody()).isEqualTo("[신발 사도 될까요?] 글에 [그 돈이면 국밥이 90그릇] 댓글이 달렸습니다. 본문");
title은 무슨 용도고 body는 무슨용도인가요? 상세한 예시를 주시겠어요?
현재는 둘이 용도가 똑같아보여요
(코드를 고치란 뜻은 아니고 댓글로 설명해달란 뜻)

TITLE: [신발 사도 될까요?] 글에 댓글이 달렸습니다
BODY: 그돈이면 국밥이 90그릇
요런느낌은 어떤가욤

2023-10-30 11:26 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationService_NotificationMessageTest.java
> +            assertThat(savedNotification.get(0).getBody()).isEqualTo("[신발 사도 될까요?] 글에 새로운 반응 0건이 있습니다. 본문");
이건 그냥 하는말이긴한데
`새로운 반응`이면 count값은 항상 1 또는 10이어야하지 않을까요?
반응이 %count건 돌파했습니다. 이러면 어느 숫자든 가능하겠지만요!

2023-10-30 11:26 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +                = notificationMessageRepository.findById(notificationContentId)
`@PostConstruct` 이런거 사용하면 되려나요?
애플리케이션 뜰때 한번 캐싱해두고 사용하고, 스프링 애플리케이션떠있을때 api로 메세지 수정 요청들어오면 그때만 업데이트해주고?!

2023-10-31 01:16 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +                = notificationMessageRepository.findById(notificationContentId)
좋은데여?

2023-10-31 01:25 UTC, jyeost commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationService_NotificationMessageTest.java
> +            assertThat(savedNotification.get(0).getBody()).isEqualTo("[신발 사도 될까요?] 글에 [그 돈이면 국밥이 90그릇] 댓글이 달렸습니다. 본문");
<img width="379" alt="image" src="https://github.com/woowacourse-teams/2023-edonymyeon/assets/103317169/b165f0d3-6d89-418d-92ae-b7dfafef5009">
이런 내용으로 제안했어요 !
근데 지금 알림 조회가 3개월로 되어있나???

2023-10-31 01:47 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationService_NotificationMessageTest.java
> +            assertThat(savedNotification.get(0).getBody()).isEqualTo("[신발 사도 될까요?] 글에 [그 돈이면 국밥이 90그릇] 댓글이 달렸습니다. 본문");
아
title: 댓글 알림
body: [순댓국 사먹어도 되나..] 글에 [이돈이면 맥날 사먹는..] ~
이런 느낌이군용

2023-10-31 04:14 UTC, This2sho approved these changes
고생이 많네요 여우상
이리내랑 케로가 열심히 남겨줘서 궁금한 부분만 커맨트 남겼습니다!
저는 어프로브하고 푸시하면 확인할게염👍

2023-10-31 04:14 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/notification/domain/Notification.java
> +    private String body;
`title`이랑 `body`랑 같이 값 객체로 묶어보는건 어때여?
이전에 사용하던 NotificationMessage 같은 네이밍으로 ?!

2023-11-03 01:46 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/domain/Notification.java
>  @Entity
조만간 롬복 파기작업을 할거에요 .. 사용하지 않는 게터가 도메인 객체에 너무 많은 건 좋지 못한 것 같소

2023-11-03 01:46 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/ui/NotificationController.java
> +    public ResponseEntity<Void> updateNotificationMessage(@RequestBody NotificationContentRequest notificationContent) {
맞아요 어드민 권한도 만들어야 하고.. 회원 권한을 관리하는 방법은 회의를 통해 정해야겠는데욥

2023-11-03 01:48 UTC, BackFoxx commented on backend/src/main/resources/db/migration/mysql/V1.4.0__notification_content.sql
> +(
@hectick 하려면 넣을 수 있는데, 우리 DB는 인메모리가 아니기 때문에 서버를 가동할 때마다 같은 알림 메시지 정보가 중복으로 저장될 거에요!

2023-11-03 01:54 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +                = notificationMessageRepository.findById(notificationContentId)
으음 정리하면 ,,
* 알림 메시지를 데이터베이스에 저장하는 형태는 유지한다
* 그러나 알림을 발송할 때마다 DB에서 메시지를 조회할 필요는 없으니 애플리케이션을 실행할 때 @PostConstruct를 사용, DB의 메시지를 메모리에 캐싱해두고 사용한다.
* 알림 메시지가 변경되었을 때는 DB에 반영함과 동시에 캐싱된 값도 수정한다

이렇게 이해했어요! 한번 개선해볼게요 🫠

2023-11-05 03:18 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/domain/notification_content/domain/NotificationContent.java
> +    private String applyDSLs(final String target, final Map<String, String> parameters) {
[도메인 특화 언어(Domain-Specific Languages)](https://www.jetbrains.com/ko-kr/mps/concepts/domain-specific-languages/)라고 해서 특정한 도메인이나 분야에서 사용하는 프로그래밍 규칙같은 것을 뜻해요! 우리가 흔하게 쓰는 정규식이나 JPQL등도 규칙에 맞게 문자열을 작성하면 프로그램이 읽어서 실행해주는데, 이것들도 DSL이기 때문이에요.

applyDSL이라는 명칭은 조금 더 쉽게 바꿔둘게요! 🥲

2023-11-05 03:19 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/application/NotificationService.java
> +                    notificationContent.getTitle(notificationContentParameters)
애플리케이션에서 알림의 body를 표현하는 API를 아직 클라이언트 측과 협의하지 못했어요!

2023-11-05 04:09 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/notification/application/NotificationService_NotificationMessageTest.java
> +            assertThat(savedNotification.get(0).getBody()).isEqualTo("[신발 사도 될까요?] 글에 새로운 반응 0건이 있습니다. 본문");
맞네요! '반응의 총 개수'랑 '새로운 반응의 개수'가 헷갈릴 여지가 있군요.
일단은 테스트코드가 문서 역할을 대신하고 있어서, 테스트 코드에서 해당 내용을 더 명확히 표현하도록 개선했어요!

2023-11-05 04:10 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/domain/Notification.java
> +        return id;
헉 !

2023-11-05 05:18 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/notification/ui/NotificationController.java
> +    public ResponseEntity<Void> updateNotificationMessage(@RequestBody NotificationContentRequest notificationContent) {
요건 혼자서 잘 못하겠어요 🥹 화요일에 같이 해주라

2023-11-05 05:37 UTC, closed without merging