Feat/#9 게시글 전체 조회 기능
woowacourse-teams/2023-edonymyeon pull request #68
Opened 2023-07-19 06:15 UTC by BackFoxx

## 🔥 연관 이슈

- close: #9 

## 📝 작업 요약

프로젝트에 등록된 모든 게시글을 조건에 맞게 조회하는 기능입니다.

## 🔎 작업 상세 설명

* /posts로 GET 요청을 보내면 프로젝트에 저장된 게시글 목록을 응답합니다.
* 별도의 queryString을 명시하지 않으면 한 번에 20개씩, 등록 시각 기준으로 내림차순 정렬합니다.
* size 파라미터를 지정하면 (예시: /posts?size=10) 한 번에 가져올 게시글 개수를 조절할 수 있습니다.
* page 파라미터를 지정하면 (예시: /posts?page=2) 가져올 게시글의 페이지를 조절할 수 있습니다.
* size와 page는 동시에 지정할 수 있습니다.  (예시: /posts?page=2&size=15)
* 등록된 게시글이 없을 경우 빈 배열을 응답합니다.

### 주의사항
* ImageFileNameMockStrategy의 구현 방법이 변경되었습니다. 
해당 Strategy로 인해 테스트가 깨지는 경우 여우에게 문의 바랍니다.

2023-07-19 08:07 UTC, This2sho reviewed
고생많으셨습니다 🦊
코드 확인하고 궁금한 것들 댓글 남겼습니다~

2023-07-19 08:07 UTC, This2sho commented on backend/src/main/java/edonymyeon/backend/post/application/dto/SortBy.java
> +    CREATE_AT("createAt");
이거 이제보니까 Post에서 `createAt`이 아니라 `createdAt`이 맞는거 같네요 😂

2023-07-19 08:07 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/controller/PostControllerTest.java
> +        게시글_하나를_등록한다3();
한글 메서드 👍

2023-07-19 08:07 UTC, This2sho commented on backend/src/test/java/edonymyeon/backend/controller/PostControllerTest.java
> +                .andExpect(status().isCreated());
테스트 객체 생성 중복을 제거할 방법을 같이 찾아볼까요 🦊 ?!

2023-07-19 08:50 UTC, jyeost reviewed
여우 코드 잘봤서용 >< 
얻어갈 것이 많더라구여 ㅎㅎ
너무 수고했습니다

2023-07-19 08:50 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +    }
확실히 서비스에서 new 로 만들어 주니 너무 복잡한 것 같아여
response 객체 안에서 정팩매로 만들어 주는 것이 아름다울 듯 ◡̈

2023-07-19 08:50 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +                        post.getPostImageInfos().get(0).getFullPath(),
해당 게시글에 사진첨부가 안되어 있는 경우 `IndexOutOfBoundsException` 발생 하나요??

2023-07-19 08:50 UTC, jyeost commented on backend/src/main/java/edonymyeon/backend/post/ui/PostController.java
> +                .body(postService.findAllPost(postFindingCondition));
findAllPost가 가장 메인이 되는 메서드 같은데 바디 안에 들어있으니 잘 안보이는 것 같아요 
따로 빼보는 건 어떤가용?!

2023-07-19 08:56 UTC, hectick reviewed
고생햇슴다

2023-07-19 08:56 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +                )).toList();
변환로직이 길어지면 dto 내부에 정적 팩토리 메서드를 만들어서 맡기는 것은 어떤가요?!

2023-07-19 08:56 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/dto/PostFindingResponse.java
> +        int commentCount
가격 정보(price)가 빠졌어요!(API 명세)

2023-07-19 08:56 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/dto/WriterResponse.java
> +
지금 merge된 브랜치들 풀 받으면 id랑 profileImage도 추가해주세요! (API 명세)

2023-07-19 08:56 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/dto/PostFindingResponse.java
> +        int commentCount
현재 노션 API 에 있는 카운트 관련 형태입니당.
```
"게시글 카운트(reactionCount)": {
		"조회수(viewCount)": 123, 
		"댓글수(commentCount)": 21,
		"스크랩수(scrapCount)": 33,
}
```
 아직 필드에 없는 값들도 남아있으니 나머지도 추후에 구현하면서 확인해보셔용

2023-07-19 08:56 UTC, hectick commented on backend/src/test/java/edonymyeon/backend/service/PostServiceFindingAllPostsTest.java
> +    private MemberIdDto memberId;
여기부분은 컨벤션!! 필드 한줄씩 띄기!!

2023-07-19 08:56 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +                    case DESC -> Direction.DESC;
어차피 Direction.ASC, Direction.DESC로 바꿀건데 원래부터 이것을 안쓰고 SortDirection 클래스를 만들어서 사용한 이유가 무엇인지 궁금합니당. 바로 Direction을 쓰면 switch없이 바로 postFindingCondition.getDirection()으로 가져올 수 있을텐데요!

2023-07-19 08:56 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +                        post.getPostImageInfos().get(0).getFullPath(),
여기서 ImagoInfos가 빈 리스트여도 get(0)이 잘 동작하나요?

2023-07-19 16:24 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +    }
정팩메 반영했습니다 ~~

2023-07-20 01:03 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/dto/PostFindingResponse.java
> +        String imagePath,
이미지 부분 설명이 그냥 TODO로 되어있어서 이름을 제맘대로 지었어요 🥲 지송

2023-07-20 01:04 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/dto/SortBy.java
> +    CREATE_AT("createAt");
조아요

2023-07-20 01:05 UTC, BackFoxx commented on backend/src/test/java/edonymyeon/backend/controller/PostControllerTest.java
> +                .andExpect(status().isCreated());
조아요~~ 일단은 쪼금 후순위라 리팩토링브랜치 따로 파서 작업하겠습니다

2023-07-20 01:08 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +                        post.getPostImageInfos().get(0).getFullPath(),
헊,,, 버그 일어날 뻔했네요 수정했습니다

2023-07-20 01:10 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/dto/PostFindingResponse.java
> +        int commentCount
보내주신 카운트 형태는 게시글 상세조회 API에용! 전체 조회 API에는 reactionCount로 감싸져 있진 않네욥

2023-07-20 01:13 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/dto/WriterResponse.java
> +
이것도 상세조회 명세에요!

2023-07-20 01:17 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +                    case DESC -> Direction.DESC;
postFindingCondition은 컨트롤러에서 만들어서 서비스로 보내는데, 
JPA에서 제공하는 Direction을 컨트롤러에서 만드는 형태로 구현한다면
컨트롤러가 JPA에 의존하는 형태가 될 수 있다고 생각했습니다!

쿼리를 매핑하는 방식이 JPA에서 다른 방식으로 변경되는 경우(JDBCTemplate을 쓴다던가)는 꽤 흔해서
최대한 JPA에 안 의존하는 컨트롤러를 만들고 싶었어용

2023-07-20 01:18 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/application/PostService.java
> +                        post.getPostImageInfos().get(0).getFullPath(),
버그나겠네요! 수정했습니다

2023-07-20 01:40 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/dto/PostFindingResponse.java
> +        int commentCount
그르네용 ~! 안드한테 물어봐서 게시글 전체조회 api 문서도 저 형태로 업뎃하엿습니다!!

2023-07-20 01:54 UTC, hectick requested changes

2023-07-20 01:54 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/dto/PostFindingResponse.java
> +        int commentCount
전체적으로 제가 전체조회용 PostFindingResponse를 상세조회용으로 착각한 것 같네요 둘의 dto이름을 명확히 분리하면 더 좋을것 같아요!! (ex. General~, Specific ~)

2023-07-20 01:54 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/dto/WriterResponse.java
> +
그렇네요 저의 실수 ㅜㅜ!!

2023-07-20 01:54 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/application/dto/PostFindingResponse.java
> +                post.getPostImageInfos().size() == 0 ? null : post.getPostImageInfos().get(0).getFullPath(),
여기 .getFullPath() 호이의 [사진 반환 pr](https://github.com/woowacourse-teams/2023-edonymyeon/pull/85) merge 되면 .getUrl()로 바꿔야 하는 부분입니다 ‼️잊지 말아주세옹

2023-07-20 01:58 UTC, hectick commented on backend/src/main/java/edonymyeon/backend/post/ui/PostController.java
> +    public ResponseEntity<List<PostFindingResponse>> findAllPosts(
![image](https://github.com/woowacourse-teams/2023-edonymyeon/assets/62106852/7f005776-871e-4ff4-b242-930ca4d585c5)
리스트가 아니라 Posts로 한번 더 감싸서 반환해야해요!

2023-07-20 02:09 UTC, BackFoxx commented on backend/src/main/java/edonymyeon/backend/post/ui/PostController.java
> +    public ResponseEntity<List<PostFindingResponse>> findAllPosts(
코멘트 주신 거 반영했어요~~~

2023-07-20 02:23 UTC, This2sho approved these changes

2023-07-20 02:27 UTC, jyeost approved these changes

2023-07-20 02:28 UTC, hectick approved these changes

2023-07-20 02:30 UTC, merged